"""Rebuild each addon's enUS manifest, then sync the shared store from both addons.

    python scan.py            # report only
    python scan.py --apply

The manifest is a pure function of an addon's own code, so it is still written into
that addon's repo - each one keeps a self-contained Locales/enUS.lua and its CI keeps
passing on a lone checkout. What is shared is the TRANSLATIONS.

Sync moves in three directions:

  import   a translation an addon has that the store does not -> into the store
  retire   a store phrase no addon uses any more              -> into store/_retired
  revive   a retired phrase an addon has started using again  -> back into the store

Retiring rather than deleting is the point of the whole design. Everything Quests
v1.38.0 moved 224 phrases to EQ Objective Tracker and every one of them orphaned on
one side and came up untranslated on the other. A retired phrase costs nothing and
comes back automatically the moment some addon asks for it again.
"""
import io
import os
import sys
import glob

import addons
import lualocale as lua

# The conflict report below prints two translations side by side, and a Windows console
# hands Python a cp1252 stdout - which raises UnicodeEncodeError on the first Cyrillic or
# CJK character and kills the run PART WAY THROUGH THE WRITES. check.py wraps its phrase
# reports in ascii() against the same hazard, but that renders a translation unreadable and
# reading the two side by side is the whole point here. So widen the stream instead.
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
if hasattr(sys.stderr, 'reconfigure'):
    sys.stderr.reconfigure(encoding='utf-8', errors='replace')

MANIFEST_FOOTER = [
    '-- Convert the `true` sentinels to their key (the self-keyed English default).',
    'for k, v in pairs(L) do if v == true then L[k] = k end end',
]

STORE_HEADER = '''-- store/%(code)s.lua
-- %(lang)s (%(code)s) translations for the Everything Quests addon family.
--
-- HOW TO USE: type the %(lang)s translation between the quotes after each "=".
-- The English text is the key inside L["..."]. Example:
--     L["Hide tracker in combat"] = "..."
--
-- This is the single source of %(lang)s for EVERY addon in the family. Which addon
-- a phrase belongs to is decided when the locale files are built, so a phrase that
-- moves from one addon to another keeps its translation with no work from anyone.
-- store/_phrases.lua lists every phrase in use and which addon uses it.
--
-- KEEP THESE EXACTLY AS THEY APPEAR (do not translate them):
--   |cffaaaaaa ... |r   -> color codes
--   %%d  %%s              -> numbers / names get inserted here
--   %%1$s  %%2$d          -> the same, when the order has to change in %(lang)s
--   \\n                  -> line break
--   \\"                  -> an escaped quote inside the text
--
-- A phrase left out of this file simply renders in English, so a partial
-- translation is always safe. Sorted by English key.

local L = {}
'''

RETIRED_HEADER = '''-- store/_retired/%(code)s.lua
-- %(lang)s translations for phrases no addon in the family currently uses.
--
-- NOT dead. A phrase lands here when the last addon using it drops or rewords it,
-- and scan.py moves it straight back into store/%(code)s.lua the moment any addon
-- starts using that exact English key again. Everything Quests v1.38.0 moved 224
-- phrases to EQ Objective Tracker in one release - this is what stops that costing
-- a translation.
--
-- Nothing here reaches the game. There is no reason to translate anything in this
-- file, and no reason to delete anything from it either.

local L = {}
'''

PHRASES_HEADER = '''-- store/_phrases.lua
-- GENERATED by scan.py. Do not hand-edit.
--
-- Every English phrase the family currently uses, grouped by the addon and source
-- file it comes from, so a translator can see what a phrase is FOR before choosing
-- a word for it. A phrase used by more than one addon is listed under each.
--
-- This is the worklist. Translate into store/<language>.lua, never in here.

local L = {}
'''


def scan_source(addon):
    """(file order, {file: [source key]}, {decoded: source key})."""
    cfg = addons.ADDONS[addon]
    cwd = os.getcwd()
    os.chdir(cfg['path'])
    try:
        files = [p.replace('\\', '/') for p in glob.glob('**/*.lua', recursive=True)]
        files = [p for p in files
                 if not any(p.startswith(s) for s in cfg['skip'])
                 and not any(s in p for s in cfg['skip_contains'])]
        order = ([f for f in cfg['preferred'] if f in files]
                 + sorted(f for f in files if f not in cfg['preferred']))
        seen, by_file, srckeys = set(), {}, {}
        for path in order:
            text = lua.strip_comments(
                io.open(path, encoding='utf-8', errors='replace').read())
            for m in lua.KEY_USAGE.finditer(text):
                raw = m.group(1)
                if raw in seen:
                    continue
                seen.add(raw)
                srckeys[lua.decode(raw)] = raw
                by_file.setdefault(path, []).append(raw)
        return order, by_file, srckeys
    finally:
        os.chdir(cwd)


def render_manifest(addon, order, by_file):
    cfg = addons.ADDONS[addon]
    header = lua.header_of(addons.manifest_path(addon), None)
    if header is None:
        raise SystemExit('%s: no existing manifest to take a header from' % addon)
    out = header + ['']
    for src in order:
        keys = by_file.get(src)
        if not keys:
            continue
        out.append(cfg['section'] % src)
        out.extend('L["%s"] = true' % k for k in keys)
        out.append('')
    out.extend(MANIFEST_FOOTER)
    eol = cfg['manifest_eol']
    return eol.join(out) + eol


def write_lua(path, header, rows, eol='\n'):
    lines = [header]
    for src_key, value in rows:
        lines.append('L["%s"] = "%s"' % (src_key, value))
    lines.append('')
    lines.append('return L')
    io.open(path, 'w', encoding='utf-8', newline='').write(eol.join(lines) + eol)


def sort_rows(table, srckeys):
    """Sorted by the English key, case-insensitively, so a diff stays readable."""
    out = []
    for k in sorted(table, key=lambda b: (b.decode('utf-8', 'replace').lower(), b)):
        out.append((srckeys[k], table[k]))
    return out


def main():
    apply = '--apply' in sys.argv
    live, srckeys, scanned = {}, {}, {}

    for addon in addons.ADDONS:
        order, by_file, keys = scan_source(addon)
        scanned[addon] = (order, by_file)
        live[addon] = set(keys)
        # first addon scanned wins the spelling; build.py re-spells per addon anyway
        for k, raw in keys.items():
            srckeys.setdefault(k, raw)
        text = render_manifest(addon, order, by_file)
        path = addons.manifest_path(addon)
        same = os.path.isfile(path) and lua.read(path) == text
        print('%-5s manifest: %d phrases across %d files  [%s]'
              % (addon, len(keys), len(by_file), 'unchanged' if same else 'CHANGED'))
        if apply and not same:
            io.open(path, 'w', encoding='utf-8', newline='').write(text)

    all_live = set()
    for addon in live:
        all_live |= live[addon]
    print('\nphrases in use: %d (union of %s)'
          % (len(all_live), ' + '.join(addons.ADDONS)))

    for code, name in addons.LANGUAGES:
        store, store_src, retired, retired_src = {}, {}, {}, {}
        sp, rp = addons.store_path(code), addons.retired_path(code)
        if os.path.isfile(sp):
            store, store_src, bad = lua.pairs_in(sp, warn=True)
            for n, text in bad:
                print('  ! store/%s.lua:%d unparsed, would be DROPPED: %s'
                      % (code, n, text))
        if os.path.isfile(rp):
            retired, retired_src, _ = lua.pairs_in(rp)

        imported, conflicts = 0, []
        for addon in addons.ADDONS:
            lp = addons.locale_path(addon, code)
            if not os.path.isfile(lp):
                continue
            got, got_src, _ = lua.pairs_in(lp)
            for k, v in got.items():
                if k not in store:
                    store[k] = v
                    store_src[k] = got_src[k]
                    imported += 1
                elif store[k] != v:
                    conflicts.append((addon, k, store[k], v))

        revived = 0
        for k in list(retired):
            if k in all_live and k not in store:
                store[k] = retired.pop(k)
                store_src[k] = retired_src.get(k, srckeys.get(k))
                revived += 1

        moved = 0
        for k in list(store):
            if k not in all_live:
                retired[k] = store.pop(k)
                retired_src[k] = store_src.get(k)
                moved += 1

        for k in list(store_src):
            if k in srckeys:
                store_src[k] = srckeys[k]

        covered = len([k for k in all_live if k in store])
        print('  %s: %d of %d in use (%d%%)  +%d imported  +%d revived  '
              '%d retired  (%d held back)'
              % (code, covered, len(all_live),
                 round(100.0 * covered / len(all_live)) if all_live else 0,
                 imported, revived, moved, len(retired)))
        for addon, k, a, b in conflicts:
            print('     ! conflict on %r' % k.decode('utf-8', 'replace')[:50])
            print('        store: %s' % a[:70])
            print('        %-5s: %s' % (addon, b[:70]))

        if apply:
            write_lua(sp, STORE_HEADER % {'code': code, 'lang': name},
                      sort_rows(store, store_src))
            write_lua(rp, RETIRED_HEADER % {'code': code, 'lang': name},
                      sort_rows(retired, retired_src))

    if apply:
        write_phrases(scanned)
    else:
        print('\nDRY RUN - re-run with --apply')
    return 0


def write_phrases(scanned):
    lines = [PHRASES_HEADER]
    for addon in addons.ADDONS:
        cfg = addons.ADDONS[addon]
        order, by_file = scanned[addon]
        lines.append('')
        lines.append('-- ' + '=' * 68)
        lines.append('-- %s (%s)' % (cfg['name'], addon))
        lines.append('-- ' + '=' * 68)
        for src in order:
            keys = by_file.get(src)
            if not keys:
                continue
            lines.append('')
            lines.append('-- %s: %s' % (addon, src))
            lines.extend('L["%s"] = true' % k for k in keys)
    lines.append('')
    lines.append('return L')
    path = os.path.join(addons.ROOT, 'store', '_phrases.lua')
    io.open(path, 'w', encoding='utf-8', newline='').write('\n'.join(lines) + '\n')
    print('\nwrote store/_phrases.lua')


if __name__ == '__main__':
    sys.exit(main())
