-- store/_phrases.lua
-- GENERATED by scan.py. Do not hand-edit.
--
-- Every English phrase the family currently uses, grouped by the addon and source
-- file it comes from, so a translator can see what a phrase is FOR before choosing
-- a word for it. A phrase used by more than one addon is listed under each.
--
-- This is the worklist. Translate into store/<language>.lua, never in here.

local L = {}


-- ====================================================================
-- Everything Quests (EQ)
-- ====================================================================

-- EQ: Options/TabGeneral.lua
L["General"] = true
L["Show quest pins on the world map"] = true
L["These are the round red markers Everything Quests puts on the big world map for quests you've already picked up (the ones in your quest log). A red \"!\" means \"go here for this quest's next step.\" A red \"?\" means \"this quest is done \226\128\148 go here to turn it in.\" Quests you haven't accepted yet keep the game's own yellow \"!\" markers; EQ does not change those. Uncheck this box and all of EQ's red markers go away."] = true
L["Auto-accept quests"] = true
L["Hold Alt to pause."] = true
L["Auto-turn-in quests"] = true
L["Skips reward-choice screens."] = true
L["Tracker"] = true
L["Open Tracker Settings"] = true
L["The tracker is now EQ Objective Tracker, a separate addon that Everything Quests installs for you. Its own options panel holds everything: position and size, fonts, colors, sections, filters, sorting and visibility. You can also open it by typing /eqot, or with the cogwheel at the top right of the tracker itself."] = true
L["Show Everything Quests icon on the tracker"] = true
L["Adds the Everything Quests logo at the top right of the tracker, which opens this options window. The tracker's own cogwheel opens the tracker's settings instead. You can also reach this window from the minimap button or by typing /eqs."] = true
L["Show Chain Guide icon on the tracker"] = true
L["Adds a small chain icon beside the cogwheel at the top right of the tracker, which opens the Chain Guide."] = true
L["Options Window Scale"] = true
L["Resizes this Everything Quests options window only. It does not change the quest tracker or anything shown in the game world. The new size applies when you let go of the slider."] = true
L["Popup window"] = true
L["Chat link"] = true
L["None"] = true
L["After an update"] = true
L["How Everything Quests tells you about new features: a Popup window, a quiet clickable Chat link in your chat frame, or None. New features always ship off until you turn them on."] = true
L["Nameplate Quest Icons"] = true
L["Quest icons on nameplates"] = true
L["Shows the \"!\" + count on objective mobs."] = true
L["Left"] = true
L["Right"] = true
L["Above"] = true
L["Below"] = true
L["Position"] = true
L["Where the quest icon + count sits relative to the enemy nameplate. Move it closer to the health bar to taste."] = true
L["Icon size"] = true
L["Count text size"] = true
L["X offset"] = true
L["Nudges the icon and count together left or right from the Position above, so you can slide them right up against the health bar."] = true
L["Y offset"] = true
L["Nudges the icon and count together up or down from the Position above (positive moves them up)."] = true
L["Reset all settings"] = true
L["Reset every Everything Quests setting to defaults?"] = true
L["Reset"] = true
L["Cancel"] = true
L["Profiles"] = true
L["Active profile"] = true
L["New Profile"] = true
L["Profile name:"] = true
L["Create"] = true
L["Overwrite profile?"] = true
L["A profile named \"%s\" already exists. Overwrite it with a copy of your current settings?"] = true
L["Overwrite"] = true
L["Switching profiles reloads the UI. Profiles are shared across characters; use them to keep different setups (e.g. raid vs solo). |cffEBB706New Profile|r prompts for a name and creates it on the spot."] = true
L["Slash commands"] = true
L["/eqs\n/everythingquests\n\n|cff999999Both open this options window.|r\n\n/eqs whatsnew\n\n|cff999999Show what's new in the latest update.|r\n\n/eqs session\n\n|cff999999Show a recap of your current play session.|r"] = true
L["Show minimap button"] = true

-- EQ: Options/TabWorldQuests.lua
L["Gold"] = true
L["Gear / Items"] = true
L["Reputation tokens"] = true
L["Resources / Currencies"] = true
L["Artifact Power"] = true
L["Profession quests"] = true
L["PvP"] = true
L["Pet battles"] = true
L["Other / Uncategorized"] = true
L["Classic"] = true
L["The Burning Crusade"] = true
L["Wrath of the Lich King"] = true
L["Cataclysm"] = true
L["Mists of Pandaria"] = true
L["Warlords of Draenor"] = true
L["Legion"] = true
L["Battle for Azeroth"] = true
L["Shadowlands"] = true
L["Dragonflight"] = true
L["The War Within"] = true
L["Midnight"] = true
L["Other"] = true
L["World Quests"] = true
L["Enable World Quests map features"] = true
L["Off: Everything Quests stops putting World Quests on the map — no world-map pins, no reward summary box, no zone quest list. The boxes below do nothing while this is off. This switch is ONLY for World Quests. It does NOT remove the red \"!\" / \"?\" quest rings — those are your normal quests, and you turn them off on the General tab. It also does NOT change the World Quests list in your tracker (that's on the Tracker tab)."] = true
L["Show world quest pins on the world map"] = true
L["Show zone quest list on zone maps"] = true
L["Filters by reward type"] = true
L["Enable All"] = true
L["Disable All"] = true
L["Filter by faction"] = true
L["Uncheck a faction to hide its world quests on the map."] = true
L["No major factions unlocked on this character yet."] = true
L["%s  |cffaaaaaa(Renown %d)|r"] = true
L["Faction %d"] = true
L["Display"] = true
L["Time left"] = true
L["Reward"] = true
L["Faction"] = true
L["A-Z"] = true
L["Sort zone quest list by"] = true
L["World map pin scale"] = true
L["Filters apply immediately when the world map is open."] = true

-- EQ: Options/TabChainGuide.lua
L["Chain Guide"] = true
L["Chain Guide (Storylines)"] = true
L["Open Chain Guide"] = true
L["Open Chain Guide on login"] = true
L["Show unrouted questlines"] = true
L["API discoveries not in our routing table."] = true
L["Show tracked chain on the world map"] = true
L["Pin the quests of the chain you're following on the world map, with your next step highlighted. Track a chain from the Track button in the Chain Guide."] = true
L["Window scale"] = true
L["Character cache"] = true
L["Per-character chain progress is cached account-wide so alts can browse what your other characters have completed. Clearing the cache removes that cross-character data; live completions stay (Blizzard tracks those)."] = true
L["Clear chain cache"] = true
L["Clear all cached chain-completion data across every character?"] = true
L["Clear"] = true
L["Cached: |cffffffff%d|r characters, |cffffffff%d|r waypoint locations\n|cffffffff%d|r chains across |cffffffff%d|r categories"] = true
L["today"] = true
L["1 day ago"] = true
L["%d days ago"] = true
L["\n|cffaaaaaaLast pruned: %s|r"] = true
L["Prune stale entries now"] = true
L["|cffEBB706EQ|r: pruned |cffffffff%d|r stale character record(s) and |cffffffff%d|r waypoint(s)."] = true

-- EQ: Options/TabHistory.lua
L["History"] = true
L["Quest History"] = true
L["Record completed quests"] = true
L["When on, Everything Quests writes an entry to your account-wide quest history every time you turn in a quest. The data is shared across all of your characters; the history window can filter by character."] = true
L["Maximum entries kept"] = true
L["When the history grows past this many entries, the oldest ones are dropped. Set higher if you want a longer record, lower to save disk space. 5000 entries is enough for several months of heavy questing."] = true
L["Open Quest History"] = true
L["Populate from past completions"] = true
L["this character"] = true
L["|cffEBB706EQ History:|r added %d past completion%s for |cffffffff%s|r (no dates)."] = true
L["One-time per character: walks the list of quests this character has completed (according to the game's own record) and adds any that aren't already in your history. Entries created this way have no date — the game doesn't tell us when they happened."] = true
L["Re-scan for quest names"] = true
L["|cffEBB706EQ History:|r requested %d quest name%s from the server. Names will fill in over the next minute or two."] = true
L["|cffEBB706EQ History:|r nothing left to look up — every entry that can be resolved already is."] = true
L["Some quests in the backfilled history show up as \"Quest #12345\" because Blizzard hasn't sent the client their name yet. This button asks the server for every missing one. Quests the server flatly has no data for (retired or internal IDs) will keep their numeric placeholder."] = true
L["Restore history from backup"] = true
L["|cffEBB706EQ History:|r no backup yet — one is saved automatically each time you log out."] = true
L["Restore quest history from the backup taken %s (%d entries)? This replaces the current history."] = true
L["Restore"] = true
L["|cffEBB706EQ History:|r restored %d entr%s from backup."] = true
L["Everything Quests saves a rolling backup of your history when you log out, and automatically restores it if your history is ever found empty or missing a character on load. Use this button to restore manually."] = true
L["Wipe history"] = true
L["Delete ALL recorded quest history (every character)? This cannot be undone."] = true
L["Wipe"] = true
L["|cffEBB706EQ History:|r wiped."] = true

-- EQ: Options/Frame.lua
L["Join our Discord!"] = true
L["Join our Discord"] = true
L["Version %s"] = true
L["Everything Quests opens its full options in a dedicated window. Click the button below, or type |cffEBB706/eqs|r in chat."] = true
L["Open Everything Quests Options"] = true
L["|cffEBB706Everything Quests|r: couldn't open Options \226\128\148 %s"] = true

-- EQ: Core/Init.lua
L["Everything Quests Discord"] = true
L["Join the community for help, feedback, and updates.\nCopy the invite below (it's pre-selected — just press Ctrl+C):"] = true
L["Close"] = true
L["Copy the link below (it's pre-selected — just press Ctrl+C):"] = true

-- EQ: Core/QuestRewards.lua
L["Equip — empty slot"] = true
L["Equipped: ilvl %d"] = true
L["+%d ilvl upgrade"] = true
L["%d ilvl lower"] = true
L["Same item level"] = true
L["ilvl %d"] = true
L["%d XP"] = true
L["Choose one:"] = true

-- EQ: Core/Util.lua
L["Expired"] = true

-- EQ: Modules/ChainGuide/CampaignSource.lua
L["Campaign Map"] = true

-- EQ: Modules/ChainGuide/ChainView.lua
L["Completed"] = true
L["Ready to turn in"] = true
L["In your quest log"] = true
L["Skipped"] = true
L["A later quest in this chain has already passed this one."] = true
L["May be worth going back to pick up."] = true
L["Not started"] = true
L["Level %d"] = true
L["Completed: "] = true
L["Completed (before tracking)"] = true
L["Shift-click to link in chat"] = true
L["Level %d–%d"] = true
L["Click to open this chain"] = true
L["Pick a chain on the left to view its quests."] = true
L["Untrack"] = true
L["Track"] = true
L["%d/%d done"] = true
L["%d active"] = true
L["|cffff9933%d skipped|r"] = true
L["Lv %d  •  ID %d"] = true
L["ON QUEST"] = true
L["NEXT"] = true
L["(optional)"] = true
L["Continue"] = true
L["Track this chain"] = true
L["Follow this chain — its quests pin on the world map (next step highlighted) and your waypoint auto-advances to the next step as you complete it. Works even with this window closed. Click again to stop."] = true
L["(no quests defined for this chain yet)"] = true

-- EQ: Modules/ChainGuide/Frame.lua
L["Hide the navigation panel"] = true
L["Collapse the category and chain list so the graph fills the whole window. Click again to bring it back."] = true
L["Back"] = true
L["Forward"] = true
L["Home"] = true
L["Options"] = true
L["Find quest"] = true
L["Type a quest name or its ID to jump to the chain that contains it."] = true
L["Go"] = true
L["Categories"] = true
L["Drag to resize"] = true
L["|cffEBB706EQ Chain Guide:|r found quest |cffffffff%d|r%s — jumping to its chain."] = true
L["|cffEBB706EQ Chain Guide:|r quest |cffffffff%d|r%s isn't in any chain I know about."] = true
L["|cffEBB706EQ Chain Guide:|r found |cffffffff%s|r — jumping to its chain."] = true
L["|cffEBB706EQ Chain Guide:|r no chain quest matches |cffffffff%s|r."] = true
L["Pick a category"] = true
L["Chains"] = true
L["%d / %d quests done"] = true

-- EQ: Modules/ChainGuide/MapPin.lua
L["Your next step"] = true
L["On this quest"] = true
L["Comes later in the chain"] = true

-- EQ: Modules/ChainGuide/QuestMapButton.lua
L["Chain"] = true
L["Find this quest in EQ's Chain Guide"] = true
L["Falls back to a Wowhead link in chat if EQ doesn't have a chain for this quest yet."] = true

-- EQ: Modules/History/Frame.lua
L["(before tracking)"] = true
L["|cffEBB706EQ History|r: |cffffffff%s|r isn't part of any chain in the Chain Guide."] = true
L["Right-click to open in the Chain Guide"] = true
L["Click to expand"] = true
L["Export"] = true
L["Re-scan names"] = true
L["Asks the server for the name of any \"Quest #12345\" entries. They'll fill in over the next minute or two as responses arrive."] = true
L["Quests"] = true
L["Streak"] = true
L["Chain Timeline"] = true
L["Activity"] = true
L["Stats"] = true
L["This Session"] = true
L["Character:"] = true
L["All characters"] = true
L["Date:"] = true
L["All time"] = true
L["Today"] = true
L["Past 7 days"] = true
L["Past 30 days"] = true
L["Type:"] = true
L["All types"] = true
L["Campaign"] = true
L["Questline"] = true
L["Calling"] = true
L["Recurring"] = true
L["World Quest"] = true
L["Sort:"] = true
L["Date"] = true
L["Name"] = true
L["Type"] = true
L["Sort direction"] = true
L["Click to flip ascending / descending."] = true
L["Hide undated  |cffaaaaaa(backfilled)|r"] = true
L["(no matching quests)"] = true
L["%d entries"] = true
L["first"] = true
L["oldest"] = true
L["newest"] = true
L["%d entries (showing %s %d)"] = true
L["Current daily streak"] = true
L["Best daily streak"] = true
L["Total quests recorded with a date"] = true
L["Streak counts consecutive days (local time) with at least one quest turn-in across any character on the account. Today or yesterday keeps the streak alive - you don't lose it until a whole day passes with no activity."] = true
L["%d days"] = true
L["Chains where you have at least one completed quest. Click a chain to expand and see per-quest completion dates."] = true
L["(no chain quests recorded yet)"] = true
L["%d of %d quests recorded"] = true
L["Quest turn-ins per day over the last %d days. Brighter = busier. Hover a cell for the date and count. The bottom-right cell is today."] = true
L["%d quest%s turned in"] = true
L["Less"] = true
L["More"] = true
L["total turn-ins in the last %d days"] = true
L["Busiest day: %s (%d quests)"] = true
L["%dg %ds %dc"] = true
L["Totals"] = true
L["Trends"] = true
L["Account-wide quest rewards. Totals count only quests turned in while reward tracking was on; older entries didn't capture XP or gold."] = true
L["Total quests with reward data"] = true
L["Total gold earned"] = true
L["Total XP earned"] = true
L["By character"] = true
L["Top single-quest rewards"] = true
L["%s  \194\183  %s quests  \194\183  %s  \194\183  %s XP"] = true
L["Biggest gold:  |cffffffff%s|r  \194\183  %s"] = true
L["Biggest gold:  (none yet)"] = true
L["Biggest XP:    |cffffffff%s|r  \194\183  %s XP"] = true
L["Biggest XP:    (none yet)"] = true
L["Daily"] = true
L["Weekly"] = true
L["Show:"] = true
L["XP"] = true
L["Gold is all income (loot, vendor, rewards) tracked forward from when this version was installed \226\128\148 past periods may read 0. XP and quest counts come from quest turn-ins."] = true
L["This week"] = true
L["last week"] = true
L["yesterday"] = true
L["%s \226\128\148 %s"] = true
L["%s vs %s"] = true
L["Your quest activity this play session. A session starts when you log in and continues across /reload; it resets the next time you log in fresh."] = true
L["Played this session"] = true
L["Quests completed"] = true
L["Quest XP earned"] = true
L["Quest gold earned"] = true
L["Level-ups"] = true
L["   |cffaaaaaa(%.1f / hour)|r"] = true
L["%d   |cffaaaaaa(%d to %d)|r"] = true
L["Press Ctrl+A to select all, then Ctrl+C to copy."] = true

-- EQ: Modules/History/Recorder.lua
L["first time seeing |cffffffff%s|r - added %d past completion%s (no dates; future turn-ins are dated)."] = true
L["Quest history loaded empty; restored a backup from %s (%d entries)."] = true
L["Quest history for %s was missing; restored a backup from %s (%d entries)."] = true

-- EQ: Modules/TrackerBridge.lua
L["EQ Objective Tracker is not loaded, so the tracker is unavailable."] = true
L["Open the Chain Guide"] = true
L["Open the Everything Quests options"] = true
L["Get Directions"] = true

-- EQ: Modules/WhatsNew.lua
L["See what's new"] = true
L["updated to"] = true
L["Open Options"] = true
L["Got it"] = true
L["Don't show these again"] = true
L["Stops What's New notices entirely. You can turn them back on in /eqs > General."] = true

-- EQ: Modules/WorldQuests/Pin.lua
L["World Quest #"] = true
L["Untrack Quest"] = true
L["Track Quest"] = true
L["Super-track (follow arrow)"] = true
L["Search on Wowhead"] = true

-- EQ: Modules/WorldQuests/Summary.lua
L["Gear"] = true
L["Reputation"] = true
L["Resources"] = true
L["Professions"] = true
L["Pet Battles"] = true

-- EQ: Modules/WorldQuests/Tab.lua
L["Click to hide the World Quests list."] = true
L["Click to show the World Quests list."] = true

-- EQ: Modules/WorldQuests/Tooltip.lua
L["Time Left: "] = true

-- EQ: Modules/WorldQuests/ZoneMap.lua
L["%s — %d quests"] = true

-- EQ: Options/TabAbout.lua
L["Open or close the options window"] = true
L["Open the Quest History window"] = true
L["Recap your current play session in chat"] = true
L["List the current zone's quest chains in chat"] = true
L["Show the What's New popup again"] = true
L["Open this About tab"] = true
L["About"] = true
L["by Wheelbarrel00"] = true
L["for WoW Midnight (12.0.x)"] = true
L["A unified replacement for the Blizzard quest experience: a custom tracker, world-map overlays, quest history, and a Midnight chain guide."] = true
L["CurseForge"] = true
L["GitHub"] = true
L["Report a Bug"] = true
L["What's New"] = true
L["Commands"] = true
L["Tip: right-click the minimap button to open Options."] = true
L["Tutorials"] = true
L["Video tutorials are coming soon."] = true
L["More Add-ons by Wheelbarrel00"] = true
L["Thanks"] = true
L["Built with feedback, reports, and ideas from the community — especially "] = true
L[". Thank you!"] = true
L["Special thanks to "] = true
L[" for the many features, fixes, and reports that keep shaping Everything Quests."] = true
L[" for the many hours spent translating Everything Quests into French."] = true
L[" for the many hours spent translating Everything Quests into Russian."] = true
L[" for the many hours spent translating Everything Quests into Korean."] = true
L["Changelog"] = true
L["Older versions are on CurseForge"] = true

-- ====================================================================
-- EQ Objective Tracker (EQOT)
-- ====================================================================

-- EQOT: Options/TabGeneral.lua
L["General"] = true
L["Lock tracker"] = true
L["Disable drag-to-move and resize."] = true
L["Hide tracker in combat"] = true
L["Hides the tracker while you are in combat and brings it back when you leave."] = true
L["Hide tracker in instances"] = true
L["Raids, dungeons, delves."] = true
L["Hide tracker when world map is open"] = true
L["Hides the tracker while the world map is up, so it does not sit over the map."] = true
L["Hide tracker in Mythic+"] = true
L["Hides the tracker during an active Mythic+ run, then brings it back when the run ends."] = true
L["Auto-track accepted quests"] = true
L["Matches Blizzard's default."] = true
L["Keep focused quest after relog"] = true
L["Restores the waypoint arrow."] = true
L["Options Window Scale"] = true
L["Resizes this EQ Objective Tracker options window only. It does not change the quest tracker or anything shown in the game world. The new size applies when you let go of the slider."] = true
L["Reset position and size"] = true
L["Returns the tracker to its default position and size."] = true
L["Reset all settings"] = true
L["Reset every EQ Objective Tracker setting to defaults? The interface will reload."] = true
L["Reset"] = true
L["Cancel"] = true
L["Restores every setting on every tab to its default and reloads the interface. This also clears the Options Window Scale, which every character shares, and this character's collapsed sections and individually hidden entries."] = true
L["Profiles"] = true
L["Switching profiles reloads the UI. Profiles are shared across characters. Use them to keep different setups such as raid and solo. |cffEBB706New Profile|r prompts for a name and creates it on the spot."] = true
L["Active profile"] = true
L["Switches to another saved settings profile. The interface reloads immediately when you pick one."] = true
L["New Profile"] = true
L["Profile name:"] = true
L["Create"] = true
L["Overwrite profile?"] = true
L["A profile named \"%s\" already exists. Overwrite it with a copy of your current settings?"] = true
L["Overwrite"] = true
L["Prompts for a name, then creates a profile holding a copy of your current settings and switches to it. The interface reloads."] = true

-- EQOT: Options/TabTracker.lua
L["Zone"] = true
L["Groups entries under the heading they sit under in your quest log."] = true
L["Title"] = true
L["Alphabetical by name."] = true
L["Status"] = true
L["Puts everything that is ready to turn in at the top."] = true
L["Type"] = true
L["Weekly first, then daily, then everything else. Only quests carry a type, so other sections fall back to alphabetical."] = true
L["Level"] = true
L["Lowest quest level first."] = true
L["Distance"] = true
L["Nearest objective first, updated as you move. A quest ready to turn in measures to its turn-in point."] = true
L["Recent"] = true
L["Most recently accepted first."] = true
L["Manual"] = true
L["Your own order. Drag quests up and down in the tracker to set it."] = true
L["Campaign section"] = true
L["Quests section"] = true
L["Profession section"] = true
L["Endeavors section"] = true
L["Achievements section"] = true
L["World Quests section"] = true
L["Top"] = true
L["Bottom"] = true
L["Move %s up"] = true
L["Move %s down"] = true
L["Reorders where this section sits in the tracker. A section only shows while it has something in it, so empty sections won't visibly move."] = true
L["Tracker"] = true
L["On-Screen Tracker"] = true
L["Changes apply immediately to the on-screen tracker."] = true
L["Show only tracked quests"] = true
L["Hides quests that are in your log but not tracked. Matches Blizzard's default tracker."] = true
L["Simplify Mode"] = true
L["Show only the first incomplete objective per quest."] = true
L["Simplify tracked achievements"] = true
L["Show only incomplete criteria for tracked achievements."] = true
L["Sort Order"] = true
L["Drag and drop the quests in the tracker to reorder them however you like."] = true
L["Filters"] = true
L["Show or hide this category of entry in the tracker."] = true
L["Show only quests in current zone"] = true
L["Only show entries with an objective on your current map. Entries whose provider cannot tell are always shown."] = true
L["Reset filters to defaults"] = true
L["Turns all six category filters back on and clears the current-zone filter. Nothing else on this tab is changed."] = true
L["Tracker Visibility"] = true
L["Uncheck to hide this section from the tracker even while it has entries."] = true
L["Auto-list current-zone world quests"] = true
L["Lists every WQ in your zone without tracking each."] = true
L["Set a custom World Quests height"] = true
L["By default the World Quests area shares space with your quest list and gets squeezed when you have a lot of quests. Turn this on to give it its own height, set by the slider below."] = true
L["World Quests Height"] = true
L["Height in pixels for the world quest area. Only used while Set a custom World Quests height is on."] = true
L["Maximum Height (% of tracker)"] = true
L["The most of the tracker the world quest area may take. Quest sections are given their space first, so this is a ceiling rather than a reservation. Only used while Set a custom World Quests height is off."] = true
L["Section Order"] = true
L["Rearrange the tracker's sections with the arrows below. A section only appears on the tracker while it has something in it, so reordering an empty section won't look like anything changed. World Quests scroll in their own panel and can only sit at the very top or bottom, so use the Top/Bottom control."] = true
L["World Quests Position"] = true
L["Where the World Quests panel sits on the tracker. |cffffffffTop|r puts it above your quests. |cffffffffBottom|r keeps it below your quests, which is the default. World Quests scroll in their own capped panel, which is why they can't be mixed in between the other sections."] = true
L["Options"] = true
L["Quest Title Color By Difficulty"] = true
L["Colors each quest title by how hard it is for your level, the way the quest log does. The Quest Title Color Override on the Appearance tab wins over this while it is set."] = true
L["Show quest level prefix"] = true
L["For example, [60] Title."] = true
L["Show zone label under quest titles"] = true
L["Adds the quest log heading each quest came from as a small line under its title."] = true
L["Show objective progress numbers"] = true
L["For example, 0/4, 1/1, etc."] = true
L["Show quest ID"] = true
L["Useful for bug reports."] = true
L["Show the visible / total count on section headers"] = true
L["For example, 3/9. Applies to every section header."] = true
L["Show usable quest item buttons"] = true
L["Puts a button on the tracker row of any quest that carries a usable item, so you can use it without opening your bags."] = true
L["Show Options icon on the tracker"] = true
L["A small cogwheel at the top-right of the tracker that opens the options panel."] = true
L["Show Quest Discovered popups"] = true
L["Boxes for newly discovered / completed quests."] = true
L["Show NEW tag on recently accepted quests"] = true
L["For about an hour after accepting."] = true
L["Split quest click"] = true
L["Click the icon to focus, click the title to open the quest log."] = true
L["Quest Sound"] = true
L["Plays when a quest is ready to turn in."] = true
L["Quest Complete Sound"] = true
L["Which sound plays when a quest becomes ready to turn in."] = true
L["Scenario Bonus Objectives"] = true
L["Show bonus objectives HUD"] = true
L["Shows a small movable checklist of the extra bonus objectives that appear during some scenarios and delves, so you do not miss their rewards. Drag to move, right-click to lock or reset. Off by default."] = true
L["Test"] = true
L["Draws the HUD with two made-up bonus objectives so you can position and size it without being in a scenario or delve. Click again to clear it."] = true
L["HUD Scale"] = true
L["Sizes the bonus objectives HUD."] = true

-- EQOT: Options/TabAppearance.lua
L["None"] = true
L["Outline"] = true
L["Thick"] = true
L["Mono"] = true
L["Mono Outline"] = true
L["Mono Thick"] = true
L["Plain"] = true
L["Card"] = true
L["Header Bar 1"] = true
L["Header Bar 2"] = true
L["Left"] = true
L["Center"] = true
L["Right"] = true
L["Same as tracker font"] = true
L["Appearance"] = true
L["Font"] = true
L["Fonts registered through LibSharedMedia, so anything from ElvUI or SharedMedia appears here too."] = true
L["Font Size"] = true
L["Base size for objective text. Titles and headers offset from this."] = true
L["Title Size Offset"] = true
L["Sizes quest and achievement titles separately from the objective text. This value is added to the Font Size above: 0 keeps titles the same size as the base font, positive makes them larger, negative smaller."] = true
L["Header Size Offset"] = true
L["Sizes the section headers (Quests, Campaign, and so on) independently of the quest text. Added on top of the Font Size above: the default 4 keeps headers at their current size, lower shrinks them (handy on a low UI scale), higher enlarges them."] = true
L["Font Outline"] = true
L["Outlines keep small text legible over bright terrain."] = true
L["Text Shadow"] = true
L["Draws a soft drop-shadow behind all tracker text so it stays readable over bright or busy backgrounds. Use Shadow Color to tint it and Shadow Size to set how far it's cast."] = true
L["Shadow Color"] = true
L["Shadow color and opacity."] = true
L["Shadow Size"] = true
L["How far the text drop-shadow is cast behind the letters. Higher values give a larger, more pronounced shadow. Lower values keep it tight. Only applies while Text Shadow is on."] = true
L["Scenario"] = true
L["Draws a drop-shadow behind the scenario / delve banner text (the Stage and name lines). This is SEPARATE from the Text Shadow above, which affects only the quest and objective text. The banner is styled on its own."] = true
L["Color and opacity of the banner's drop shadow."] = true
L["How far the scenario banner's drop-shadow is cast. Higher values give a larger, more pronounced shadow. Lower values keep it tight. Only applies while the Scenario Text Shadow above is on."] = true
L["Banner Alignment"] = true
L["Positions the scenario / delve banner within the tracker. Left lines it up with the quest text, Center keeps it centered (the default), and Right pushes it to the tracker's right edge."] = true
L["Banner Text Size"] = true
L["Grows or shrinks the scenario / delve banner's Stage and name text. 0 is the default size. The banner artwork is a fixed size, so large values may overflow it."] = true
L["Criteria Text Size"] = true
L["Sizes the scenario / delve objective (criteria) lines shown under the banner, separately from the Banner Text Size above. Raise it if the criteria text looks small next to your quest and World Quest text."] = true
L["Scroll Bar"] = true
L["Hide scroll bar"] = true
L["Removes the tracker's scroll bar entirely and scrolls with the mouse wheel instead. Everything else in this group styles that bar, so it all stops applying while this is on."] = true
L["Scroll Bar Background"] = true
L["Draws a track behind the scroll bar so it stays visible over bright terrain."] = true
L["Scroll Bar Color"] = true
L["Color and opacity of the scroll bar track."] = true
L["Solid color thumb"] = true
L["Replaces the tracker scroll bar's textured thumb (the draggable block) with a flat single-color block. Use the Thumb Color and Thumb Width controls to style it. Off restores the stock Blizzard bar."] = true
L["Thumb Color"] = true
L["Color and opacity of the draggable block. Only used while Solid color thumb is on."] = true
L["Thumb Width"] = true
L["How wide the draggable block is. Only used while Solid color thumb is on."] = true
L["Hide scroll bar arrows"] = true
L["Hides the up and down arrow buttons at the ends of the tracker scroll bar. The bar still scrolls by dragging the thumb or using the mouse wheel."] = true
L["Background"] = true
L["Fills the tracker behind the text. Useful over bright terrain."] = true
L["Background Color"] = true
L["Background color and opacity."] = true
L["Border"] = true
L["Draws a border around the tracker."] = true
L["Border Color"] = true
L["Border color and opacity."] = true
L["Border Thickness"] = true
L["Border thickness in pixels."] = true
L["Header Bar"] = true
L["Show header bars"] = true
L["Draws a colored gradient bar behind each section header (Quests, Campaign, World Quests, and so on), for a look closer to the default Blizzard tracker. Off by default."] = true
L["Bar Color"] = true
L["Brightest end of the bar gradient. The other end is the same color darkened."] = true
L["Bar Style"] = true
L["Header Bar 1 is a horizontal gradient (bright on the left, dark on the right). Header Bar 2 is a vertical gradient (bright at the top, dark at the bottom). Bar Color, Bar Height, and Soft edges all apply to whichever style you pick."] = true
L["Soft edges"] = true
L["Feathers the top, left, and right edges of the header bar so it blends into the UI instead of sitting in a hard box. The gradient color is unchanged. Only applies while Header bars is on. Off by default."] = true
L["Bar Height"] = true
L["How tall the section-header bar is. The bar is centered on the header row, so larger values fill more of it."] = true
L["Edge Softness"] = true
L["How soft the header bar's feathered edges are when Soft edges is on. Higher is softer, lower tightens toward a hard edge."] = true
L["Colors & Dimensions"] = true
L["Reset to Defaults"] = true
L["Reset every setting on this tab to its defaults? The interface will reload."] = true
L["Restores every control on this tab, including the zone bar block, to its default. Other tabs are left alone."] = true
L["Quest Title Color Override"] = true
L["When cleared, falls back to difficulty coloring or default yellow."] = true
L["Use class color for titles"] = true
L["Colors quest, achievement, and endeavor titles with the class color of the character you are currently logged in on. Overrides the color above while it is on. Off by default."] = true
L["Use title color for completed quests"] = true
L["Instead of green."] = true
L["Section Header Color"] = true
L["Color of the Quests, Campaign and World Quests headings."] = true
L["Use class color for headers"] = true
L["Colors the section headers (Quests, Campaign, and so on) with the class color of the character you are currently logged in on. Overrides the color above while it is on. Off by default."] = true
L["Divider Line Color"] = true
L["Sets the color of the thin line under each section header. Defaults to the original gold."] = true
L["Tracker Scale"] = true
L["Scales the whole tracker. Takes effect immediately out of combat."] = true
L["Block Spacing"] = true
L["Vertical gap between each entry and between sections."] = true
L["Line Spacing"] = true
L["Adds vertical space between a quest's objective lines, across the whole tracker. 0 keeps the default spacing."] = true
L["Header Spacing"] = true
L["Adds or removes space around section headers and beneath each quest's title. 0 keeps the default spacing."] = true
L["Quest Rows"] = true
L["Row Layout"] = true
L["How each quest is drawn in the tracker. |cffffffffPlain|r is the default look - text straight on the tracker background. |cffffffffCard|r gives every quest its own panel with a background and border, which makes long lists easier to read apart."] = true
L["Fill color behind each quest card. Only used while Row Layout is set to Card."] = true
L["Outline color around each quest card. Only used while Row Layout is set to Card."] = true
L["How thick the card outline is, in pixels. 0 hides the outline and leaves just the fill."] = true
L["Card Padding"] = true
L["Breathing room between a card's edge and the text inside it. Larger values make taller cards."] = true
L["Tint cards by quest type"] = true
L["Gives campaign, legendary, dungeon and raid entries their own card color. Anything else uses the plain background color above."] = true
L["Campaign"] = true
L["Card color for campaign entries. Needs Tint cards by quest type switched on."] = true
L["Legendary"] = true
L["Card color for legendary entries. Needs Tint cards by quest type switched on."] = true
L["Dungeon"] = true
L["Card color for dungeon entries. Needs Tint cards by quest type switched on."] = true
L["Raid"] = true
L["Card color for raid entries. Needs Tint cards by quest type switched on."] = true
L["Zone Progress Bar"] = true
L["Show zone progress bar"] = true
L["Approximate questline progress."] = true
L["Float as a movable bar"] = true
L["Drag to move, right-click to lock or reset. Unticked, the bar becomes an ordinary tracker section instead and only Bar Texture and Bar Color still apply to it."] = true
L["Fills the floating bar behind its text."] = true
L["Background color and opacity for the floating bar. While this is unset the bar uses a plain black fill that fades slightly once locked."] = true
L["Draws a border around the floating bar."] = true
L["Border color and opacity for the floating bar."] = true
L["Zone Bar Scale"] = true
L["Size of the floating bar. The docked section follows the tracker's own scale instead."] = true
L["Font for the floating bar's zone name, count and percentage. The docked section uses the tracker font."] = true
L["Bar Texture"] = true
L["Sets the fill texture of the zone progress bar. Textures added by other media addons (such as SharedMedia, ElvUI, or Details) appear here too."] = true
L["Fill color and opacity of the bar itself."] = true
L["Header Color"] = true
L["Color of the zone name on the floating bar. The docked section uses the section header color."] = true
L["Count Color"] = true
L["Color of the completed-of-total count on the floating bar."] = true

-- EQOT: Options/TabAbout.lua
L["Open this window"] = true
L["Lock moving and resizing"] = true
L["Unlock moving and resizing"] = true
L["Restore the default position and size"] = true
L["Show or hide the tracker"] = true
L["Bring back every entry you have hidden"] = true
L["Import your Everything Quests settings"] = true
L["Print provider status to chat"] = true
L["Toggle entry validation warnings"] = true
L["Special thanks to %s for the many features, fixes, and reports that keep shaping EQ Objective Tracker."] = true
L["Special thanks to %s for the many hours spent translating EQ Objective Tracker into French."] = true
L["Special thanks to %s for the many hours spent translating EQ Objective Tracker into Russian."] = true
L["Special thanks to %s for the many hours spent translating EQ Objective Tracker into Korean."] = true
L["About"] = true
L["Version %s"] = true
L["by Wheelbarrel00"] = true
L["A standalone replacement for the default objective tracker. It does not require Everything Quests, and never will."] = true
L["Join our Discord"] = true
L["CurseForge"] = true
L["GitHub"] = true
L["Report a Bug"] = true
L["Commands"] = true
L["Content providers"] = true
L["Providers are gated at load time by which TOC file your game flavor used. A provider that is not listed was never loaded."] = true
L["Thanks"] = true
L["Changelog"] = true
L["Older versions are on CurseForge"] = true

-- EQOT: Options/Frame.lua
L["Plays the currently selected sound."] = true
L["Clear"] = true
L["Join our Discord!"] = true
L["Click to copy the invite link."] = true

-- EQOT: Core/Init.lua
L["Copy the link below (it's pre-selected \226\128\148 just press Ctrl+C):"] = true
L["Close"] = true
L["Join the community for help, feedback, and updates.\nCopy the invite below (it's pre-selected \226\128\148 just press Ctrl+C):"] = true

-- EQOT: Core/Migrate.lua
L["imported %d settings from Everything Quests."] = true

-- EQOT: Data/Filter.lua
L["World Quests"] = true
L["Bonus Objectives"] = true
L["Campaign quests"] = true
L["Daily quests"] = true
L["Weekly quests"] = true
L["Normal quests"] = true

-- EQOT: Data/Providers/Achievements.lua
L["Left-click to open, right-click to untrack."] = true

-- EQOT: Data/Providers/Professions.lua
L["%s (Recraft)"] = true
L["Left-click to open the recipe, right-click to untrack."] = true

-- EQOT: Data/Providers/Scenarios.lua
L["Ritual Site"] = true
L["Delves"] = true
L["Mythic+"] = true
L["Warfront"] = true
L["Proving Grounds"] = true
L["Follower Dungeon"] = true
L["Void Incursion"] = true
L["Battleground"] = true
L["Arena"] = true
L["Stage %d of %d"] = true

-- EQOT: Data/Providers/WorldQuests.lua
L["Ready to turn in"] = true

-- EQOT: Data/ScenarioBonus.lua
L["Delve Bonus Loot"] = true
L["Nemesis Strongbox: %d/%d packs"] = true
L["Sanctified Banner: Grand Spoils earned"] = true
L["Sanctified Banner: bonus Spoils secured"] = true
L["Sanctified Banner: kill the Voidfused Rager"] = true
L["Sanctified Banner: find it for bonus loot"] = true

-- EQOT: UI/AutoQuestPopup.lua
L["Click to view quest"] = true
L["Quest Complete!"] = true
L["Quest Discovered!"] = true

-- EQOT: UI/Commands.lua
L["tracker locked."] = true
L["tracker unlocked."] = true
L["position and size reset."] = true
L["nothing is hidden."] = true
L["%d hidden entries restored."] = true
L["no Everything Quests configuration found to import."] = true
L["Import from Everything Quests"] = true
L["Reset this profile to defaults and replace it with your Everything Quests tracker settings?\n\nThis cannot be undone. Make a new profile first if you want to keep the current one."] = true
L["Import"] = true
L["commands:"] = true

-- EQOT: UI/Dialog.lua
L["OK"] = true

-- EQOT: UI/RewardTooltip.lua
L["Equip \226\128\148 empty slot"] = true
L["Equipped: ilvl %d"] = true
L["+%d ilvl upgrade"] = true
L["%d ilvl lower"] = true
L["Same item level"] = true
L["ilvl %d"] = true
L["%d XP"] = true
L["Choose one:"] = true
L["Time Left: "] = true

-- EQOT: UI/Row.lua
L["Find Group"] = true
L["Open the Premade Group Finder for this quest."] = true

-- EQOT: UI/RowMenu.lua
L["Pin to tracker"] = true
L["Unpin from tracker"] = true
L["Track Quest"] = true
L["Untrack Quest"] = true
L["Focus"] = true
L["Unfocus"] = true
L["Super-track (follow arrow)"] = true
L["Open in Map & Quest Log"] = true
L["Pop Out Quest Details"] = true
L["Search on Wowhead"] = true
L["Abandon Quest"] = true

-- EQOT: UI/Scenario.lua
L["Final Stage"] = true
L["Stage %d"] = true

-- EQOT: UI/ScenarioBonusHUD.lua
L["Unlock (allow moving)"] = true
L["Lock position"] = true
L["Reset position"] = true

-- EQOT: UI/Sections.lua
L["Zone Progress"] = true
L["Quests"] = true
L["Achievements"] = true
L["Endeavors"] = true
L["Profession"] = true

-- EQOT: UI/Tracker.lua
L["Tracker locked"] = true
L["Use /eqot unlock to move it."] = true
L["Drag to move, corner grip to resize."] = true
L["/eqot for options"] = true
L["Open the options panel"] = true
L["a visibility rule is keeping the tracker hidden - see /eqot, General."] = true

return L
