-- store/koKR.lua
-- Korean (koKR) translations for the Everything Quests addon family.
--
-- HOW TO USE: type the Korean translation between the quotes after each "=".
-- The English text is the key inside L["..."]. Example:
--     L["Hide tracker in combat"] = "..."
--
-- This is the single source of Korean for EVERY addon in the family. Which addon
-- a phrase belongs to is decided when the locale files are built, so a phrase that
-- moves from one addon to another keeps its translation with no work from anyone.
--
-- Mirrors store/_phrases.lua line for line (same groups, same order, duplicates
-- included), so the two files can be read side by side. Regenerate against a new
-- _phrases.lua by replacing each `= true` with the translation for that key.
--
-- KEEP THESE EXACTLY AS THEY APPEAR (do not translate them):
--   |cffaaaaaa ... |r   -> color codes
--   %d  %s              -> numbers / names get inserted here
--   %1$s  %2$d          -> the same, when the order has to change in Korean
--   \n                  -> line break
--   \"                  -> an escaped quote inside the text
--
-- A phrase left out of this file simply renders in English, so a partial
-- translation is always safe.
local L = {}


-- ====================================================================
-- Everything Quests (EQ)
-- ====================================================================

-- EQ: Options/TabGeneral.lua
L["General"] = "일반"
L["Show quest pins on the world map"] = "세계 지도에 퀘스트 핀 표시"
L["These are the round red markers Everything Quests puts on the big world map for quests you've already picked up (the ones in your quest log). A red \"!\" means \"go here for this quest's next step.\" A red \"?\" means \"this quest is done \226\128\148 go here to turn it in.\" Quests you haven't accepted yet keep the game's own yellow \"!\" markers; EQ does not change those. Uncheck this box and all of EQ's red markers go away."] = "이미 수락한(퀘스트 일지에 있는) 퀘스트에 대해 Everything Quests가 큰 지도에 찍는 둥근 빨간 표시입니다. 빨간 \"!\"는 \"이 퀘스트의 다음 단계로 가라\", 빨간 \"?\"는 \"이 퀘스트는 완료됨 - 여기서 완료하라\"는 뜻입니다. 아직 수락 안 한 퀘스트는 게임 기본 노란 \"!\" 표시를 그대로 둡니다(EQ는 그것을 바꾸지 않음). 이 설정을 끄면 EQ의 빨간 표시가 모두 사라집니다."
L["Auto-accept quests"] = "퀘스트 자동 수락"
L["Hold Alt to pause."] = "Alt 누르면 일시정지."
L["Auto-turn-in quests"] = "퀘스트 자동 완료"
L["Skips reward-choice screens."] = "보상 선택 화면을 건너뜁니다."
L["Tracker"] = "추적기"
L["Open Tracker Settings"] = "추적기 설정 열기"
L["The tracker is now EQ Objective Tracker, a separate addon that Everything Quests installs for you. Its own options panel holds everything: position and size, fonts, colors, sections, filters, sorting and visibility. You can also open it by typing /eqot, or with the cogwheel at the top right of the tracker itself."] = "추적기는 이제 Everything Quests가 함께 설치해 주는 별도 애드온인 EQ Objective Tracker입니다. 위치와 크기, 글꼴, 색상, 섹션, 필터, 정렬, 표시 여부까지 모든 설정이 그쪽 설정창에 있습니다. /eqot 를 입력하거나 추적기 우측 상단의 톱니바퀴로도 열 수 있습니다."
L["Show Everything Quests icon on the tracker"] = "추적기에 Everything Quests 아이콘 표시"
L["Adds the Everything Quests logo at the top right of the tracker, which opens this options window. The tracker's own cogwheel opens the tracker's settings instead. You can also reach this window from the minimap button or by typing /eqs."] = "추적기 우측 상단에 Everything Quests 로고를 추가합니다. 누르면 이 설정창이 열립니다. 추적기의 톱니바퀴는 추적기 자체 설정을 엽니다. 미니맵 버튼이나 /eqs 입력으로도 이 창을 열 수 있습니다."
L["Show Chain Guide icon on the tracker"] = "추적기에 연계 가이드 아이콘 표시"
L["Adds a small chain icon beside the cogwheel at the top right of the tracker, which opens the Chain Guide."] = "추적기 우측 상단 톱니바퀴 옆에 작은 사슬 아이콘을 추가합니다. 누르면 연계 가이드가 열립니다."
L["Options Window Scale"] = "설정 창 배율"
L["Resizes this Everything Quests options window only. It does not change the quest tracker or anything shown in the game world. The new size applies when you let go of the slider."] = "이 Everything Quests 설정 창의 크기만 조절합니다. 퀘스트 추적기나 게임 화면에 표시되는 것은 바뀌지 않습니다. 슬라이더에서 손을 떼면 새 크기가 적용됩니다."
L["Popup window"] = "팝업 창"
L["Chat link"] = "채팅 링크"
L["None"] = "없음"
L["After an update"] = "업데이트 후"
L["How Everything Quests tells you about new features: a Popup window, a quiet clickable Chat link in your chat frame, or None. New features always ship off until you turn them on."] = "Everything Quests가 새 기능을 알리는 방식입니다: 팝업 창, 채팅창에 조용히 표시되는 클릭 가능한 채팅 링크, 또는 없음. 새 기능은 켜기 전까지 항상 꺼진 상태로 배포됩니다."
L["Nameplate Quest Icons"] = "이름표 퀘스트 아이콘"
L["Quest icons on nameplates"] = "이름표에 퀘스트 아이콘"
L["Shows the \"!\" + count on objective mobs."] = "목표 몹에 \"!\" + 개수를 표시합니다."
L["Left"] = "왼쪽"
L["Right"] = "오른쪽"
L["Above"] = "위쪽"
L["Below"] = "아래쪽"
L["Position"] = "위치"
L["Where the quest icon + count sits relative to the enemy nameplate. Move it closer to the health bar to taste."] = "퀘스트 아이콘과 처치 수가 적 이름표를 기준으로 표시되는 위치입니다. 취향에 따라 생명력 막대에 더 가깝게 옮기세요."
L["Icon size"] = "아이콘 크기"
L["Count text size"] = "처치 수 글자 크기"
L["X offset"] = "가로 위치 조정"
L["Nudges the icon and count together left or right from the Position above, so you can slide them right up against the health bar."] = "위의 위치를 기준으로 아이콘과 처치 수를 좌우로 함께 밀어 생명력 막대에 바짝 붙일 수 있습니다."
L["Y offset"] = "세로 위치 조정"
L["Nudges the icon and count together up or down from the Position above (positive moves them up)."] = "위의 위치를 기준으로 아이콘과 처치 수를 위아래로 함께 밉니다 (양수면 위로 이동)."
L["Reset all settings"] = "모든 설정 초기화"
L["Reset every Everything Quests setting to defaults?"] = "모든 Everything Quests 설정을 기본값으로 초기화할까요?"
L["Reset"] = "초기화"
L["Cancel"] = "취소"
L["Profiles"] = "프로필"
L["Active profile"] = "활성 프로필"
L["New Profile"] = "새 프로필"
L["Profile name:"] = "프로필 이름:"
L["Create"] = "만들기"
L["Overwrite profile?"] = "프로필 덮어쓸까요?"
L["A profile named \"%s\" already exists. Overwrite it with a copy of your current settings?"] = "\"%s\" 프로필이 이미 있습니다. 현재 설정의 사본으로 덮어쓸까요?"
L["Overwrite"] = "덮어쓰기"
L["Switching profiles reloads the UI. Profiles are shared across characters; use them to keep different setups (e.g. raid vs solo). |cffEBB706New Profile|r prompts for a name and creates it on the spot."] = "프로필을 전환하면 UI가 리로드됩니다. 프로필은 캐릭터 간 공유되며, 서로 다른 설정(예: 공격대 vs 솔로)을 유지하는 데 씁니다. |cffEBB706새 프로필|r은 이름을 입력받아 즉시 만듭니다."
L["Slash commands"] = "슬래시 명령어"
L["/eqs\n/everythingquests\n\n|cff999999Both open this options window.|r\n\n/eqs whatsnew\n\n|cff999999Show what's new in the latest update.|r\n\n/eqs session\n\n|cff999999Show a recap of your current play session.|r"] = "/eqs\n/everythingquests\n\n|cff999999둘 다 이 설정 창을 엽니다.|r\n\n/eqs whatsnew\n\n|cff999999최신 업데이트의 새 소식을 표시합니다.|r\n\n/eqs session\n\n|cff999999현재 플레이 세션 요약을 표시합니다.|r"
L["Show minimap button"] = "미니맵 버튼 표시"

-- EQ: Options/TabWorldQuests.lua
L["Gold"] = "골드"
L["Gear / Items"] = "장비/아이템"
L["Reputation tokens"] = "평판 증표"
L["Resources / Currencies"] = "자원/화폐"
L["Artifact Power"] = "유물력"
L["Profession quests"] = "전문기술 퀘스트"
L["PvP"] = "PvP"
L["Pet battles"] = "애완동물 대전"
L["Other / Uncategorized"] = "기타/미분류"
L["Classic"] = "클래식"
L["The Burning Crusade"] = "불타는 성전"
L["Wrath of the Lich King"] = "리치 왕의 분노"
L["Cataclysm"] = "대격변"
L["Mists of Pandaria"] = "판다리아의 안개"
L["Warlords of Draenor"] = "드레노어의 전쟁군주"
L["Legion"] = "군단"
L["Battle for Azeroth"] = "격전의 아제로스"
L["Shadowlands"] = "어둠땅"
L["Dragonflight"] = "용군단"
L["The War Within"] = "내부전쟁"
L["Midnight"] = "한밤"
L["Other"] = "기타"
L["World Quests"] = "전역 퀘스트"
L["Enable World Quests map features"] = "전역 퀘스트 지도 기능 활성화"
L["Off: Everything Quests stops putting World Quests on the map — no world-map pins, no reward summary box, no zone quest list. The boxes below do nothing while this is off. This switch is ONLY for World Quests. It does NOT remove the red \"!\" / \"?\" quest rings — those are your normal quests, and you turn them off on the General tab. It also does NOT change the World Quests list in your tracker (that's on the Tracker tab)."] = "끔: Everything Quests가 전역 퀘스트를 지도에 표시하지 않습니다 - 지도 핀, 보상 요약 상자, 지역 퀘스트 목록 모두 없음. 꺼져 있는 동안 아래 항목은 동작하지 않습니다. 이 스위치는 오직 전역 퀘스트용입니다. 빨간 \"!\" / \"?\" 퀘스트 고리는 제거하지 않습니다 - 그건 일반 퀘스트이며 일반 탭에서 끕니다. 추적기의 전역 퀘스트 목록도 바꾸지 않습니다(그건 추적기 탭)."
L["Show world quest pins on the world map"] = "지도에 전역 퀘스트 핀 표시"
L["Show zone quest list on zone maps"] = "지역 지도에 지역 퀘스트 목록 표시"
L["Filters by reward type"] = "보상 종류별 필터"
L["Enable All"] = "모두 켜기"
L["Disable All"] = "모두 끄기"
L["Filter by faction"] = "세력별 필터"
L["Uncheck a faction to hide its world quests on the map."] = "세력 체크를 해제하면 그 세력의 전역 퀘스트가 지도에서 숨겨집니다."
L["No major factions unlocked on this character yet."] = "이 캐릭터는 아직 주요 세력이 해금되지 않았습니다."
L["%s  |cffaaaaaa(Renown %d)|r"] = "%s  |cffaaaaaa(명성 %d)|r"
L["Faction %d"] = "세력 %d"
L["Display"] = "표시"
L["Time left"] = "남은 시간"
L["Reward"] = "보상"
L["Faction"] = "세력"
L["A-Z"] = "가나다"
L["Sort zone quest list by"] = "지역 퀘스트 목록 정렬 기준"
L["World map pin scale"] = "지도 핀 배율"
L["Filters apply immediately when the world map is open."] = "지도가 열려 있을 때 필터가 즉시 적용됩니다."

-- EQ: Options/TabChainGuide.lua
L["Chain Guide"] = "연계 가이드"
L["Chain Guide (Storylines)"] = "연계 가이드 (스토리라인)"
L["Open Chain Guide"] = "연계 가이드 열기"
L["Open Chain Guide on login"] = "접속 시 연계 가이드 열기"
L["Show unrouted questlines"] = "경로 없는 퀘스트라인 표시"
L["API discoveries not in our routing table."] = "라우팅 표에 없는 API 발견 항목."
L["Show tracked chain on the world map"] = "추적 중인 연계를 지도에 표시"
L["Pin the quests of the chain you're following on the world map, with your next step highlighted. Track a chain from the Track button in the Chain Guide."] = "따라가는 연계의 퀘스트를 지도에 표시하고 다음 단계를 강조합니다. 연계 가이드의 추적 버튼으로 연계를 추적하세요."
L["Window scale"] = "창 배율"
L["Character cache"] = "캐릭터 캐시"
L["Per-character chain progress is cached account-wide so alts can browse what your other characters have completed. Clearing the cache removes that cross-character data; live completions stay (Blizzard tracks those)."] = "캐릭터별 연계 진행이 계정 전체에 캐시되어 부캐가 다른 캐릭터의 완료 내역을 볼 수 있습니다. 캐시를 비우면 캐릭터 간 데이터가 삭제되며, 실시간 완료는 유지됩니다(블리자드가 추적함)."
L["Clear chain cache"] = "연계 캐시 비우기"
L["Clear all cached chain-completion data across every character?"] = "모든 캐릭터의 연계 완료 캐시 데이터를 지울까요?"
L["Clear"] = "비우기"
L["Cached: |cffffffff%d|r characters, |cffffffff%d|r waypoint locations\n|cffffffff%d|r chains across |cffffffff%d|r categories"] = "캐시: 캐릭터 |cffffffff%d|r명, 경로 위치 |cffffffff%d|r곳\n연계 |cffffffff%d|r개, 분류 |cffffffff%d|r개"
L["today"] = "오늘"
L["1 day ago"] = "1일 전"
L["%d days ago"] = "%d일 전"
L["\n|cffaaaaaaLast pruned: %s|r"] = "\n|cffaaaaaa마지막 정리: %s|r"
L["Prune stale entries now"] = "오래된 항목 지금 정리"
L["|cffEBB706EQ|r: pruned |cffffffff%d|r stale character record(s) and |cffffffff%d|r waypoint(s)."] = "|cffEBB706EQ|r: 오래된 캐릭터 기록 |cffffffff%d|r개와 경로 |cffffffff%d|r개를 정리했습니다."

-- EQ: Options/TabHistory.lua
L["History"] = "기록"
L["Quest History"] = "퀘스트 기록"
L["Record completed quests"] = "완료 퀘스트 기록"
L["When on, Everything Quests writes an entry to your account-wide quest history every time you turn in a quest. The data is shared across all of your characters; the history window can filter by character."] = "켜면 퀘스트를 완료할 때마다 Everything Quests가 계정 전체 퀘스트 기록에 항목을 작성합니다. 데이터는 모든 캐릭터 간 공유되며, 기록 창에서 캐릭터별로 필터링할 수 있습니다."
L["Maximum entries kept"] = "보관 최대 항목 수"
L["When the history grows past this many entries, the oldest ones are dropped. Set higher if you want a longer record, lower to save disk space. 5000 entries is enough for several months of heavy questing."] = "기록이 이 항목 수를 넘으면 가장 오래된 것부터 삭제됩니다. 더 길게 기록하려면 높이고, 디스크 공간을 아끼려면 낮추세요. 5000개면 몇 달간 집중적으로 퀘스트를 해도 충분합니다."
L["Open Quest History"] = "퀘스트 기록 열기"
L["Populate from past completions"] = "과거 완료 내역으로 채우기"
L["this character"] = "이 캐릭터"
L["|cffEBB706EQ History:|r added %d past completion%s for |cffffffff%s|r (no dates)."] = "|cffEBB706EQ 기록:|r |cffffffff%3$s|r의 과거 완료 %1$d건을 추가했습니다(날짜 없음)."
L["One-time per character: walks the list of quests this character has completed (according to the game's own record) and adds any that aren't already in your history. Entries created this way have no date — the game doesn't tell us when they happened."] = "캐릭터당 1회: 이 캐릭터가 완료한 퀘스트 목록(게임 자체 기록 기준)을 훑어 기록에 없는 것을 추가합니다. 이렇게 만든 항목은 날짜가 없습니다 - 게임이 언제였는지 알려주지 않습니다."
L["Re-scan for quest names"] = "퀘스트 이름 다시 검색"
L["|cffEBB706EQ History:|r requested %d quest name%s from the server. Names will fill in over the next minute or two."] = "|cffEBB706EQ 기록:|r 서버에 퀘스트 이름 %1$d개를 요청했습니다. 이름은 1~2분에 걸쳐 채워집니다."
L["|cffEBB706EQ History:|r nothing left to look up — every entry that can be resolved already is."] = "|cffEBB706EQ 기록:|r 더 조회할 것이 없습니다 - 해결 가능한 항목은 이미 모두 해결됨."
L["Some quests in the backfilled history show up as \"Quest #12345\" because Blizzard hasn't sent the client their name yet. This button asks the server for every missing one. Quests the server flatly has no data for (retired or internal IDs) will keep their numeric placeholder."] = "채워 넣은 기록의 일부 퀘스트는 블리자드가 아직 이름을 보내지 않아 \"Quest #12345\"로 표시됩니다. 이 버튼은 빠진 것을 모두 서버에 요청합니다. 서버에 데이터가 아예 없는 퀘스트(은퇴/내부 ID)는 숫자 자리표시자를 유지합니다."
L["Restore history from backup"] = "백업에서 기록 복원"
L["|cffEBB706EQ History:|r no backup yet — one is saved automatically each time you log out."] = "|cffEBB706EQ 기록:|r 아직 백업 없음 - 접속 종료할 때마다 자동 저장됩니다."
L["Restore quest history from the backup taken %s (%d entries)? This replaces the current history."] = "%s에 만든 백업(%d개 항목)에서 퀘스트 기록을 복원할까요? 현재 기록을 대체합니다."
L["Restore"] = "복원"
L["|cffEBB706EQ History:|r restored %d entr%s from backup."] = "|cffEBB706EQ 기록:|r 백업에서 %1$d개 항목을 복원했습니다."
L["Everything Quests saves a rolling backup of your history when you log out, and automatically restores it if your history is ever found empty or missing a character on load. Use this button to restore manually."] = "Everything Quests는 접속 종료 시 기록 백업을 갱신 저장하고, 접속 시 기록이 비어 있거나 캐릭터가 빠져 있으면 자동 복원합니다. 수동 복원하려면 이 버튼을 사용하세요."
L["Wipe history"] = "기록 삭제"
L["Delete ALL recorded quest history (every character)? This cannot be undone."] = "기록된 모든 퀘스트 기록(모든 캐릭터)을 삭제할까요? 되돌릴 수 없습니다."
L["Wipe"] = "삭제"
L["|cffEBB706EQ History:|r wiped."] = "|cffEBB706EQ 기록:|r 삭제됨."

-- EQ: Options/Frame.lua
L["Join our Discord!"] = "디스코드 참여!"
L["Join our Discord"] = "디스코드 참여"
L["Version %s"] = "버전 %s"
L["Everything Quests opens its full options in a dedicated window. Click the button below, or type |cffEBB706/eqs|r in chat."] = "Everything Quests는 전체 설정을 전용 창에서 엽니다. 아래 버튼을 클릭하거나 채팅에 |cffEBB706/eqs|r를 입력하세요."
L["Open Everything Quests Options"] = "Everything Quests 설정 열기"
L["|cffEBB706Everything Quests|r: couldn't open Options \226\128\148 %s"] = "|cffEBB706Everything Quests|r: 설정을 열 수 없습니다 - %s"

-- EQ: Core/Init.lua
L["Everything Quests Discord"] = "Everything Quests 디스코드"
L["Join the community for help, feedback, and updates.\nCopy the invite below (it's pre-selected — just press Ctrl+C):"] = "도움, 피드백, 업데이트를 위해 커뮤니티에 참여하세요.\n아래 초대 링크를 복사하세요(이미 선택됨 - Ctrl+C):"
L["Close"] = "닫기"
L["Copy the link below (it's pre-selected — just press Ctrl+C):"] = "아래 링크를 복사하세요(이미 선택됨 - Ctrl+C):"

-- EQ: Core/QuestRewards.lua
L["Equip — empty slot"] = "장착 - 빈 슬롯"
L["Equipped: ilvl %d"] = "장착 중: 아이템 레벨 %d"
L["+%d ilvl upgrade"] = "+%d 아이템 레벨 상승"
L["%d ilvl lower"] = "%d 아이템 레벨 낮음"
L["Same item level"] = "동일 아이템 레벨"
L["ilvl %d"] = "아이템 레벨 %d"
L["%d XP"] = "%d 경험치"
L["Choose one:"] = "하나 선택:"

-- EQ: Core/Util.lua
L["Expired"] = "만료됨"

-- EQ: Modules/ChainGuide/CampaignSource.lua
L["Campaign Map"] = "대장정 지도"

-- EQ: Modules/ChainGuide/ChainView.lua
L["Completed"] = "완료됨"
L["Ready to turn in"] = "완료 가능"
L["In your quest log"] = "퀘스트 일지에 있음"
L["Skipped"] = "건너뜀"
L["A later quest in this chain has already passed this one."] = "이 연계의 이후 퀘스트가 이미 이걸 지나쳤습니다."
L["May be worth going back to pick up."] = "돌아가서 받을 만할 수 있습니다."
L["Not started"] = "시작 안 함"
L["Level %d"] = "%d레벨"
L["Completed: "] = "완료: "
L["Completed (before tracking)"] = "완료됨 (추적 전)"
L["Shift-click to link in chat"] = "Shift-클릭하면 채팅에 링크"
L["Level %d–%d"] = "%d-%d레벨"
L["Click to open this chain"] = "클릭하면 이 연계를 엽니다"
L["Pick a chain on the left to view its quests."] = "왼쪽에서 연계를 선택하면 퀘스트를 봅니다."
L["Untrack"] = "추적 해제"
L["Track"] = "추적"
L["%d/%d done"] = "%d/%d 완료"
L["%d active"] = "%d개 진행 중"
L["|cffff9933%d skipped|r"] = "|cffff9933%d개 건너뜀|r"
L["Lv %d  •  ID %d"] = "Lv %d  \226\128\162  ID %d"
L["ON QUEST"] = "퀘스트 중"
L["NEXT"] = "다음"
L["(optional)"] = "(선택)"
L["Continue"] = "계속"
L["Track this chain"] = "이 연계 추적"
L["Follow this chain — its quests pin on the world map (next step highlighted) and your waypoint auto-advances to the next step as you complete it. Works even with this window closed. Click again to stop."] = "이 연계를 따라갑니다 - 퀘스트가 지도에 표시되고(다음 단계 강조), 완료하면 경로가 다음 단계로 자동 이동합니다. 이 창을 닫아도 작동합니다. 다시 클릭하면 중지."
L["(no quests defined for this chain yet)"] = "(이 연계에 아직 정의된 퀘스트 없음)"

-- EQ: Modules/ChainGuide/Frame.lua
L["Hide the navigation panel"] = "탐색 패널 숨김"
L["Collapse the category and chain list so the graph fills the whole window. Click again to bring it back."] = "분류 및 연계 목록을 접어 그래프가 창 전체를 채우게 합니다. 다시 클릭하면 되돌립니다."
L["Back"] = "뒤로"
L["Forward"] = "앞으로"
L["Home"] = "홈"
L["Options"] = "설정"
L["Find quest"] = "퀘스트 찾기"
L["Type a quest name or its ID to jump to the chain that contains it."] = "퀘스트 이름이나 ID를 입력하면 그 퀘스트가 포함된 연계로 이동합니다."
L["Go"] = "이동"
L["Categories"] = "분류"
L["Drag to resize"] = "드래그로 크기 조정"
L["|cffEBB706EQ Chain Guide:|r found quest |cffffffff%d|r%s — jumping to its chain."] = "|cffEBB706EQ 연계 가이드:|r 퀘스트 |cffffffff%d|r%s을 찾았습니다 - 해당 연계로 이동."
L["|cffEBB706EQ Chain Guide:|r quest |cffffffff%d|r%s isn't in any chain I know about."] = "|cffEBB706EQ 연계 가이드:|r 퀘스트 |cffffffff%d|r%s은 제가 아는 어떤 연계에도 없습니다."
L["|cffEBB706EQ Chain Guide:|r found |cffffffff%s|r — jumping to its chain."] = "|cffEBB706EQ 연계 가이드:|r |cffffffff%s|r을 찾았습니다 - 해당 연계로 이동."
L["|cffEBB706EQ Chain Guide:|r no chain quest matches |cffffffff%s|r."] = "|cffEBB706EQ 연계 가이드:|r |cffffffff%s|r와 일치하는 연계 퀘스트가 없습니다."
L["Pick a category"] = "분류 선택"
L["Chains"] = "연계"
L["%d / %d quests done"] = "%d / %d 퀘스트 완료"

-- EQ: Modules/ChainGuide/MapPin.lua
L["Your next step"] = "다음 단계"
L["On this quest"] = "현재 퀘스트"
L["Comes later in the chain"] = "연계 후반부"

-- EQ: Modules/ChainGuide/QuestMapButton.lua
L["Chain"] = "연계"
L["Find this quest in EQ's Chain Guide"] = "EQ 연계 가이드에서 이 퀘스트 찾기"
L["Falls back to a Wowhead link in chat if EQ doesn't have a chain for this quest yet."] = "EQ에 아직 이 퀘스트의 연계가 없으면 채팅에 Wowhead 링크를 표시합니다."

-- EQ: Modules/History/Frame.lua
L["(before tracking)"] = "(추적 전)"
L["|cffEBB706EQ History|r: |cffffffff%s|r isn't part of any chain in the Chain Guide."] = "|cffEBB706EQ 기록|r: |cffffffff%s|r은(는) 연계 가이드의 어떤 연계에도 포함되지 않습니다."
L["Right-click to open in the Chain Guide"] = "우클릭하여 연계 가이드에서 열기"
L["Click to expand"] = "클릭하여 펼치기"
L["Export"] = "내보내기"
L["Re-scan names"] = "이름 다시 검색"
L["Asks the server for the name of any \"Quest #12345\" entries. They'll fill in over the next minute or two as responses arrive."] = "\"Quest #12345\" 형태 항목의 이름을 서버에 요청합니다. 응답이 도착하면서 1~2분에 걸쳐 채워집니다."
L["Quests"] = "퀘스트"
L["Streak"] = "연속 기록"
L["Chain Timeline"] = "연계 일정표"
L["Activity"] = "활동"
L["Stats"] = "통계"
L["This Session"] = "현재 세션"
L["Character:"] = "캐릭터:"
L["All characters"] = "모든 캐릭터"
L["Date:"] = "날짜:"
L["All time"] = "전체 기간"
L["Today"] = "오늘"
L["Past 7 days"] = "최근 7일"
L["Past 30 days"] = "최근 30일"
L["Type:"] = "유형:"
L["All types"] = "모든 유형"
L["Campaign"] = "대장정"
L["Questline"] = "퀘스트라인"
L["Calling"] = "부름"
L["Recurring"] = "반복"
L["World Quest"] = "전역 퀘스트"
L["Sort:"] = "정렬:"
L["Date"] = "날짜"
L["Name"] = "이름"
L["Type"] = "종류"
L["Sort direction"] = "정렬 방향"
L["Click to flip ascending / descending."] = "클릭하여 오름차순 / 내림차순 전환."
L["Hide undated  |cffaaaaaa(backfilled)|r"] = "날짜 없음 숨기기  |cffaaaaaa(소급 입력)|r"
L["(no matching quests)"] = "(일치하는 퀘스트 없음)"
L["%d entries"] = "%d개 항목"
L["first"] = "처음"
L["oldest"] = "가장 오래됨"
L["newest"] = "가장 최근"
L["%d entries (showing %s %d)"] = "%d개 항목(%s %d개 표시)"
L["Current daily streak"] = "현재 일일 연속 기록"
L["Best daily streak"] = "최고 일일 연속 기록"
L["Total quests recorded with a date"] = "날짜와 함께 기록된 총 퀘스트"
L["Streak counts consecutive days (local time) with at least one quest turn-in across any character on the account. Today or yesterday keeps the streak alive - you don't lose it until a whole day passes with no activity."] = "연속 기록은 계정의 아무 캐릭터로든 최소 한 개 퀘스트를 완료한 연속된 날(현지 시간)을 셉니다. 오늘이나 어제가 포함되면 유지되며, 활동 없는 하루가 완전히 지나기 전까지는 사라지지 않습니다."
L["%d days"] = "%d일"
L["Chains where you have at least one completed quest. Click a chain to expand and see per-quest completion dates."] = "최소 한 개 퀘스트를 완료한 연계입니다. 연계를 클릭하면 펼쳐서 퀘스트별 완료 날짜를 볼 수 있습니다."
L["(no chain quests recorded yet)"] = "(아직 기록된 연계 퀘스트 없음)"
L["%d of %d quests recorded"] = "%d / %d 퀘스트 기록됨"
L["Quest turn-ins per day over the last %d days. Brighter = busier. Hover a cell for the date and count. The bottom-right cell is today."] = "최근 %d일 동안의 일별 퀘스트 완료 수입니다. 밝을수록 바쁜 날입니다. 칸 위에 마우스를 올리면 날짜와 횟수가 표시됩니다. 오른쪽 아래 칸이 오늘입니다."
L["%d quest%s turned in"] = "%1$d개 퀘스트 완료"
L["Less"] = "적음"
L["More"] = "많음"
L["total turn-ins in the last %d days"] = "최근 %d일 동안 총 완료"
L["Busiest day: %s (%d quests)"] = "가장 바쁜 날: %s (%d개 퀘스트)"
L["%dg %ds %dc"] = "%d골드 %d실버 %d코퍼"
L["Totals"] = "합계"
L["Trends"] = "추세"
L["Account-wide quest rewards. Totals count only quests turned in while reward tracking was on; older entries didn't capture XP or gold."] = "계정 전체 퀘스트 보상입니다. 합계는 보상 추적이 켜져 있는 동안 완료한 퀘스트만 셉니다. 이전 항목은 경험치나 골드를 기록하지 않았습니다."
L["Total quests with reward data"] = "보상 데이터가 있는 총 퀘스트"
L["Total gold earned"] = "획득한 총 골드"
L["Total XP earned"] = "획득한 총 경험치"
L["By character"] = "캐릭터별"
L["Top single-quest rewards"] = "단일 퀘스트 최고 보상"
L["%s  \194\183  %s quests  \194\183  %s  \194\183  %s XP"] = "%s  \194\183  %s 퀘스트  \194\183  %s  \194\183  %s 경험치"
L["Biggest gold:  |cffffffff%s|r  \194\183  %s"] = "최대 골드:  |cffffffff%s|r  \194\183  %s"
L["Biggest gold:  (none yet)"] = "최대 골드:  (아직 없음)"
L["Biggest XP:    |cffffffff%s|r  \194\183  %s XP"] = "최대 경험치:    |cffffffff%s|r  \194\183  %s 경험치"
L["Biggest XP:    (none yet)"] = "최대 경험치:    (아직 없음)"
L["Daily"] = "일일"
L["Weekly"] = "주간"
L["Show:"] = "표시:"
L["XP"] = "경험치"
L["Gold is all income (loot, vendor, rewards) tracked forward from when this version was installed \226\128\148 past periods may read 0. XP and quest counts come from quest turn-ins."] = "골드는 이 버전을 설치한 시점부터 추적된 모든 수입(전리품, 상인, 보상)입니다 - 이전 기간은 0으로 표시될 수 있습니다. 경험치와 퀘스트 수는 퀘스트 완료에서 가져옵니다."
L["This week"] = "이번 주"
L["last week"] = "지난 주"
L["yesterday"] = "어제"
L["%s \226\128\148 %s"] = "%s - %s"
L["%s vs %s"] = "%s vs %s"
L["Your quest activity this play session. A session starts when you log in and continues across /reload; it resets the next time you log in fresh."] = "이번 플레이 세션의 퀘스트 활동입니다. 세션은 접속할 때 시작되어 /reload 후에도 이어지며, 다음에 새로 접속하면 초기화됩니다."
L["Played this session"] = "이번 세션 플레이 시간"
L["Quests completed"] = "완료한 퀘스트"
L["Quest XP earned"] = "획득한 퀘스트 경험치"
L["Quest gold earned"] = "획득한 퀘스트 골드"
L["Level-ups"] = "레벨 상승"
L["   |cffaaaaaa(%.1f / hour)|r"] = "   |cffaaaaaa(시간당 %.1f)|r"
L["%d   |cffaaaaaa(%d to %d)|r"] = "%d   |cffaaaaaa(%d에서 %d)|r"
L["Press Ctrl+A to select all, then Ctrl+C to copy."] = "Ctrl+A로 전체 선택 후 Ctrl+C로 복사하세요."

-- EQ: Modules/History/Recorder.lua
L["first time seeing |cffffffff%s|r - added %d past completion%s (no dates; future turn-ins are dated)."] = "|cffffffff%1$s|r 캐릭터를 처음 확인했습니다 - 과거 완료 기록 %2$d건을 추가했습니다 (날짜 없음, 이후 완료부터는 날짜가 기록됩니다)."
L["Quest history loaded empty; restored a backup from %s (%d entries)."] = "퀘스트 기록이 비어 있어 %s의 백업을 복원했습니다 (%d개 항목)."
L["Quest history for %s was missing; restored a backup from %s (%d entries)."] = "%s의 퀘스트 기록이 없어 %s의 백업을 복원했습니다 (%d개 항목)."

-- EQ: Modules/TrackerBridge.lua
L["EQ Objective Tracker is not loaded, so the tracker is unavailable."] = "EQ Objective Tracker가 로드되지 않아 추적기를 사용할 수 없습니다."
L["Open the Chain Guide"] = "연계 가이드 열기"
L["Open the Everything Quests options"] = "Everything Quests 설정 열기"
L["Get Directions"] = "경로 안내"

-- EQ: Modules/WhatsNew.lua
L["See what's new"] = "새 소식 보기"
L["updated to"] = "업데이트:"
L["Open Options"] = "설정 열기"
L["Got it"] = "확인"
L["Don't show these again"] = "다시 표시 안 함"
L["Stops What's New notices entirely. You can turn them back on in /eqs > General."] = "새 소식 알림을 완전히 끕니다. /eqs > 일반에서 다시 켤 수 있습니다."

-- EQ: Modules/WorldQuests/Pin.lua
L["World Quest #"] = "전역 퀘스트 #"
L["Untrack Quest"] = "퀘스트 추적 해제"
L["Track Quest"] = "퀘스트 추적"
L["Super-track (follow arrow)"] = "주요 추적 (화살표 따라가기)"
L["Search on Wowhead"] = "Wowhead에서 검색"

-- EQ: Modules/WorldQuests/Summary.lua
L["Gear"] = "장비"
L["Reputation"] = "평판"
L["Resources"] = "자원"
L["Professions"] = "전문 기술"
L["Pet Battles"] = "애완동물 대전"

-- EQ: Modules/WorldQuests/Tab.lua
L["Click to hide the World Quests list."] = "클릭하여 전역 퀘스트 목록을 숨깁니다."
L["Click to show the World Quests list."] = "클릭하여 전역 퀘스트 목록을 표시합니다."

-- EQ: Modules/WorldQuests/Tooltip.lua
L["Time Left: "] = "남은 시간: "

-- EQ: Modules/WorldQuests/ZoneMap.lua
L["%s — %d quests"] = "%s - %d개 퀘스트"

-- EQ: Options/TabAbout.lua
L["Open or close the options window"] = "설정 창 열기/닫기"
L["Open the Quest History window"] = "퀘스트 기록 창 열기"
L["Recap your current play session in chat"] = "현재 플레이 세션을 채팅에 요약"
L["List the current zone's quest chains in chat"] = "현재 지역의 퀘스트 연계를 채팅에 표시"
L["Show the What's New popup again"] = "새 소식 팝업 다시 표시"
L["Open this About tab"] = "이 정보 탭 열기"
L["About"] = "정보"
L["by Wheelbarrel00"] = "제작: Wheelbarrel00"
L["for WoW Midnight (12.0.x)"] = "WoW 한밤 (12.0.x) 용"
L["A unified replacement for the Blizzard quest experience: a custom tracker, world-map overlays, quest history, and a Midnight chain guide."] = "블리자드 퀘스트 환경을 통합 대체합니다: 맞춤 추적기, 세계 지도 오버레이, 퀘스트 기록, 그리고 한밤 연계 가이드."
L["CurseForge"] = "CurseForge"
L["GitHub"] = "GitHub"
L["Report a Bug"] = "버그 신고"
L["What's New"] = "새 소식"
L["Commands"] = "명령어"
L["Tip: right-click the minimap button to open Options."] = "팁: 미니맵 버튼을 우클릭하면 설정이 열립니다."
L["Tutorials"] = "사용 안내"
L["Video tutorials are coming soon."] = "동영상 안내가 곧 제공됩니다."
L["More Add-ons by Wheelbarrel00"] = "Wheelbarrel00의 다른 애드온"
L["Thanks"] = "감사의 말"
L["Built with feedback, reports, and ideas from the community — especially "] = "커뮤니티의 피드백, 제보, 아이디어로 제작되었습니다 - 특히 "
L[". Thank you!"] = ". 감사합니다!"
L["Special thanks to "] = "특별히 감사드립니다: "
L[" for the many features, fixes, and reports that keep shaping Everything Quests."] = " Everything Quests를 계속 다듬어 가는 많은 기능 제안과 수정, 제보를 해 주셔서 감사합니다."
L[" for the many hours spent translating Everything Quests into French."] = " Everything Quests를 프랑스어로 번역하느라 많은 시간을 쏟아 주셔서 감사합니다."
L[" for the many hours spent translating Everything Quests into Russian."] = " Everything Quests를 러시아어로 번역하느라 많은 시간을 쏟아 주셔서 감사합니다."
L[" for the many hours spent translating Everything Quests into Korean."] = " Everything Quests를 한국어로 번역하느라 많은 시간을 쏟아 주셔서 감사합니다."
L["Changelog"] = "변경 내역"
L["Older versions are on CurseForge"] = "이전 버전은 CurseForge에 있습니다"

-- ====================================================================
-- EQ Objective Tracker (EQOT)
-- ====================================================================

-- EQOT: Options/TabGeneral.lua
L["General"] = "일반"
L["Lock tracker"] = "추적기 잠금"
L["Disable drag-to-move and resize."] = "드래그 이동/크기 조정 비활성화."
L["Hide tracker in combat"] = "전투 중 추적기 숨김"
L["Hides the tracker while you are in combat and brings it back when you leave."] = "전투 중에는 추적기를 숨기고, 전투가 끝나면 다시 표시합니다."
L["Hide tracker in instances"] = "인스턴스에서 추적기 숨김"
L["Raids, dungeons, delves."] = "공격대, 던전, 구렁."
L["Hide tracker when world map is open"] = "지도 열면 추적기 숨김"
L["Hides the tracker while the world map is up, so it does not sit over the map."] = "세계 지도가 열려 있는 동안 추적기를 숨겨 지도를 가리지 않게 합니다."
L["Hide tracker in Mythic+"] = "쐐기에서 추적기 숨김"
L["Hides the tracker during an active Mythic+ run, then brings it back when the run ends."] = "쐐기 진행 중에는 추적기를 숨기고, 종료되면 다시 표시합니다."
L["Auto-track accepted quests"] = "수락한 퀘스트 자동 추적"
L["Matches Blizzard's default."] = "블리자드 기본값과 동일."
L["Keep focused quest after relog"] = "재접속 후 집중 추적 퀘스트 유지"
L["Restores the waypoint arrow."] = "경로 화살표를 복원합니다."
L["Options Window Scale"] = "설정 창 배율"
L["Resizes this EQ Objective Tracker options window only. It does not change the quest tracker or anything shown in the game world. The new size applies when you let go of the slider."] = "이 EQ Objective Tracker 설정 창의 크기만 조절합니다. 퀘스트 추적기나 게임 화면에 표시되는 것은 바뀌지 않습니다. 슬라이더에서 손을 떼면 새 크기가 적용됩니다."
L["Reset position and size"] = "위치/크기 초기화"
L["Returns the tracker to its default position and size."] = "추적기를 기본 위치와 크기로 되돌립니다."
L["Reset all settings"] = "모든 설정 초기화"
L["Reset every EQ Objective Tracker setting to defaults? The interface will reload."] = "EQ Objective Tracker의 모든 설정을 기본값으로 초기화할까요? 인터페이스를 다시 불러옵니다."
L["Reset"] = "초기화"
L["Cancel"] = "취소"
L["Restores every setting on every tab to its default and reloads the interface. This also clears the Options Window Scale, which every character shares, and this character's collapsed sections and individually hidden entries."] = "모든 탭의 모든 설정을 기본값으로 되돌리고 인터페이스를 다시 불러옵니다. 모든 캐릭터가 공유하는 설정 창 배율, 그리고 이 캐릭터의 접힌 섹션과 개별 숨김 항목도 함께 초기화됩니다."
L["Profiles"] = "프로필"
L["Switching profiles reloads the UI. Profiles are shared across characters. Use them to keep different setups such as raid and solo. |cffEBB706New Profile|r prompts for a name and creates it on the spot."] = "프로필을 전환하면 UI가 리로드됩니다. 프로필은 캐릭터 간 공유되며, 서로 다른 설정(예: 공격대 vs 솔로)을 유지하는 데 씁니다. |cffEBB706새 프로필|r은 이름을 입력받아 즉시 만듭니다."
L["Active profile"] = "활성 프로필"
L["Switches to another saved settings profile. The interface reloads immediately when you pick one."] = "저장된 다른 설정 프로필로 전환합니다. 선택하는 즉시 인터페이스를 다시 불러옵니다."
L["New Profile"] = "새 프로필"
L["Profile name:"] = "프로필 이름:"
L["Create"] = "만들기"
L["Overwrite profile?"] = "프로필 덮어쓸까요?"
L["A profile named \"%s\" already exists. Overwrite it with a copy of your current settings?"] = "\"%s\" 프로필이 이미 있습니다. 현재 설정의 사본으로 덮어쓸까요?"
L["Overwrite"] = "덮어쓰기"
L["Prompts for a name, then creates a profile holding a copy of your current settings and switches to it. The interface reloads."] = "이름을 물어본 뒤 현재 설정을 복사한 프로필을 만들어 그쪽으로 전환합니다. 인터페이스를 다시 불러옵니다."

-- EQOT: Options/TabTracker.lua
L["Zone"] = "지역"
L["Groups entries under the heading they sit under in your quest log."] = "퀘스트 일지에서 속해 있는 머리글 기준으로 항목을 묶습니다."
L["Title"] = "제목"
L["Alphabetical by name."] = "이름 가나다순."
L["Status"] = "상태"
L["Puts everything that is ready to turn in at the top."] = "완료 가능한 것을 모두 맨 위로 올립니다."
L["Type"] = "종류"
L["Weekly first, then daily, then everything else. Only quests carry a type, so other sections fall back to alphabetical."] = "주간을 먼저, 그다음 일일, 나머지는 그 뒤로 정렬합니다. 종류 정보는 퀘스트에만 있어서 다른 섹션은 가나다순으로 정렬됩니다."
L["Level"] = "레벨"
L["Lowest quest level first."] = "낮은 퀘스트 레벨부터."
L["Distance"] = "거리"
L["Nearest objective first, updated as you move. A quest ready to turn in measures to its turn-in point."] = "가까운 목표부터 정렬하며, 이동하면 갱신됩니다. 완료 가능한 퀘스트는 완료 지점까지의 거리로 잽니다."
L["Recent"] = "최근"
L["Most recently accepted first."] = "최근에 수락한 것부터."
L["Manual"] = "수동"
L["Your own order. Drag quests up and down in the tracker to set it."] = "직접 정한 순서입니다. 추적기에서 퀘스트를 위아래로 드래그해 정하세요."
L["Campaign section"] = "대장정 섹션"
L["Quests section"] = "퀘스트 섹션"
L["Profession section"] = "전문기술 섹션"
L["Endeavors section"] = "과업 섹션"
L["Achievements section"] = "업적 섹션"
L["World Quests section"] = "전역 퀘스트 섹션"
L["Top"] = "상단"
L["Bottom"] = "하단"
L["Move %s up"] = "%s 위로 이동"
L["Move %s down"] = "%s 아래로 이동"
L["Reorders where this section sits in the tracker. A section only shows while it has something in it, so empty sections won't visibly move."] = "이 섹션이 추적기에서 놓이는 위치를 바꿉니다. 섹션은 내용이 있을 때만 표시되므로, 비어 있는 섹션은 눈에 띄게 움직이지 않습니다."
L["Tracker"] = "추적기"
L["On-Screen Tracker"] = "화면 추적기"
L["Changes apply immediately to the on-screen tracker."] = "변경 사항이 화면 추적기에 즉시 적용됩니다."
L["Show only tracked quests"] = "추적 중인 퀘스트만 표시"
L["Hides quests that are in your log but not tracked. Matches Blizzard's default tracker."] = "일지에는 있지만 추적하지 않는 퀘스트를 숨깁니다. 블리자드 기본 추적기와 동일합니다."
L["Simplify Mode"] = "간소화 모드"
L["Show only the first incomplete objective per quest."] = "퀘스트당 첫 미완료 목표만 표시."
L["Simplify tracked achievements"] = "추적 업적 간소화"
L["Show only incomplete criteria for tracked achievements."] = "추적 업적의 미완료 조건만 표시."
L["Sort Order"] = "정렬 순서"
L["Drag and drop the quests in the tracker to reorder them however you like."] = "추적기의 퀘스트를 드래그해서 원하는 대로 순서를 바꿀 수 있습니다."
L["Filters"] = "필터"
L["Show or hide this category of entry in the tracker."] = "이 분류의 항목을 추적기에 표시할지 정합니다."
L["Show only quests in current zone"] = "현재 지역의 퀘스트만 표시"
L["Only show entries with an objective on your current map. Entries whose provider cannot tell are always shown."] = "현재 지도에 목표가 있는 항목만 표시합니다. 제공자가 판별할 수 없는 항목은 항상 표시됩니다."
L["Reset filters to defaults"] = "필터를 기본값으로 초기화"
L["Turns all six category filters back on and clears the current-zone filter. Nothing else on this tab is changed."] = "여섯 개 분류 필터를 모두 다시 켜고 현재 지역 필터를 해제합니다. 이 탭의 다른 설정은 바뀌지 않습니다."
L["Tracker Visibility"] = "추적기 표시"
L["Uncheck to hide this section from the tracker even while it has entries."] = "체크를 해제하면 항목이 있어도 이 섹션을 추적기에서 숨깁니다."
L["Auto-list current-zone world quests"] = "현재 지역 전역 퀘스트 자동 목록"
L["Lists every WQ in your zone without tracking each."] = "각각 추적하지 않고 지역의 모든 전역 퀘스트를 나열합니다."
L["Set a custom World Quests height"] = "전역 퀘스트 높이 사용자 지정"
L["By default the World Quests area shares space with your quest list and gets squeezed when you have a lot of quests. Turn this on to give it its own height, set by the slider below."] = "기본적으로 전역 퀘스트 영역은 퀘스트 목록과 공간을 공유하여 퀘스트가 많으면 좁아집니다. 이 설정을 켜면 아래 슬라이더로 지정한 자체 높이를 갖습니다."
L["World Quests Height"] = "전역 퀘스트 높이"
L["Height in pixels for the world quest area. Only used while Set a custom World Quests height is on."] = "전역 퀘스트 영역의 높이(픽셀)입니다. 전역 퀘스트 높이 직접 지정이 켜져 있을 때만 사용됩니다."
L["Maximum Height (% of tracker)"] = "최대 높이 (추적기의 %)"
L["The most of the tracker the world quest area may take. Quest sections are given their space first, so this is a ceiling rather than a reservation. Only used while Set a custom World Quests height is off."] = "전역 퀘스트 영역이 추적기에서 차지할 수 있는 최대치입니다. 퀘스트 섹션에 먼저 자리를 주므로 확보가 아니라 상한입니다. 전역 퀘스트 높이 직접 지정이 꺼져 있을 때만 사용됩니다."
L["Section Order"] = "섹션 순서"
L["Rearrange the tracker's sections with the arrows below. A section only appears on the tracker while it has something in it, so reordering an empty section won't look like anything changed. World Quests scroll in their own panel and can only sit at the very top or bottom, so use the Top/Bottom control."] = "아래 화살표로 추적기의 섹션 순서를 바꿉니다. 섹션은 내용이 있을 때만 추적기에 나타나므로, 비어 있는 섹션의 순서를 바꿔도 변화가 없어 보일 수 있습니다. 전역 퀘스트는 자체 패널에서 스크롤되며 맨 위 또는 맨 아래에만 놓을 수 있습니다 - 위/아래 조절을 사용하세요."
L["World Quests Position"] = "전역 퀘스트 위치"
L["Where the World Quests panel sits on the tracker. |cffffffffTop|r puts it above your quests. |cffffffffBottom|r keeps it below your quests, which is the default. World Quests scroll in their own capped panel, which is why they can't be mixed in between the other sections."] = "전역 퀘스트 패널이 추적기에서 놓이는 위치입니다. |cffffffff위|r는 퀘스트 위에, |cffffffff아래|r는 퀘스트 아래(기본값)에 둡니다. 전역 퀘스트는 자체 제한된 패널에서 스크롤되므로 다른 섹션 사이에 섞을 수 없습니다."
L["Options"] = "설정"
L["Quest Title Color By Difficulty"] = "난이도별 퀘스트 제목 색상"
L["Colors each quest title by how hard it is for your level, the way the quest log does. The Quest Title Color Override on the Appearance tab wins over this while it is set."] = "퀘스트 일지처럼 내 레벨 대비 난이도에 따라 퀘스트 제목에 색을 입힙니다. 외형 탭의 퀘스트 제목 색상 덮어쓰기가 설정돼 있으면 그쪽이 우선합니다."
L["Show quest level prefix"] = "퀘스트 레벨 접두 표시"
L["For example, [60] Title."] = "예: [60] 제목."
L["Show zone label under quest titles"] = "퀘스트 제목 아래 지역 표시"
L["Adds the quest log heading each quest came from as a small line under its title."] = "각 퀘스트가 속한 퀘스트 일지 머리글을 제목 아래 작은 글씨로 붙입니다."
L["Show objective progress numbers"] = "목표 진행 숫자 표시"
L["For example, 0/4, 1/1, etc."] = "예: 0/4, 1/1 등."
L["Show quest ID"] = "퀘스트 ID 표시"
L["Useful for bug reports."] = "버그 신고에 유용."
L["Show the visible / total count on section headers"] = "섹션 머리글에 표시/전체 개수 표시"
L["For example, 3/9. Applies to every section header."] = "예: 3/9. 모든 섹션 머리글에 적용됩니다."
L["Show usable quest item buttons"] = "사용 가능한 퀘스트 아이템 버튼 표시"
L["Puts a button on the tracker row of any quest that carries a usable item, so you can use it without opening your bags."] = "사용 가능한 아이템이 딸린 퀘스트의 추적기 줄에 버튼을 답니다. 가방을 열지 않고 바로 사용할 수 있습니다."
L["Show Options icon on the tracker"] = "추적기에 설정 아이콘 표시"
L["A small cogwheel at the top-right of the tracker that opens the options panel."] = "추적기 우상단의 작은 톱니바퀴로 설정 패널을 엽니다."
L["Show Quest Discovered popups"] = "퀘스트 발견 팝업 표시"
L["Boxes for newly discovered / completed quests."] = "새로 발견/완료된 퀘스트 상자."
L["Show NEW tag on recently accepted quests"] = "최근 수락 퀘스트에 NEW 표시"
L["For about an hour after accepting."] = "수락 후 약 1시간 동안."
L["Split quest click"] = "퀘스트 클릭 분리"
L["Click the icon to focus, click the title to open the quest log."] = "아이콘 클릭은 집중 추적, 제목 클릭은 퀘스트 일지를 엽니다."
L["Quest Sound"] = "퀘스트 소리"
L["Plays when a quest is ready to turn in."] = "퀘스트를 완료할 수 있을 때 재생됩니다."
L["Quest Complete Sound"] = "퀘스트 완료 소리"
L["Which sound plays when a quest becomes ready to turn in."] = "퀘스트가 완료 가능해질 때 재생할 소리입니다."
L["Scenario Bonus Objectives"] = "시나리오 보너스 목표"
L["Show bonus objectives HUD"] = "보너스 목표 HUD 표시"
L["Shows a small movable checklist of the extra bonus objectives that appear during some scenarios and delves, so you do not miss their rewards. Drag to move, right-click to lock or reset. Off by default."] = "일부 시나리오와 구렁에서 나타나는 추가 보너스 목표를 작은 이동식 체크리스트로 표시하여 보상을 놓치지 않게 합니다. 드래그로 이동, 우클릭으로 잠금 또는 초기화. 기본은 꺼짐."
L["Test"] = "테스트"
L["Draws the HUD with two made-up bonus objectives so you can position and size it without being in a scenario or delve. Click again to clear it."] = "가짜 보너스 목표 두 개로 HUD를 그려서, 시나리오나 구렁에 들어가지 않고도 위치와 크기를 잡을 수 있게 합니다. 다시 누르면 지웁니다."
L["HUD Scale"] = "HUD 배율"
L["Sizes the bonus objectives HUD."] = "보너스 목표 HUD의 크기를 조정합니다."

-- EQOT: Options/TabAppearance.lua
L["None"] = "없음"
L["Outline"] = "외곽선"
L["Thick"] = "두꺼움"
L["Mono"] = "모노"
L["Mono Outline"] = "모노 외곽선"
L["Mono Thick"] = "모노 두꺼움"
L["Plain"] = "단순"
L["Card"] = "카드"
L["Header Bar 1"] = "헤더 막대 1"
L["Header Bar 2"] = "헤더 막대 2"
L["Left"] = "왼쪽"
L["Center"] = "중앙"
L["Right"] = "오른쪽"
L["Same as tracker font"] = "추적기 글꼴과 동일"
L["Appearance"] = "외형"
L["Font"] = "글꼴"
L["Fonts registered through LibSharedMedia, so anything from ElvUI or SharedMedia appears here too."] = "LibSharedMedia에 등록된 글꼴입니다. ElvUI나 SharedMedia가 추가한 글꼴도 여기에 나타납니다."
L["Font Size"] = "글꼴 크기"
L["Base size for objective text. Titles and headers offset from this."] = "목표 글자의 기준 크기입니다. 제목과 머리글은 여기서 보정됩니다."
L["Title Size Offset"] = "제목 크기 보정"
L["Sizes quest and achievement titles separately from the objective text. This value is added to the Font Size above: 0 keeps titles the same size as the base font, positive makes them larger, negative smaller."] = "퀘스트와 업적 제목을 목표 글자와 별도로 크기 조정합니다. 이 값은 위의 글꼴 크기에 더해집니다: 0이면 제목이 기본 글꼴과 같은 크기, 양수면 크게, 음수면 작게."
L["Header Size Offset"] = "머리글 크기 보정"
L["Sizes the section headers (Quests, Campaign, and so on) independently of the quest text. Added on top of the Font Size above: the default 4 keeps headers at their current size, lower shrinks them (handy on a low UI scale), higher enlarges them."] = "섹션 머리글(퀘스트, 대장정 등)을 퀘스트 글자와 독립적으로 크기 조정합니다. 위의 글꼴 크기에 더해집니다: 기본값 4는 머리글을 현재 크기로 유지하고, 낮추면 작아지며(낮은 UI 배율에서 유용), 높이면 커집니다."
L["Font Outline"] = "글꼴 외곽선"
L["Outlines keep small text legible over bright terrain."] = "외곽선은 밝은 지형 위에서도 작은 글자를 읽기 쉽게 해 줍니다."
L["Text Shadow"] = "글자 그림자"
L["Draws a soft drop-shadow behind all tracker text so it stays readable over bright or busy backgrounds. Use Shadow Color to tint it and Shadow Size to set how far it's cast."] = "추적기의 모든 글자 뒤에 부드러운 그림자를 그려 밝거나 복잡한 배경 위에서도 잘 보이게 합니다. 그림자 색상으로 색을 입히고 그림자 크기로 퍼지는 정도를 설정합니다."
L["Shadow Color"] = "그림자 색상"
L["Shadow color and opacity."] = "그림자 색상과 불투명도."
L["Shadow Size"] = "그림자 크기"
L["How far the text drop-shadow is cast behind the letters. Higher values give a larger, more pronounced shadow. Lower values keep it tight. Only applies while Text Shadow is on."] = "글자 뒤로 그림자가 퍼지는 거리. 값이 클수록 그림자가 크고 뚜렷하며, 작을수록 좁습니다. 글자 그림자가 켜져 있을 때만 적용됩니다."
L["Scenario"] = "시나리오"
L["Draws a drop-shadow behind the scenario / delve banner text (the Stage and name lines). This is SEPARATE from the Text Shadow above, which affects only the quest and objective text. The banner is styled on its own."] = "시나리오/구렁 배너 글자(단계 및 이름 줄) 뒤에 그림자를 그립니다. 이는 위의 글자 그림자와 별개이며, 글자 그림자는 퀘스트와 목표 글자에만 적용됩니다 - 배너는 따로 스타일링됩니다."
L["Color and opacity of the banner's drop shadow."] = "배너 그림자의 색상과 불투명도."
L["How far the scenario banner's drop-shadow is cast. Higher values give a larger, more pronounced shadow. Lower values keep it tight. Only applies while the Scenario Text Shadow above is on."] = "시나리오 배너 그림자가 퍼지는 거리. 값이 클수록 크고 뚜렷하며, 작을수록 좁습니다. 위의 시나리오 글자 그림자가 켜져 있을 때만 적용됩니다."
L["Banner Alignment"] = "배너 정렬"
L["Positions the scenario / delve banner within the tracker. Left lines it up with the quest text, Center keeps it centered (the default), and Right pushes it to the tracker's right edge."] = "시나리오/구렁 배너를 추적기 안에서 정렬합니다. 왼쪽은 퀘스트 글자에 맞추고, 중앙은 가운데 정렬(기본값), 오른쪽은 추적기의 오른쪽 끝으로 붙입니다."
L["Banner Text Size"] = "배너 글자 크기"
L["Grows or shrinks the scenario / delve banner's Stage and name text. 0 is the default size. The banner artwork is a fixed size, so large values may overflow it."] = "시나리오/구렁 배너의 단계 및 이름 글자를 키우거나 줄입니다. 0이 기본 크기입니다. 배너 그림은 크기가 고정이라 값이 크면 넘칠 수 있습니다."
L["Criteria Text Size"] = "목표 글자 크기"
L["Sizes the scenario / delve objective (criteria) lines shown under the banner, separately from the Banner Text Size above. Raise it if the criteria text looks small next to your quest and World Quest text."] = "배너 아래에 표시되는 시나리오/구렁 목표(달성 조건) 줄의 크기를 위의 배너 글자 크기와 별도로 조정합니다. 목표 글자가 퀘스트 및 전역 퀘스트 글자보다 작아 보이면 높이세요."
L["Scroll Bar"] = "스크롤 막대"
L["Hide scroll bar"] = "스크롤 막대 숨김"
L["Removes the tracker's scroll bar entirely and scrolls with the mouse wheel instead. Everything else in this group styles that bar, so it all stops applying while this is on."] = "추적기의 스크롤 막대를 아예 없애고 마우스 휠로 스크롤합니다. 이 그룹의 나머지 설정은 그 막대를 꾸미는 것이라, 이 옵션이 켜져 있는 동안에는 모두 적용되지 않습니다."
L["Scroll Bar Background"] = "스크롤 막대 배경"
L["Draws a track behind the scroll bar so it stays visible over bright terrain."] = "스크롤 막대 뒤에 트랙을 그려 밝은 지형 위에서도 잘 보이게 합니다."
L["Scroll Bar Color"] = "스크롤 막대 색상"
L["Color and opacity of the scroll bar track."] = "스크롤 막대 트랙의 색상과 불투명도."
L["Solid color thumb"] = "단색 손잡이"
L["Replaces the tracker scroll bar's textured thumb (the draggable block) with a flat single-color block. Use the Thumb Color and Thumb Width controls to style it. Off restores the stock Blizzard bar."] = "추적기 스크롤 막대의 텍스처 손잡이(드래그 블록)를 단색 블록으로 교체합니다. 손잡이 색상과 손잡이 너비로 스타일을 조정하세요. 끄면 블리자드 기본 막대로 복원됩니다."
L["Thumb Color"] = "손잡이 색상"
L["Color and opacity of the draggable block. Only used while Solid color thumb is on."] = "드래그 블록의 색상과 불투명도입니다. 단색 손잡이가 켜져 있을 때만 사용됩니다."
L["Thumb Width"] = "손잡이 너비"
L["How wide the draggable block is. Only used while Solid color thumb is on."] = "드래그 블록의 너비입니다. 단색 손잡이가 켜져 있을 때만 사용됩니다."
L["Hide scroll bar arrows"] = "스크롤 막대 화살표 숨김"
L["Hides the up and down arrow buttons at the ends of the tracker scroll bar. The bar still scrolls by dragging the thumb or using the mouse wheel."] = "추적기 스크롤 막대 양 끝의 위/아래 화살표 버튼을 숨깁니다. 막대는 손잡이를 드래그하거나 마우스 휠로 계속 스크롤됩니다."
L["Background"] = "배경"
L["Fills the tracker behind the text. Useful over bright terrain."] = "글자 뒤로 추적기를 채웁니다. 밝은 지형 위에서 유용합니다."
L["Background Color"] = "배경 색상"
L["Background color and opacity."] = "배경 색상과 불투명도."
L["Border"] = "테두리"
L["Draws a border around the tracker."] = "추적기 둘레에 테두리를 그립니다."
L["Border Color"] = "테두리 색상"
L["Border color and opacity."] = "테두리 색상과 불투명도."
L["Border Thickness"] = "테두리 두께"
L["Border thickness in pixels."] = "테두리 두께(픽셀)입니다."
L["Header Bar"] = "헤더 막대"
L["Show header bars"] = "헤더 막대 표시"
L["Draws a colored gradient bar behind each section header (Quests, Campaign, World Quests, and so on), for a look closer to the default Blizzard tracker. Off by default."] = "각 섹션 머리글(퀘스트, 대장정, 전역 퀘스트 등) 뒤에 색상 그라데이션 막대를 그려 기본 블리자드 추적기에 가까운 모습으로 만듭니다. 기본은 꺼짐."
L["Bar Color"] = "막대 색상"
L["Brightest end of the bar gradient. The other end is the same color darkened."] = "막대 그라데이션의 밝은 쪽 색입니다. 반대쪽은 같은 색을 어둡게 한 것입니다."
L["Bar Style"] = "막대 스타일"
L["Header Bar 1 is a horizontal gradient (bright on the left, dark on the right). Header Bar 2 is a vertical gradient (bright at the top, dark at the bottom). Bar Color, Bar Height, and Soft edges all apply to whichever style you pick."] = "헤더 막대 1은 가로 그라데이션입니다(왼쪽이 밝고 오른쪽이 어두움). 헤더 막대 2는 세로 그라데이션입니다(위쪽이 밝고 아래쪽이 어두움). 막대 색상, 막대 높이, 부드러운 가장자리는 선택한 스타일에 모두 적용됩니다."
L["Soft edges"] = "부드러운 가장자리"
L["Feathers the top, left, and right edges of the header bar so it blends into the UI instead of sitting in a hard box. The gradient color is unchanged. Only applies while Header bars is on. Off by default."] = "헤더 막대의 위쪽, 왼쪽, 오른쪽 가장자리를 부드럽게 하여 딱딱한 상자처럼 보이지 않고 UI에 자연스럽게 어우러지게 합니다. 그라데이션 색상은 그대로 유지됩니다. 헤더 막대가 켜져 있을 때만 적용되며, 기본값으로 꺼짐."
L["Bar Height"] = "막대 높이"
L["How tall the section-header bar is. The bar is centered on the header row, so larger values fill more of it."] = "섹션 머리글 막대의 높이입니다. 막대는 머리글 줄에 가운데 정렬되므로 값이 클수록 더 많이 채웁니다."
L["Edge Softness"] = "가장자리 부드러움"
L["How soft the header bar's feathered edges are when Soft edges is on. Higher is softer, lower tightens toward a hard edge."] = "부드러운 가장자리가 켜져 있을 때 헤더 막대의 가장자리가 얼마나 부드러운지 설정합니다. 값이 클수록 부드럽고, 작을수록 딱딱한 가장자리에 가까워집니다."
L["Colors & Dimensions"] = "색상 및 크기"
L["Reset to Defaults"] = "기본값으로 초기화"
L["Reset every setting on this tab to its defaults? The interface will reload."] = "이 탭의 모든 설정을 기본값으로 초기화할까요? 인터페이스를 다시 불러옵니다."
L["Restores every control on this tab, including the zone bar block, to its default. Other tabs are left alone."] = "지역 막대 그룹을 포함해 이 탭의 모든 항목을 기본값으로 되돌립니다. 다른 탭은 건드리지 않습니다."
L["Quest Title Color Override"] = "퀘스트 제목 색상 덮어쓰기"
L["When cleared, falls back to difficulty coloring or default yellow."] = "비우면 난이도 색상 또는 기본 노란색으로 돌아갑니다."
L["Use class color for titles"] = "제목에 직업 색상 사용"
L["Colors quest, achievement, and endeavor titles with the class color of the character you are currently logged in on. Overrides the color above while it is on. Off by default."] = "퀘스트, 업적, 과업 제목을 현재 접속한 캐릭터의 직업 색상으로 표시합니다. 켜져 있는 동안 위의 색상을 덮어씁니다. 기본은 꺼짐."
L["Use title color for completed quests"] = "완료 퀘스트에 제목 색상 사용"
L["Instead of green."] = "녹색 대신."
L["Section Header Color"] = "섹션 헤더 색상"
L["Color of the Quests, Campaign and World Quests headings."] = "퀘스트, 대장정, 전역 퀘스트 머리글의 색상입니다."
L["Use class color for headers"] = "머리글에 직업 색상 사용"
L["Colors the section headers (Quests, Campaign, and so on) with the class color of the character you are currently logged in on. Overrides the color above while it is on. Off by default."] = "섹션 머리글(퀘스트, 대장정 등)을 현재 접속한 캐릭터의 직업 색상으로 표시합니다. 켜져 있는 동안 위의 색상을 덮어씁니다. 기본은 꺼짐."
L["Divider Line Color"] = "구분선 색상"
L["Sets the color of the thin line under each section header. Defaults to the original gold."] = "각 섹션 머리글 아래의 가는 선 색상을 설정합니다. 기본값은 원래의 금색입니다."
L["Tracker Scale"] = "추적기 배율"
L["Scales the whole tracker. Takes effect immediately out of combat."] = "추적기 전체의 배율입니다. 비전투 중에는 즉시 적용됩니다."
L["Block Spacing"] = "블록 간격"
L["Vertical gap between each entry and between sections."] = "항목 사이, 섹션 사이의 세로 간격입니다."
L["Line Spacing"] = "줄 간격"
L["Adds vertical space between a quest's objective lines, across the whole tracker. 0 keeps the default spacing."] = "추적기 전체에서 퀘스트 목표 줄 사이에 세로 여백을 추가합니다. 0은 기본 간격을 유지합니다."
L["Header Spacing"] = "머리글 간격"
L["Adds or removes space around section headers and beneath each quest's title. 0 keeps the default spacing."] = "섹션 머리글 주위와 각 퀘스트 제목 아래의 여백을 늘리거나 줄입니다. 0은 기본 간격을 유지합니다."
L["Quest Rows"] = "퀘스트 줄"
L["Row Layout"] = "줄 배치"
L["How each quest is drawn in the tracker. |cffffffffPlain|r is the default look - text straight on the tracker background. |cffffffffCard|r gives every quest its own panel with a background and border, which makes long lists easier to read apart."] = "추적기에서 각 퀘스트를 그리는 방식입니다. |cffffffff단순|r은 기본 모양으로, 추적기 배경 위에 글자만 표시합니다. |cffffffff카드|r는 퀘스트마다 배경과 테두리가 있는 개별 판을 주어 목록이 길어져도 구분하기 쉽습니다."
L["Fill color behind each quest card. Only used while Row Layout is set to Card."] = "각 퀘스트 카드 뒤의 채우기 색상입니다. 줄 배치가 카드일 때만 사용됩니다."
L["Outline color around each quest card. Only used while Row Layout is set to Card."] = "각 퀘스트 카드 둘레의 외곽선 색상입니다. 줄 배치가 카드일 때만 사용됩니다."
L["How thick the card outline is, in pixels. 0 hides the outline and leaves just the fill."] = "카드 외곽선의 두께입니다(픽셀). 0으로 하면 외곽선을 숨기고 채우기만 남깁니다."
L["Card Padding"] = "카드 여백"
L["Breathing room between a card's edge and the text inside it. Larger values make taller cards."] = "카드 가장자리와 그 안의 글자 사이 여백입니다. 값이 클수록 카드가 높아집니다."
L["Tint cards by quest type"] = "퀘스트 종류별 카드 색상"
L["Gives campaign, legendary, dungeon and raid entries their own card color. Anything else uses the plain background color above."] = "대장정, 전설, 던전, 공격대 항목에 각각 고유한 카드 색상을 줍니다. 그 외에는 위의 기본 배경 색상을 사용합니다."
L["Campaign"] = "대장정"
L["Card color for campaign entries. Needs Tint cards by quest type switched on."] = "대장정 항목의 카드 색상입니다. 퀘스트 종류별 카드 색상을 켜야 적용됩니다."
L["Legendary"] = "전설"
L["Card color for legendary entries. Needs Tint cards by quest type switched on."] = "전설 항목의 카드 색상입니다. 퀘스트 종류별 카드 색상을 켜야 적용됩니다."
L["Dungeon"] = "던전"
L["Card color for dungeon entries. Needs Tint cards by quest type switched on."] = "던전 항목의 카드 색상입니다. 퀘스트 종류별 카드 색상을 켜야 적용됩니다."
L["Raid"] = "공격대"
L["Card color for raid entries. Needs Tint cards by quest type switched on."] = "공격대 항목의 카드 색상입니다. 퀘스트 종류별 카드 색상을 켜야 적용됩니다."
L["Zone Progress Bar"] = "지역 진행 막대"
L["Show zone progress bar"] = "지역 진행 막대 표시"
L["Approximate questline progress."] = "대략적인 퀘스트라인 진행도."
L["Float as a movable bar"] = "이동 가능한 막대로 띄우기"
L["Drag to move, right-click to lock or reset. Unticked, the bar becomes an ordinary tracker section instead and only Bar Texture and Bar Color still apply to it."] = "드래그로 옮기고, 우클릭으로 잠그거나 초기화합니다. 체크를 해제하면 막대가 일반 추적기 섹션이 되고, 막대 텍스처와 막대 색상만 계속 적용됩니다."
L["Fills the floating bar behind its text."] = "떠 있는 막대의 글자 뒤를 채웁니다."
L["Background color and opacity for the floating bar. While this is unset the bar uses a plain black fill that fades slightly once locked."] = "떠 있는 막대의 배경 색상과 불투명도입니다. 지정하지 않으면 검은 단색을 쓰며, 잠그면 살짝 흐려집니다."
L["Draws a border around the floating bar."] = "떠 있는 막대 둘레에 테두리를 그립니다."
L["Border color and opacity for the floating bar."] = "떠 있는 막대의 테두리 색상과 불투명도."
L["Zone Bar Scale"] = "지역 막대 배율"
L["Size of the floating bar. The docked section follows the tracker's own scale instead."] = "떠 있는 막대의 크기입니다. 도킹된 섹션은 추적기 자체 배율을 따릅니다."
L["Font for the floating bar's zone name, count and percentage. The docked section uses the tracker font."] = "떠 있는 막대의 지역명, 개수, 백분율에 쓸 글꼴입니다. 도킹된 섹션은 추적기 글꼴을 사용합니다."
L["Bar Texture"] = "막대 텍스처"
L["Sets the fill texture of the zone progress bar. Textures added by other media addons (such as SharedMedia, ElvUI, or Details) appear here too."] = "지역 진행 막대의 채우기 텍스처를 설정합니다. 다른 미디어 애드온(SharedMedia, ElvUI, Details 등)이 추가한 텍스처도 여기에 표시됩니다."
L["Fill color and opacity of the bar itself."] = "막대 자체의 채우기 색상과 불투명도."
L["Header Color"] = "헤더 색상"
L["Color of the zone name on the floating bar. The docked section uses the section header color."] = "떠 있는 막대의 지역명 색상입니다. 도킹된 섹션은 섹션 머리글 색상을 사용합니다."
L["Count Color"] = "개수 색상"
L["Color of the completed-of-total count on the floating bar."] = "떠 있는 막대의 완료/전체 개수 색상입니다."

-- EQOT: Options/TabAbout.lua
L["Open this window"] = "이 창 열기"
L["Lock moving and resizing"] = "이동/크기 조절 잠금"
L["Unlock moving and resizing"] = "이동/크기 조절 잠금 해제"
L["Restore the default position and size"] = "기본 위치와 크기로 복원"
L["Show or hide the tracker"] = "추적기 표시/숨김"
L["Print provider status to chat"] = "제공자 상태를 채팅으로 출력"
L["Toggle entry validation warnings"] = "항목 검증 경고 켜고 끄기"
L["About"] = "정보"
L["Version %s"] = "버전 %s"
L["by Wheelbarrel00"] = "제작: Wheelbarrel00"
L["A standalone replacement for the default objective tracker. It does not require Everything Quests, and never will."] = "기본 목표 추적기를 대체하는 독립 애드온입니다. Everything Quests가 필요하지 않으며, 앞으로도 그럴 일은 없습니다."
L["Commands"] = "명령어"
L["Content providers"] = "콘텐츠 제공자"
L["Providers are gated at load time by which TOC file your game flavor used. A provider that is not listed was never loaded."] = "제공자는 게임 버전이 어느 TOC 파일을 썼는지에 따라 로드 시점에 걸러집니다. 목록에 없는 제공자는 아예 로드되지 않은 것입니다."

-- EQOT: Options/Frame.lua
L["Plays the currently selected sound."] = "현재 선택한 소리를 재생합니다."
L["Clear"] = "비우기"

-- EQOT: Core/Init.lua
L["Copy the link below (it's pre-selected \226\128\148 just press Ctrl+C):"] = "아래 링크를 복사하세요(미리 선택돼 있으니 Ctrl+C 만 누르면 됩니다):"
L["Close"] = "닫기"

-- EQOT: Core/Migrate.lua
L["imported %d settings from Everything Quests."] = "Everything Quests에서 설정 %d개를 가져왔습니다."

-- EQOT: Data/Filter.lua
L["World Quests"] = "전역 퀘스트"
L["Bonus Objectives"] = "보너스 목표"
L["Campaign quests"] = "대장정 퀘스트"
L["Daily quests"] = "일일 퀘스트"
L["Weekly quests"] = "주간 퀘스트"
L["Normal quests"] = "일반 퀘스트"

-- EQOT: Data/Providers/Achievements.lua
L["Left-click to open, right-click to untrack."] = "좌클릭하여 열기, 우클릭하여 추적 해제."

-- EQOT: Data/Providers/Professions.lua
L["%s (Recraft)"] = "%s (재제작)"
L["Left-click to open the recipe, right-click to untrack."] = "좌클릭하여 열기, 우클릭하여 추적 해제."

-- EQOT: Data/Providers/Scenarios.lua
L["Ritual Site"] = "의식 지점"
L["Delves"] = "구렁"
L["Mythic+"] = "신화+"
L["Warfront"] = "격전지"
L["Proving Grounds"] = "수련의 장"
L["Follower Dungeon"] = "추종자 던전"
L["Void Incursion"] = "공허 침입"
L["Battleground"] = "전장"
L["Arena"] = "투기장"
L["Stage %d of %d"] = "단계 %d / %d"

-- EQOT: Data/Providers/WorldQuests.lua
L["Ready to turn in"] = "완료 가능"

-- EQOT: Data/ScenarioBonus.lua
L["Delve Bonus Loot"] = "구렁 보너스 전리품"
L["Nemesis Strongbox: %d/%d packs"] = "원수의 금고: %d/%d 무리"
L["Sanctified Banner: Grand Spoils earned"] = "축성된 깃발: 큰 전리품 획득 완료"
L["Sanctified Banner: bonus Spoils secured"] = "축성된 깃발: 보너스 전리품 확보"
L["Sanctified Banner: kill the Voidfused Rager"] = "축성된 깃발: 공허주입 분노령 처치"
L["Sanctified Banner: find it for bonus loot"] = "축성된 깃발: 찾으면 보너스 전리품"

-- EQOT: UI/AutoQuestPopup.lua
L["Click to view quest"] = "클릭하여 퀘스트 보기"
L["Quest Complete!"] = "퀘스트 완료!"
L["Quest Discovered!"] = "퀘스트 발견!"

-- EQOT: UI/Commands.lua
L["tracker locked."] = "추적기 잠김"
L["tracker unlocked."] = "추적기 잠금 해제됨."
L["position and size reset."] = "위치/크기 초기화됨."
L["nothing is hidden."] = "숨긴 항목이 없습니다."
L["%d hidden entries restored."] = "숨긴 항목 %d개를 복원했습니다."
L["no Everything Quests configuration found to import."] = "가져올 Everything Quests 설정을 찾지 못했습니다."
L["Import from Everything Quests"] = "Everything Quests에서 가져오기"
L["Reset this profile to defaults and replace it with your Everything Quests tracker settings?\n\nThis cannot be undone. Make a new profile first if you want to keep the current one."] = "이 프로필을 기본값으로 되돌린 뒤 Everything Quests 추적기 설정으로 교체할까요?\n\n되돌릴 수 없습니다. 현재 프로필을 남기려면 먼저 새 프로필을 만드세요."
L["Import"] = "가져오기"
L["commands:"] = "명령어:"

-- EQOT: UI/Dialog.lua
L["OK"] = "확인"

-- EQOT: UI/RewardTooltip.lua
L["Equip \226\128\148 empty slot"] = "착용 - 빈 칸"
L["Equipped: ilvl %d"] = "장착 중: 아이템 레벨 %d"
L["+%d ilvl upgrade"] = "+%d 아이템 레벨 상승"
L["%d ilvl lower"] = "%d 아이템 레벨 낮음"
L["Same item level"] = "동일 아이템 레벨"
L["ilvl %d"] = "아이템 레벨 %d"
L["%d XP"] = "%d 경험치"
L["Choose one:"] = "하나 선택:"
L["Time Left: "] = "남은 시간: "

-- EQOT: UI/Row.lua
L["Find Group"] = "그룹 찾기"
L["Open the Premade Group Finder for this quest."] = "이 퀘스트의 사전 구성 그룹 찾기를 엽니다."

-- EQOT: UI/RowMenu.lua
L["Pin to tracker"] = "추적기에 고정"
L["Unpin from tracker"] = "추적기에서 고정 해제"
L["Track Quest"] = "퀘스트 추적"
L["Untrack Quest"] = "퀘스트 추적 해제"
L["Focus"] = "집중 추적"
L["Unfocus"] = "집중 추적 해제"
L["Super-track (follow arrow)"] = "주요 추적 (화살표 따라가기)"
L["Open in Map & Quest Log"] = "지도 및 퀘스트 일지에서 열기"
L["Pop Out Quest Details"] = "퀘스트 상세 정보 창 띄우기"
L["Search on Wowhead"] = "Wowhead에서 검색"
L["Abandon Quest"] = "퀘스트 포기"

-- EQOT: UI/Scenario.lua
L["Final Stage"] = "마지막 단계"
L["Stage %d"] = "%d단계"

-- EQOT: UI/ScenarioBonusHUD.lua
L["Unlock (allow moving)"] = "잠금 해제(이동 허용)"
L["Lock position"] = "위치 잠금"
L["Reset position"] = "위치 초기화"

-- EQOT: UI/Sections.lua
L["Zone Progress"] = "지역 진행도"
L["Quests"] = "퀘스트"
L["Achievements"] = "업적"
L["Endeavors"] = "과업"
L["Profession"] = "전문기술"

-- EQOT: UI/Tracker.lua
L["Tracker locked"] = "추적기 잠김"
L["Use /eqot unlock to move it."] = "/eqot unlock 으로 옮길 수 있습니다."
L["Drag to move, corner grip to resize."] = "드래그로 옮기고, 모서리 손잡이로 크기를 조절합니다."
L["/eqot for options"] = "/eqot 로 설정 열기"
L["Open the options panel"] = "설정 패널 열기"
L["a visibility rule is keeping the tracker hidden - see /eqot, General."] = "표시 규칙 때문에 추적기가 숨겨져 있습니다. /eqot 의 일반 탭을 확인하세요."

return L
