-- store/_retired/frFR.lua
-- French translations for phrases no addon in the family currently uses.
--
-- NOT dead. A phrase lands here when the last addon using it drops or rewords it,
-- and scan.py moves it straight back into store/frFR.lua the moment any addon
-- starts using that exact English key again. Everything Quests v1.38.0 moved 224
-- phrases to EQ Objective Tracker in one release - this is what stops that costing
-- a translation.
--
-- Nothing here reaches the game. There is no reason to translate anything in this
-- file, and no reason to delete anything from it either.

local L = {}

L["An on-screen panel while inside a delve showing the story variant and its grade, the recommended curios for your role, your run timer, and your death count."] = "Un panneau à l'écran pendant que vous êtes dans un gouffre, montrant la variante d'histoire et son rang, les curiosités recommandées pour votre rôle, votre chrono de parcours et votre nombre de morts."
L["By default the World Quests area shares space with your quest list and gets squeezed when you have a lot of quests. Turn this on to give it its own height, set by the slider below."] = "Par défaut, la zone des Expéditions partage l'espace avec votre liste de quêtes et se retrouve à l'étroit quand vous avez beaucoup de quêtes. Activez ceci pour lui donner sa propre hauteur, réglée par le curseur ci-dessous."
L["Draws the red circle behind every world map marker for a quest in your log, both the ones you are still working on and the ones that are ready to turn in. Off by default for plain icons and a much quieter map when a zone is busy."] = "Dessine le cercle rouge derrière chaque marqueur de la carte du monde correspondant à une quête de votre journal, aussi bien celles que vous êtes en train de faire que celles qui sont prêtes à être rendues. Désactivé par défaut, pour des icônes simples et une carte bien plus lisible quand une zone est chargée."
L["Draws the red circle behind every world map marker for a quest in your log, both the ones you are still working on and the ones that are ready to turn in. Off by default for plain icons and a much quieter map when a zone is busy. The gold ring on quests you have not picked up yet is left alone, because it is the only thing telling those apart from the quests you are already carrying."] = "Dessine le cercle rouge derrière chaque marqueur de la carte du monde correspondant à une quête de votre journal, aussi bien celles que vous êtes en train de faire que celles qui sont prêtes à être rendues. Désactivé par défaut, pour des icônes simples et une carte bien plus lisible quand une zone est chargée. L'anneau doré des quêtes que vous n'avez pas encore prises n'est pas touché, car il est la seule chose qui les distingue des quêtes que vous avez déjà acceptées."
L["Draws the red circle behind every world map marker for a quest in your log, both the ones you are still working on and the ones that are ready to turn in. Uncheck it for plain icons and a much quieter map when a zone is busy. The gold ring on quests you have not picked up yet is left alone, because it is the only thing telling those apart from the quests you are already carrying."] = "Dessine le cercle rouge derrière chaque marqueur de la carte du monde correspondant à une quête de votre journal, aussi bien celles que vous êtes en train de faire que celles qui sont prêtes à être rendues. Décochez cette case pour obtenir des icônes simples et une carte bien plus lisible quand une zone est chargée. L'anneau doré des quêtes que vous n'avez pas encore prises n'est pas touché, car il est la seule chose qui les distingue des quêtes que vous avez déjà acceptées."
L["for WoW Midnight (12.0.x)"] = "pour WoW Midnight (12.0.x)"
L["Frosthearth Venom \226\128\148 cuts enemy attack and cast speed by 20 percent, which buys time on both Soul Extinction and the Void Toxin dispel."] = "Frosthearth Venom — réduit la vitesse d'attaque et d'incantation des ennemis de 20 pour cent, ce qui vous laisse du temps à la fois sur Soul Extinction et sur la dissipation de Void Toxin."
L["Leaves out quests that are sorted into a dungeon or a raid. There are 721 of them, and most are picked up inside the instance or from a quest giver at its door, so they clutter the outdoor map without helping you while you are questing in the world."] = "Exclut les quêtes rattachées à un donjon ou à un raid. Il y en a 721, et la plupart se prennent à l'intérieur de l'instance ou auprès d'un donneur de quête posté à son entrée, donc elles encombrent la carte extérieure sans vous aider pendant que vous questez dans le monde."
L["Leaves out quests the game has already greyed out for you, using the game's own threshold rather than a fixed number of levels. On by default. Turn it off to see everything a quest giver has, including the quests you have outlevelled."] = "Laisse de côté les quêtes que le jeu a déjà grisées pour vous, en utilisant le seuil du jeu lui-même plutôt qu'un nombre fixe de niveaux. Activé par défaut. Désactivez-le pour voir tout ce qu'un donneur de quête propose, y compris les quêtes dont vous avez dépassé le niveau."
L["Leaves out the 141 quests that require a trade skill, such as a Blacksmithing or Alchemy specialisation. Everything Quests cannot read your skill levels on this version of the game, so these are offered even when you have not trained the profession they need."] = "Exclut les 141 quêtes qui exigent un métier, comme une spécialisation en forge ou en alchimie. Everything Quests ne peut pas lire vos niveaux de compétence sur cette version du jeu, donc ces quêtes sont proposées même si vous n'avez pas appris le métier requis."
L["Leaves out the 141 quests that require a trade skill, such as a Blacksmithing or Alchemy specialization. Everything Quests cannot read your skill levels on this version of the game, so these are offered even when you have not trained the profession they need."] = "Exclut les 141 quêtes qui exigent un métier, comme une spécialisation en forge ou en alchimie. Everything Quests ne peut pas lire vos niveaux de compétence sur cette version du jeu, donc ces quêtes sont proposées même si vous n'avez pas appris le métier requis."
L["Leaves out the quests you can hand in over and over, usually a turn-in for reputation or a common trade good. There are 609 of them and they never stop being offered, so they stay on the map forever once you can see them."] = "Exclut les quêtes que vous pouvez rendre encore et encore, en général une remise pour de la réputation ou une ressource commune. Il y en a 609 et elles restent proposées indéfiniment, donc elles ne quittent plus la carte une fois visibles."
L["Look up any quest in the game"] = "Consulter n'importe quelle quête du jeu"
L["Look up any quest in the game, including ones you have never picked up. Shows the level and race and class requirements, where it starts and turns in, what has to be finished first, and why you cannot take it yet. Also on /eqs quests, or right-click a gold quest marker on the map."] = "Consultez n'importe quelle quête du jeu, y compris celles que vous n'avez jamais prises. Affiche le niveau, les conditions de race et de classe, où elle commence et où elle se rend, ce qu'il faut terminer avant, et pourquoi vous ne pouvez pas encore la prendre. Également accessible par /eqs quests, ou par un clic droit sur un marqueur de quête doré sur la carte."
L["Marks every quest giver who has something for you but is not in your quest log yet, with a gold ring around the exclamation mark so it reads apart from the quests you are already carrying. One marker covers a whole quest giver, and hovering it lists everything that giver offers. Quests are filtered by your level, race, class and the quests you have already finished. Holiday quests are left out, because nothing in the data says whether the holiday is running."] = "Marque chaque donneur de quête qui a quelque chose pour vous sans que la quête soit déjà dans votre journal, avec un anneau doré autour du point d'exclamation pour le distinguer des quêtes que vous avez déjà prises. Un seul marqueur couvre tout un donneur de quête, et le survoler liste tout ce qu'il propose. Les quêtes sont filtrées selon votre niveau, votre race, votre classe et les quêtes que vous avez déjà terminées. Les quêtes de fête sont exclues, car rien dans les données n'indique si la fête est en cours."
L["Maximum Height (% of tracker)"] = "Hauteur maximale (pourcentage du module de suivi)"
L["Quest pins already grow as you zoom in and shrink as you zoom out. This scales that whole range, so raise it if the pins are hard to pick out on a large or high-resolution display."] = "Les marqueurs de quête grandissent déjà quand vous zoomez et rétrécissent quand vous dézoomez. Ce réglage ajuste toute cette plage : augmentez-le si les marqueurs sont difficiles à repérer sur un grand écran ou en haute résolution."
L["Season 2 also gives her a Poison slot. This popup does not cover it yet - the Nemesis tab already recommends one for Azta'rec."] = "La saison 2 lui donne aussi un emplacement Poison. Cette fenêtre ne le couvre pas encore - l'onglet Némésis en recommande déjà un pour Azta'rec."
L["These are the round red markers Everything Quests puts on the big world map for quests you've already picked up (the ones in your quest log). A red \"!\" means \"go here for this quest's next step.\" A red \"?\" means \"this quest is done \226\128\148 go here to turn it in.\" Quests you haven't accepted yet keep the game's own yellow \"!\" markers; EQ does not change those. Uncheck this box and all of EQ's red markers go away."] = "Ce sont les marqueurs ronds rouges qu'Everything Quests indique sur la carte du monde pour les quêtes déjà présentes dans votre journal de quêtes. Un \"!\" rouge signifie \"Allez ici pour la prochaine étape de la quête.\". Un \"?\" rouge signifie \"cette quête est accomplie \226\128\148 venez ici pour la rendre.\" Les quêtes que vous n'avez pas encore accepté conservent le marqueur \"!\" jaune du jeu; EQ ne les change pas. Décochez cette case pour désactiver tous les marqueurs rouges d'EQ."
L["Three of the six unlock from the quest \"%s\"."] = "Trois des six se débloquent via la quête \"%s\"."
L["Turns all six category filters back on and clears the current-zone filter. Nothing else on this tab is changed."] = "Réactive les six filtres de catégorie et efface le filtre de zone actuelle. Rien d'autre sur cet onglet n'est modifié."

return L
