-- store/_retired/frFR.lua
-- French translations for phrases no addon in the family currently uses.
--
-- NOT dead. A phrase lands here when the last addon using it drops or rewords it,
-- and scan.py moves it straight back into store/frFR.lua the moment any addon
-- starts using that exact English key again. Everything Quests v1.38.0 moved 224
-- phrases to EQ Objective Tracker in one release - this is what stops that costing
-- a translation.
--
-- Nothing here reaches the game. There is no reason to translate anything in this
-- file, and no reason to delete anything from it either.

local L = {}

L["%d hidden entries restored."] = "%d entrées masquées restaurées"
L["/eqs\n/everythingquests\n\n|cff999999Both open this options window.|r\n\n/eqs whatsnew\n\n|cff999999Show what's new in the latest update.|r\n\n/eqs session\n\n|cff999999Show a recap of your current play session.|r"] = "/eqs\n/everythingquests\n\n|cff999999Ces deux commandes ouvre la fenêtre de configuration actuelle|r\n\n/eqs whatsnew\n\n|cff999999Affiche les nouveautés de la dernière mise-à-jour.|r\n\n/eqs session\n\n|cff999999Affiche un récapitulatif de votre session de jeu actuelle.|r"
L["A unified replacement for the Blizzard quest experience: a custom tracker, objective markers on the map and minimap, nameplate quest icons, and a browser for the quests you have not picked up yet."] = "Un remplacement unifié de l'expérience de quête de Blizzard: un module de suivi personnalisé, des marqueurs d'objectif sur la carte du monde et la mini-carte, des icônes de quête sur les cartes de nom et un navigateur pour les quêtes que vous n'avez pas encore acceptées."
L["A unified replacement for the Blizzard quest experience: a custom tracker, world-map overlays, quest history, and a Midnight chain guide."] = "Un remplacement unifié de l'expérience de quête de Blizzard: un module de suivi personnalisé, des superpositions sur la carte du monde, un historique des quêtes et un guide des suites de quêtes Midnight."
L["Also reads the progress other quest addons broadcast, so you see everyone in the group rather than only the people running EQ. When you join a group EQ asks those addons for their quest logs, the same way they ask each other. Your own progress is never sent on their channel."] = "Lit aussi la progression diffusée par les autres addons de quêtes, pour que vous voyiez tout le groupe et pas seulement les personnes qui utilisent EQ. Quand vous rejoignez un groupe, EQ demande à ces addons leurs journaux de quêtes, comme ils se le demandent entre eux. Votre propre progression n'est jamais envoyée sur leur canal."
L["An on-screen panel while inside a delve showing the story variant and its grade, the recommended curios for your role, your run timer, and your death count."] = "Un panneau à l'écran pendant que vous êtes dans un gouffre, montrant la variante d'histoire et son rang, les curiosités recommandées pour votre rôle, votre chrono de parcours et votre nombre de morts."
L["Bonus Spoils: Nemesis Strongbox packs + the Sanctified Banner — the bonus loot to grab before the boss."] = "Butin bonus: les groupes du Coffre-fort de la Némésis + le Sanctified Banner — le butin supplémentaire à récupérer avant le boss."
L["Bring back every entry you have hidden"] = "Réafficher toutes les entrées que vous avez masquées"
L["By default the World Quests area shares space with your quest list and gets squeezed when you have a lot of quests. Turn this on to give it its own height, set by the slider below."] = "Par défaut, la zone des Expéditions partage l'espace avec votre liste de quêtes et se retrouve à l'étroit quand vous avez beaucoup de quêtes. Activez ceci pour lui donner sa propre hauteur, réglée par le curseur ci-dessous."
L["Colors & Dimensions"] = "Couleurs & dimensions"
L["Colors each quest title by how hard it is for your level, the way the quest log does. The Quest Title Color Override on the Appearance tab wins over this while it is set."] = "Colore chaque titre de quête selon sa difficulté pour votre niveau, comme le fait le journal de quêtes. La Couleur titres de quêtes de l'onglet Apparence prévaut sur ce réglage tant qu'elle est définie."
L["Colors quest, achievement, and endeavor titles with the class color of the character you are currently logged in on. Overrides the color above while it is on. Off by default."] = "Colore les titres de quêtes, de hauts-faits et d'initiatives avec la couleur de classe du personnage actuellement connecté. Remplace la couleur ci-dessus lorsqu'activé. Désactivé par défaut."
L["Colors quest, achievement, and endeavor titles with the class color of the character you are currently logged in on. Overrides the color below while it is on. Off by default."] = "Colore les titres de quêtes, de hauts-faits et d'initiatives avec la couleur de classe du personnage actuellement connecté. Remplace la couleur ci-dessous lorsqu'activé. Désactivé par défaut."
L["Colors the section headers (Quests, Campaign, and so on) with the class color of the character you are currently logged in on. Overrides the color above while it is on. Off by default."] = "Colore les en-têtes de section (Quêtes, Campagne, etc.) avec la couleur de classe du personnage actuellement connecté. Remplace la couleur ci-dessus lorsqu'activé. Désactivé par défaut."
L["Draws a filled bar for objectives that report a percentage or a running total, the way the default tracker does, instead of a plain line of text. Applies to quests, World Quests, achievements and scenario objectives."] = "Dessine une barre remplie pour les objectifs qui indiquent un pourcentage ou un compteur, comme le fait le suivi par défaut, au lieu d'une simple ligne de texte. S'applique aux quêtes, aux expéditions, aux hauts faits et aux objectifs de scénario."
L["Draws the red circle behind every world map marker for a quest in your log, both the ones you are still working on and the ones that are ready to turn in. Off by default for plain icons and a much quieter map when a zone is busy."] = "Dessine le cercle rouge derrière chaque marqueur de la carte du monde correspondant à une quête de votre journal, aussi bien celles que vous êtes en train de faire que celles qui sont prêtes à être rendues. Désactivé par défaut, pour des icônes simples et une carte bien plus lisible quand une zone est chargée."
L["Draws the red circle behind every world map marker for a quest in your log, both the ones you are still working on and the ones that are ready to turn in. Off by default for plain icons and a much quieter map when a zone is busy. The gold ring on quests you have not picked up yet is left alone, because it is the only thing telling those apart from the quests you are already carrying."] = "Dessine le cercle rouge derrière chaque marqueur de la carte du monde correspondant à une quête de votre journal, aussi bien celles que vous êtes en train de faire que celles qui sont prêtes à être rendues. Désactivé par défaut, pour des icônes simples et une carte bien plus lisible quand une zone est chargée. L'anneau doré des quêtes que vous n'avez pas encore prises n'est pas touché, car il est la seule chose qui les distingue des quêtes que vous avez déjà acceptées."
L["Draws the red circle behind every world map marker for a quest in your log, both the ones you are still working on and the ones that are ready to turn in. Uncheck it for plain icons and a much quieter map when a zone is busy. The gold ring on quests you have not picked up yet is left alone, because it is the only thing telling those apart from the quests you are already carrying."] = "Dessine le cercle rouge derrière chaque marqueur de la carte du monde correspondant à une quête de votre journal, aussi bien celles que vous êtes en train de faire que celles qui sont prêtes à être rendues. Décochez cette case pour obtenir des icônes simples et une carte bien plus lisible quand une zone est chargée. L'anneau doré des quêtes que vous n'avez pas encore prises n'est pas touché, car il est la seule chose qui les distingue des quêtes que vous avez déjà acceptées."
L["for WoW Midnight (12.0.x)"] = "pour WoW Midnight (12.0.x)"
L["Frosthearth Venom \226\128\148 cuts enemy attack and cast speed by 20 percent, which buys time on both Soul Extinction and the Void Toxin dispel."] = "Frosthearth Venom — réduit la vitesse d'attaque et d'incantation des ennemis de 20 pour cent, ce qui vous laisse du temps à la fois sur Soul Extinction et sur la dissipation de Void Toxin."
L["Header Bar"] = "Barre d'en-tête"
L["Instead of green."] = "Au lieu du vert."
L["Leaves out quests that are sorted into a dungeon or a raid. There are 721 of them, and most are picked up inside the instance or from a quest giver at its door, so they clutter the outdoor map without helping you while you are questing in the world."] = "Exclut les quêtes rattachées à un donjon ou à un raid. Il y en a 721, et la plupart se prennent à l'intérieur de l'instance ou auprès d'un donneur de quête posté à son entrée, donc elles encombrent la carte extérieure sans vous aider pendant que vous questez dans le monde."
L["Leaves out quests the game has already greyed out for you, using the game's own threshold rather than a fixed number of levels. On by default. Turn it off to see everything a quest giver has, including the quests you have outlevelled."] = "Laisse de côté les quêtes que le jeu a déjà grisées pour vous, en utilisant le seuil du jeu lui-même plutôt qu'un nombre fixe de niveaux. Activé par défaut. Désactivez-le pour voir tout ce qu'un donneur de quête propose, y compris les quêtes dont vous avez dépassé le niveau."
L["Leaves out the 141 quests that require a trade skill, such as a Blacksmithing or Alchemy specialisation. Everything Quests cannot read your skill levels on this version of the game, so these are offered even when you have not trained the profession they need."] = "Exclut les 141 quêtes qui exigent un métier, comme une spécialisation en forge ou en alchimie. Everything Quests ne peut pas lire vos niveaux de compétence sur cette version du jeu, donc ces quêtes sont proposées même si vous n'avez pas appris le métier requis."
L["Leaves out the 141 quests that require a trade skill, such as a Blacksmithing or Alchemy specialization. Everything Quests cannot read your skill levels on this version of the game, so these are offered even when you have not trained the profession they need."] = "Exclut les 141 quêtes qui exigent un métier, comme une spécialisation en forge ou en alchimie. Everything Quests ne peut pas lire vos niveaux de compétence sur cette version du jeu, donc ces quêtes sont proposées même si vous n'avez pas appris le métier requis."
L["Leaves out the quests you can hand in over and over, usually a turn-in for reputation or a common trade good. There are 609 of them and they never stop being offered, so they stay on the map forever once you can see them."] = "Exclut les quêtes que vous pouvez rendre encore et encore, en général une remise pour de la réputation ou une ressource commune. Il y en a 609 et elles restent proposées indéfiniment, donc elles ne quittent plus la carte une fois visibles."
L["Look up any quest in the game"] = "Consulter n'importe quelle quête du jeu"
L["Look up any quest in the game, including ones you have never picked up. Shows the level and race and class requirements, where it starts and turns in, what has to be finished first, and why you cannot take it yet. Also on /eqs quests, or right-click a gold quest marker on the map."] = "Consultez n'importe quelle quête du jeu, y compris celles que vous n'avez jamais prises. Affiche le niveau, les conditions de race et de classe, où elle commence et où elle se rend, ce qu'il faut terminer avant, et pourquoi vous ne pouvez pas encore la prendre. Également accessible par /eqs quests, ou par un clic droit sur un marqueur de quête doré sur la carte."
L["Marks every quest giver who has something for you but is not in your quest log yet, with a gold ring around the exclamation mark so it reads apart from the quests you are already carrying. One marker covers a whole quest giver, and hovering it lists everything that giver offers. Quests are filtered by your level, race, class and the quests you have already finished. Holiday quests are left out, because nothing in the data says whether the holiday is running."] = "Marque chaque donneur de quête qui a quelque chose pour vous sans que la quête soit déjà dans votre journal, avec un anneau doré autour du point d'exclamation pour le distinguer des quêtes que vous avez déjà prises. Un seul marqueur couvre tout un donneur de quête, et le survoler liste tout ce qu'il propose. Les quêtes sont filtrées selon votre niveau, votre race, votre classe et les quêtes que vous avez déjà terminées. Les quêtes de fête sont exclues, car rien dans les données n'indique si la fête est en cours."
L["Maximum Height (% of tracker)"] = "Hauteur maximale (pourcentage du module de suivi)"
L["nothing is hidden."] = "Rien n'est masqué"
L["Off: Everything Quests stops putting World Quests on the map — no world-map pins, no reward summary box, no zone quest list. The boxes below do nothing while this is off. This switch is ONLY for World Quests. It does NOT remove the red \"!\" / \"?\" quest rings — those are your normal quests, and you turn them off on the General tab. It also does NOT change the World Quests list in your tracker (that's on the Tracker tab)."] = "Désactivé: Everything Quests arrête d'afficher les Expéditions sur la carte — pas de marqueurs, pas de résumé des récompenses, pas de liste des quêtes de la zone. Les cases ci-dessous ne servent à rien quand cette fonctionnalité est désactivée. Cette case ne fonctionne QUE pour les Expéditions. Cela ne retire PAS les anneaux de quête \"!\" / \"?\" — Ceux-ci concernent vos quêtes normales, et vous pouvez les désactiver dans l'onglet Général. Cela ne change PAS non plus la liste des Expéditions (Cela se passe dans l'onglet Module)."
L["Quest pins already grow as you zoom in and shrink as you zoom out. This scales that whole range, so raise it if the pins are hard to pick out on a large or high-resolution display."] = "Les marqueurs de quête grandissent déjà quand vous zoomez et rétrécissent quand vous dézoomez. Ce réglage ajuste toute cette plage : augmentez-le si les marqueurs sont difficiles à repérer sur un grand écran ou en haute résolution."
L["Quest Title Color By Difficulty"] = "Coloriser les noms de quête en fonction de la difficulté"
L["Quest Title Color Override"] = "Couleur titres de quêtes"
L["Restore every option to its default value."] = "Rétablir la valeur par défaut de chaque option."
L["Restores every setting on every tab to its default and reloads the interface. This also clears the Options Window Scale, which every character shares, and this character's collapsed sections and individually hidden entries."] = "Restaure tous les réglages de tous les onglets par défaut et recharge l'interface. Cela réinitialise aussi l'Échelle de la fenêtre d'options, commune à tous les personnages, ainsi que les sections repliées et les entrées masquées individuellement sur ce personnage."
L["Sanctified Banner - find it for bonus loot"] = "Sanctified Banner - trouvez-le pour du butin bonus"
L["Sanctified Banner - Grand Spoils earned!"] = "Sanctified Banner - grand butin obtenu!"
L["Sanctified Banner - kill the Voidfused Rager!"] = "Sanctified Banner - tuez le Voidfused Rager!"
L["Sanctified Banner found - bonus Spoils secured"] = "Sanctified Banner trouvé - butin bonus sécurisé"
L["Season 2 also gives her a Poison slot. This popup does not cover it yet - the Nemesis tab already recommends one for Azta'rec."] = "La saison 2 lui donne aussi un emplacement Poison. Cette fenêtre ne le couvre pas encore - l'onglet Némésis en recommande déjà un pour Azta'rec."
L["Show Options icon on the tracker"] = "Afficher l'icône Options sur le module de suivi"
L["Slash commands"] = "Commandes slash"
L["The most of this crest you're allowed to earn this season - the seasonal earning cap."] = "Le nombre maximum de cet écusson que vous pouvez gagner cette saison - le plafond saisonnier."
L["The seasonal cap on this crest - how many you can earn for the lower crests, and how many you can hold at once for the higher ones."] = "Le plafond saisonnier de cet écusson - pour les écussons inférieurs, le nombre que vous pouvez gagner, et pour les supérieurs, le nombre que vous pouvez posséder à la fois."
L["These are the round red markers Everything Quests puts on the big world map for quests you've already picked up (the ones in your quest log). A red \"!\" means \"go here for this quest's next step.\" A red \"?\" means \"this quest is done \226\128\148 go here to turn it in.\" Quests you haven't accepted yet keep the game's own yellow \"!\" markers; EQ does not change those. Uncheck this box and all of EQ's red markers go away."] = "Ce sont les marqueurs ronds rouges qu'Everything Quests indique sur la carte du monde pour les quêtes déjà présentes dans votre journal de quêtes. Un \"!\" rouge signifie \"Allez ici pour la prochaine étape de la quête.\". Un \"?\" rouge signifie \"cette quête est accomplie \226\128\148 venez ici pour la rendre.\" Les quêtes que vous n'avez pas encore accepté conservent le marqueur \"!\" jaune du jeu; EQ ne les change pas. Décochez cette case pour désactiver tous les marqueurs rouges d'EQ."
L["Three of the six unlock from the quest \"%s\"."] = "Trois des six se débloquent via la quête \"%s\"."
L["Turns all six category filters back on and clears the current-zone filter. Nothing else on this tab is changed."] = "Réactive les six filtres de catégorie et efface le filtre de zone actuelle. Rien d'autre sur cet onglet n'est modifié."
L["Use class color for titles"] = "Utiliser la couleur de classe pour les titres"
L["When cleared, falls back to difficulty coloring or default yellow."] = "Quand nettoyé, retourne à la couleur de difficulté ou à la couleur par défaut"
L["While inside a delve, tracks the two bonus-chest objectives - Nemesis Strongbox packs and the Sanctified Banner - so you know you've grabbed the extra loot before pulling the boss."] = "Dans un gouffre, suit les deux objectifs de coffres bonus - les groupes du Coffre-fort de la Némésis et le Sanctified Banner - pour que vous sachiez que le butin supplémentaire est récupéré avant de pull le boss."

return L
