-- store/_retired/koKR.lua
-- Korean translations for phrases no addon in the family currently uses.
--
-- NOT dead. A phrase lands here when the last addon using it drops or rewords it,
-- and scan.py moves it straight back into store/koKR.lua the moment any addon
-- starts using that exact English key again. Everything Quests v1.38.0 moved 224
-- phrases to EQ Objective Tracker in one release - this is what stops that costing
-- a translation.
--
-- Nothing here reaches the game. There is no reason to translate anything in this
-- file, and no reason to delete anything from it either.

local L = {}

L["%d hidden entries restored."] = "숨긴 항목 %d개를 복원했습니다."
L["%s  \194\183  %s quests  \194\183  %s  \194\183  %s XP"] = "%s  \194\183  %s 퀘스트  \194\183  %s  \194\183  %s 경험치"
L["/eqs\n/everythingquests\n\n|cff999999Both open this options window.|r\n\n/eqs whatsnew\n\n|cff999999Show what's new in the latest update.|r\n\n/eqs session\n\n|cff999999Show a recap of your current play session.|r"] = "/eqs\n/everythingquests\n\n|cff999999둘 다 이 설정 창을 엽니다.|r\n\n/eqs whatsnew\n\n|cff999999최신 업데이트의 새 소식을 표시합니다.|r\n\n/eqs session\n\n|cff999999현재 플레이 세션 요약을 표시합니다.|r"
L["A unified replacement for the Blizzard quest experience: a custom tracker, objective markers on the map and minimap, nameplate quest icons, and a browser for the quests you have not picked up yet."] = "블리자드 퀘스트 환경을 통합 대체합니다: 맞춤 추적기, 세계 지도와 미니맵의 목표 표식, 이름표 퀘스트 아이콘, 그리고 아직 수락하지 않은 퀘스트를 찾아보는 검색기."
L["A unified replacement for the Blizzard quest experience: a custom tracker, world-map overlays, quest history, and a Midnight chain guide."] = "블리자드 퀘스트 환경을 통합 대체합니다: 맞춤 추적기, 세계 지도 오버레이, 퀘스트 기록, 그리고 한밤 연계 가이드."
L["Account-wide quest rewards. Totals count only quests turned in while reward tracking was on; older entries didn't capture XP or gold."] = "계정 전체 퀘스트 보상입니다. 합계는 보상 추적이 켜져 있는 동안 완료한 퀘스트만 셉니다. 이전 항목은 경험치나 골드를 기록하지 않았습니다."
L["Adds the quest log heading each quest came from as a small line under its title."] = "각 퀘스트가 속한 퀘스트 일지 머리글을 제목 아래 작은 글씨로 붙입니다."
L["Also reads the progress other quest addons broadcast, so you see everyone in the group rather than only the people running EQ. When you join a group EQ asks those addons for their quest logs, the same way they ask each other. Your own progress is never sent on their channel."] = "다른 퀘스트 애드온이 보내는 진행도도 읽어, EQ를 쓰는 사람뿐 아니라 파티 전원을 볼 수 있습니다. 파티에 들어가면 EQ가 그 애드온들이 서로에게 하는 것과 같은 방식으로 퀘스트 일지를 요청합니다. 내 진행도는 그쪽 채널로 절대 보내지 않습니다."
L["An on-screen panel while inside a delve showing the story variant and its grade, the recommended curios for your role, your run timer, and your death count."] = "구렁 안에 있는 동안 이야기 변형과 등급, 역할에 맞는 추천 진기한 물건, 진행 시간, 사망 횟수를 보여주는 화면 패널입니다."
L["Biggest gold:  (none yet)"] = "최대 골드:  (아직 없음)"
L["Biggest gold:  |cffffffff%s|r  \194\183  %s"] = "최대 골드:  |cffffffff%s|r  \194\183  %s"
L["Biggest XP:    (none yet)"] = "최대 경험치:    (아직 없음)"
L["Biggest XP:    |cffffffff%s|r  \194\183  %s XP"] = "최대 경험치:    |cffffffff%s|r  \194\183  %s 경험치"
L["Bonus Spoils: Nemesis Strongbox packs + the Sanctified Banner — the bonus loot to grab before the boss."] = "추가 전리품: 원수의 금고 무리 + Sanctified Banner — 우두머리 전에 챙겨야 할 추가 전리품입니다."
L["Bring back every entry you have hidden"] = "숨긴 항목 모두 되살리기"
L["By default the World Quests area shares space with your quest list and gets squeezed when you have a lot of quests. Turn this on to give it its own height, set by the slider below."] = "기본적으로 전역 퀘스트 영역은 퀘스트 목록과 공간을 공유하여 퀘스트가 많으면 좁아집니다. 이 설정을 켜면 아래 슬라이더로 지정한 자체 높이를 갖습니다."
L["Card color for campaign quests. Needs Tint cards by quest type switched on."] = "대장정 퀘스트의 카드 색상입니다. 퀘스트 종류별 카드 색상을 켜야 적용됩니다."
L["Card color for dungeon quests. Needs Tint cards by quest type switched on."] = "던전 퀘스트의 카드 색상입니다. 퀘스트 종류별 카드 색상을 켜야 적용됩니다."
L["Card color for legendary quests. Needs Tint cards by quest type switched on."] = "전설 퀘스트의 카드 색상입니다. 퀘스트 종류별 카드 색상을 켜야 적용됩니다."
L["Card color for raid quests. Needs Tint cards by quest type switched on."] = "공격대 퀘스트의 카드 색상입니다. 퀘스트 종류별 카드 색상을 켜야 적용됩니다."
L["Categories"] = "분류"
L["Character:"] = "캐릭터:"
L["Collapse the category and chain list so the graph fills the whole window. Click again to bring it back."] = "분류 및 연계 목록을 접어 그래프가 창 전체를 채우게 합니다. 다시 클릭하면 되돌립니다."
L["Colors & Dimensions"] = "색상 및 크기"
L["Colors each quest title by how hard it is for your level, the way the quest log does. The Quest Title Color Override on the Appearance tab wins over this while it is set."] = "퀘스트 일지처럼 내 레벨 대비 난이도에 따라 퀘스트 제목에 색을 입힙니다. 외형 탭의 퀘스트 제목 색상 덮어쓰기가 설정돼 있으면 그쪽이 우선합니다."
L["Colors quest, achievement, and endeavor titles with the class color of the character you are currently logged in on. Overrides the color above while it is on. Off by default."] = "퀘스트, 업적, 과업 제목을 현재 접속한 캐릭터의 직업 색상으로 표시합니다. 켜져 있는 동안 위의 색상을 덮어씁니다. 기본은 꺼짐."
L["Colors quest, achievement, and endeavor titles with the class color of the character you are currently logged in on. Overrides the color below while it is on. Off by default."] = "퀘스트, 업적, 과업 제목을 현재 접속한 캐릭터의 직업 색상으로 표시합니다. 켜져 있는 동안 아래의 색상을 덮어씁니다. 기본은 꺼짐."
L["Colors the section headers (Quests, Campaign, and so on) with the class color of the character you are currently logged in on. Overrides the color above while it is on. Off by default."] = "섹션 머리글(퀘스트, 대장정 등)을 현재 접속한 캐릭터의 직업 색상으로 표시합니다. 켜져 있는 동안 위의 색상을 덮어씁니다. 기본은 꺼짐."
L["Date:"] = "날짜:"
L["Draws a filled bar for objectives that report a percentage or a running total, the way the default tracker does, instead of a plain line of text. Applies to quests, World Quests, achievements and scenario objectives."] = "백분율이나 누적 수치를 보여주는 목표에 기본 추적기처럼 채워지는 막대를 그립니다. 단순한 텍스트 줄 대신 표시되며, 퀘스트, 전역 퀘스트, 업적, 시나리오 목표에 적용됩니다."
L["For example, 3/9. Applies to every section header."] = "예: 3/9. 모든 섹션 머리글에 적용됩니다."
L["for WoW Midnight (12.0.x)"] = "WoW 한밤 (12.0.x) 용"
L["Frosthearth Venom \226\128\148 cuts enemy attack and cast speed by 20 percent, which buys time on both Soul Extinction and the Void Toxin dispel."] = "Frosthearth Venom — 적의 공격 속도와 시전 속도를 20퍼센트 낮춰, Soul Extinction과 Void Toxin 해제 양쪽에서 여유를 벌어 줍니다."
L["Give campaign, legendary, dungeon and raid quests their own card color so you can tell them apart at a glance. Anything else uses the plain background color above."] = "대장정, 전설, 던전, 공격대 퀘스트에 각각 고유한 카드 색상을 주어 한눈에 구분할 수 있게 합니다. 그 외에는 위의 기본 배경 색상을 사용합니다."
L["Go"] = "이동"
L["Header Bar"] = "헤더 막대"
L["Home"] = "홈"
L["Instead of green."] = "녹색 대신."
L["Lv %d  •  ID %d"] = "Lv %d  \226\128\162  ID %d"
L["Marks every quest giver who has something for you but is not in your quest log yet, with a gold ring around the exclamation mark so it reads apart from the quests you are already carrying. One marker covers a whole quest giver, and hovering it lists everything that giver offers. Quests are filtered by your level, race, class and the quests you have already finished. Holiday quests are left out, because nothing in the data says whether the holiday is running."] = "줄 것이 있지만 아직 퀘스트 일지에 없는 퀘스트 제공자를 모두 표시하며, 느낌표 둘레에 금색 테두리를 둘러 이미 수행 중인 퀘스트와 구분됩니다. 표식 하나가 제공자 한 명 전체를 나타내고, 마우스를 올리면 그 제공자가 주는 모든 퀘스트가 나열됩니다. 퀘스트는 레벨, 종족, 직업, 그리고 이미 완료한 퀘스트를 기준으로 걸러집니다. 축제 퀘스트는 데이터만으로 축제 진행 여부를 알 수 없어 제외됩니다."
L["Maximum Height (% of tracker)"] = "최대 높이 (추적기의 백분율)"
L["nothing is hidden."] = "숨긴 항목이 없습니다."
L["Off: Everything Quests stops putting World Quests on the map — no world-map pins, no reward summary box, no zone quest list. The boxes below do nothing while this is off. This switch is ONLY for World Quests. It does NOT remove the red \"!\" / \"?\" quest rings — those are your normal quests, and you turn them off on the General tab. It also does NOT change the World Quests list in your tracker (that's on the Tracker tab)."] = "끔: Everything Quests가 전역 퀘스트를 지도에 표시하지 않습니다 - 지도 핀, 보상 요약 상자, 지역 퀘스트 목록 모두 없음. 꺼져 있는 동안 아래 항목은 동작하지 않습니다. 이 스위치는 오직 전역 퀘스트용입니다. 빨간 \"!\" / \"?\" 퀘스트 고리는 제거하지 않습니다 - 그건 일반 퀘스트이며 일반 탭에서 끕니다. 추적기의 전역 퀘스트 목록도 바꾸지 않습니다(그건 추적기 탭)."
L["Pick a category"] = "분류 선택"
L["Quest Title Color By Difficulty"] = "난이도별 퀘스트 제목 색상"
L["Quest Title Color Override"] = "퀘스트 제목 색상 덮어쓰기"
L["Restore every option to its default value."] = "모든 옵션을 기본값으로 되돌립니다."
L["Restores every setting on every tab to its default and reloads the interface. This also clears the Options Window Scale, which every character shares, and this character's collapsed sections and individually hidden entries."] = "모든 탭의 모든 설정을 기본값으로 되돌리고 인터페이스를 다시 불러옵니다. 모든 캐릭터가 공유하는 설정 창 배율, 그리고 이 캐릭터의 접힌 섹션과 개별 숨김 항목도 함께 초기화됩니다."
L["Sanctified Banner - find it for bonus loot"] = "Sanctified Banner - 추가 전리품을 위해 찾아보세요"
L["Sanctified Banner - Grand Spoils earned!"] = "Sanctified Banner - 대규모 전리품 획득!"
L["Sanctified Banner - kill the Voidfused Rager!"] = "Sanctified Banner - Voidfused Rager를 처치하세요!"
L["Sanctified Banner found - bonus Spoils secured"] = "Sanctified Banner 발견 - 추가 전리품 확보"
L["Season 2 also gives her a Poison slot. This popup does not cover it yet - the Nemesis tab already recommends one for Azta'rec."] = "시즌 2에는 독 칸도 생겼습니다. 이 창은 아직 다루지 않으며 - 원수 탭에서 Azta'rec용 독을 이미 추천하고 있습니다."
L["Show Options icon on the tracker"] = "추적기에 설정 아이콘 표시"
L["Slash commands"] = "슬래시 명령어"
L["The header of the section you are scrolled into stays at the top of the quest list, so you can always see which section you are in. On by default."] = "스크롤해 들어간 섹션의 머리글이 퀘스트 목록 맨 위에 계속 표시되어, 지금 어느 섹션에 있는지 항상 알 수 있습니다. 기본은 켜짐."
L["The most of the tracker the world quest area may take. Quest sections are given their space first, so this is a ceiling rather than a reservation. Only used while Set a custom World Quests height is off."] = "전역 퀘스트 영역이 추적기에서 차지할 수 있는 최대치입니다. 퀘스트 섹션에 먼저 자리를 주므로 확보가 아니라 상한입니다. 전역 퀘스트 높이 직접 지정이 꺼져 있을 때만 사용됩니다."
L["The most of this crest you're allowed to earn this season - the seasonal earning cap."] = "이번 시즌에 획득할 수 있는 이 문장의 최대 개수 - 시즌 획득 한도입니다."
L["The seasonal cap on this crest - how many you can earn for the lower crests, and how many you can hold at once for the higher ones."] = "이 문장의 시즌 한도입니다 - 하위 문장은 획득할 수 있는 개수, 상위 문장은 동시에 보유할 수 있는 개수를 뜻합니다."
L["These are the round red markers Everything Quests puts on the big world map for quests you've already picked up (the ones in your quest log). A red \"!\" means \"go here for this quest's next step.\" A red \"?\" means \"this quest is done \226\128\148 go here to turn it in.\" Quests you haven't accepted yet keep the game's own yellow \"!\" markers; EQ does not change those. Uncheck this box and all of EQ's red markers go away."] = "이미 수락한(퀘스트 일지에 있는) 퀘스트에 대해 Everything Quests가 큰 지도에 찍는 둥근 빨간 표시입니다. 빨간 \"!\"는 \"이 퀘스트의 다음 단계로 가라\", 빨간 \"?\"는 \"이 퀘스트는 완료됨 - 여기서 완료하라\"는 뜻입니다. 아직 수락 안 한 퀘스트는 게임 기본 노란 \"!\" 표시를 그대로 둡니다(EQ는 그것을 바꾸지 않음). 이 설정을 끄면 EQ의 빨간 표시가 모두 사라집니다."
L["Three of the six unlock from the quest \"%s\"."] = "여섯 중 셋은 \"%s\" 퀘스트로 해금됩니다."
L["Turns all six category filters back on and clears the current-zone filter. Nothing else on this tab is changed."] = "여섯 개 분류 필터를 모두 다시 켜고 현재 지역 필터를 해제합니다. 이 탭의 다른 설정은 바뀌지 않습니다."
L["Type:"] = "유형:"
L["Use class color for titles"] = "제목에 직업 색상 사용"
L["When cleared, falls back to difficulty coloring or default yellow."] = "비우면 난이도 색상 또는 기본 노란색으로 돌아갑니다."
L["While inside a delve, tracks the two bonus-chest objectives - Nemesis Strongbox packs and the Sanctified Banner - so you know you've grabbed the extra loot before pulling the boss."] = "구렁 안에서 추가 상자 목표 두 가지 - 원수의 금고 무리와 Sanctified Banner - 를 추적해, 우두머리를 끌기 전에 추가 전리품을 챙겼는지 알 수 있게 해 줍니다."
L["|cffEBB706EQ Chain Guide:|r found quest |cffffffff%d|r%s — jumping to its chain."] = "|cffEBB706EQ 연계 가이드:|r 퀘스트 |cffffffff%d|r%s을 찾았습니다 - 해당 연계로 이동."
L["|cffEBB706EQ Chain Guide:|r found |cffffffff%s|r — jumping to its chain."] = "|cffEBB706EQ 연계 가이드:|r |cffffffff%s|r을 찾았습니다 - 해당 연계로 이동."
L["|cffEBB706EQ Chain Guide:|r no chain quest matches |cffffffff%s|r."] = "|cffEBB706EQ 연계 가이드:|r |cffffffff%s|r와 일치하는 연계 퀘스트가 없습니다."

return L
