-- store/_retired/ruRU.lua
-- Russian translations for phrases no addon in the family currently uses.
--
-- NOT dead. A phrase lands here when the last addon using it drops or rewords it,
-- and scan.py moves it straight back into store/ruRU.lua the moment any addon
-- starts using that exact English key again. Everything Quests v1.38.0 moved 224
-- phrases to EQ Objective Tracker in one release - this is what stops that costing
-- a translation.
--
-- Nothing here reaches the game. There is no reason to translate anything in this
-- file, and no reason to delete anything from it either.

local L = {}

L["%d hidden entries restored."] = "Восстановлено скрытых записей: %d"
L["/eqs\n/everythingquests\n\n|cff999999Both open this options window.|r\n\n/eqs whatsnew\n\n|cff999999Show what's new in the latest update.|r\n\n/eqs session\n\n|cff999999Show a recap of your current play session.|r"] = "/eqs\n/everythingquests\n\n|cff999999Обе открывают это окно настроек.|r\n\n/eqs whatsnew\n\n|cff999999Показать, что нового в последнем обновлении.|r\n\n/eqs session\n\n|cff999999Показать итоги текущей игровой сессии.|r"
L["A unified replacement for the Blizzard quest experience: a custom tracker, objective markers on the map and minimap, nameplate quest icons, and a browser for the quests you have not picked up yet."] = "Единая замена стандартному квестовому интерфейсу Blizzard: собственный трекер, метки целей на карте мира и мини-карте, иконки заданий возле полоски здоровья и обозреватель заданий, которые вы ещё не взяли."
L["A unified replacement for the Blizzard quest experience: a custom tracker, world-map overlays, quest history, and a Midnight chain guide."] = "Единая замена стандартному квестовому интерфейсу Blizzard: собственный трекер, наложения на карту мира, история заданий и гид по цепочкам для Midnight."
L["Adds the quest log heading each quest came from as a small line under its title."] = "Добавляет под названием задания небольшую строку с заголовком журнала заданий, под которым оно находится."
L["Also reads the progress other quest addons broadcast, so you see everyone in the group rather than only the people running EQ. When you join a group EQ asks those addons for their quest logs, the same way they ask each other. Your own progress is never sent on their channel."] = "Также читает прогресс, который передают другие аддоны заданий, чтобы вы видели всю группу, а не только тех, у кого стоит EQ. Когда вы вступаете в группу, EQ запрашивает у этих аддонов журналы заданий так же, как они запрашивают их друг у друга. Ваш собственный прогресс никогда не отправляется по их каналу."
L["An on-screen panel while inside a delve showing the story variant and its grade, the recommended curios for your role, your run timer, and your death count."] = "Панель на экране внутри вылазки, показывающая вариацию истории и ее ранг, рекомендованные диковинки для вашей роли, таймер прохождения и число смертей."
L["Bonus Spoils: Nemesis Strongbox packs + the Sanctified Banner — the bonus loot to grab before the boss."] = "Бонусная добыча: группы у Сейфа Немезиды + Sanctified Banner — дополнительная добыча, которую стоит забрать до босса."
L["Bring back every entry you have hidden"] = "Вернуть все скрытые вами записи"
L["By default the World Quests area shares space with your quest list and gets squeezed when you have a lot of quests. Turn this on to give it its own height, set by the slider below."] = "По умолчанию область локальных заданий делит место со списком заданий и сжимается, когда заданий много. Включите, чтобы задать ей собственную высоту с помощью ползунка ниже."
L["Categories"] = "Категории"
L["Collapse the category and chain list so the graph fills the whole window. Click again to bring it back."] = "Сворачивает список категорий и цепочек, чтобы схема заняла всё окно. Нажмите ещё раз, чтобы вернуть её."
L["Colors & Dimensions"] = "Цвета и размеры"
L["Colors each quest title by how hard it is for your level, the way the quest log does. The Quest Title Color Override on the Appearance tab wins over this while it is set."] = "Окрашивает название каждого задания по его сложности для вашего уровня, как это делает журнал заданий. Параметр «Цвет заданий» на вкладке «Внешний вид» имеет приоритет, пока он задан."
L["Colors quest, achievement, and endeavor titles with the class color of the character you are currently logged in on. Overrides the color above while it is on. Off by default."] = "Окрашивает названия заданий, достижений и устремлений в цвет класса персонажа, за которого вы сейчас играете. Пока включено, заменяет цвет выше. По умолчанию выкл."
L["Colors quest, achievement, and endeavor titles with the class color of the character you are currently logged in on. Overrides the color below while it is on. Off by default."] = "Окрашивает названия заданий, достижений и устремлений в цвет класса персонажа, за которого вы сейчас играете. Пока включено, заменяет цвет ниже. По умолчанию выкл."
L["Colors the section headers (Quests, Campaign, and so on) with the class color of the character you are currently logged in on. Overrides the color above while it is on. Off by default."] = "Окрашивает заголовки разделов (Задания, Кампания и т.д.) в цвет класса персонажа, за которого вы сейчас играете. Пока включено, заменяет цвет выше. По умолчанию выкл."
L["Draws a filled bar for objectives that report a percentage or a running total, the way the default tracker does, instead of a plain line of text. Applies to quests, World Quests, achievements and scenario objectives."] = "Для целей, которые показывают проценты или текущий счетчик, рисует заполненную полосу вместо обычной строки текста, как это делает стандартный трекер. Работает для заданий, локальных заданий, достижений и целей сценариев."
L["Draws the red circle behind every world map marker for a quest in your log, both the ones you are still working on and the ones that are ready to turn in. Off by default for plain icons and a much quieter map when a zone is busy."] = "Рисует красный круг позади каждой метки на карте мира для задания из вашего журнала - и для тех, что ещё в работе, и для тех, что готовы к сдаче. По умолчанию отключено, чтобы значки были простыми, а карта заметно спокойнее в оживлённой зоне."
L["Draws the red circle behind every world map marker for a quest in your log, both the ones you are still working on and the ones that are ready to turn in. Off by default for plain icons and a much quieter map when a zone is busy. The gold ring on quests you have not picked up yet is left alone, because it is the only thing telling those apart from the quests you are already carrying."] = "Рисует красный круг позади каждой метки на карте мира для задания из вашего журнала - и для тех, что ещё в работе, и для тех, что готовы к сдаче. По умолчанию отключено, чтобы значки были простыми, а карта заметно спокойнее в оживлённой зоне. Золотое кольцо у заданий, которые вы ещё не взяли, остаётся на месте, потому что только оно отличает их от заданий, которые вы уже несёте."
L["Draws the red circle behind every world map marker for a quest in your log, both the ones you are still working on and the ones that are ready to turn in. Uncheck it for plain icons and a much quieter map when a zone is busy. The gold ring on quests you have not picked up yet is left alone, because it is the only thing telling those apart from the quests you are already carrying."] = "Рисует красный круг позади каждой метки на карте мира для задания из вашего журнала - и для тех, что ещё в работе, и для тех, что готовы к сдаче. Снимите галочку, чтобы получить простые значки и гораздо более спокойную карту в оживлённой зоне. Золотое кольцо у заданий, которые вы ещё не взяли, остаётся на месте, потому что только оно отличает их от заданий, которые вы уже несёте."
L["for WoW Midnight (12.0.x)"] = "для WoW Midnight (12.0.x)"
L["Frosthearth Venom \226\128\148 cuts enemy attack and cast speed by 20 percent, which buys time on both Soul Extinction and the Void Toxin dispel."] = "Frosthearth Venom — снижает скорость атаки и сотворения заклинаний врагов на 20 процентов, что дает запас времени и на Soul Extinction, и на снятие Void Toxin."
L["Go"] = "Искать"
L["Header Bar"] = "Полоса заголовка"
L["Home"] = "Главная"
L["Instead of green."] = "Вместо зелёного."
L["Leaves out quests that are sorted into a dungeon or a raid. There are 721 of them, and most are picked up inside the instance or from a quest giver at its door, so they clutter the outdoor map without helping you while you are questing in the world."] = "Убирает задания, относящиеся к подземелью или рейду. Их 721, и большинство берётся внутри подземелья или у персонажа возле входа, поэтому они засоряют карту внешнего мира, ничем не помогая, пока вы выполняете задания снаружи."
L["Leaves out quests the game has already greyed out for you, using the game's own threshold rather than a fixed number of levels. On by default. Turn it off to see everything a quest giver has, including the quests you have outlevelled."] = "Не показывает задания, которые игра уже сделала серыми, используя собственный порог игры, а не фиксированное число уровней. Включено по умолчанию. Отключите, чтобы видеть всё, что предлагает дающий задания, включая задания, которые вы переросли."
L["Leaves out the 141 quests that require a trade skill, such as a Blacksmithing or Alchemy specialisation. Everything Quests cannot read your skill levels on this version of the game, so these are offered even when you have not trained the profession they need."] = "Убирает 141 задание, требующее профессии, например специализации в кузнечном деле или алхимии. Everything Quests не может прочитать ваши уровни навыков в этой версии игры, поэтому такие задания предлагаются, даже если вы не обучались нужной профессии."
L["Leaves out the 141 quests that require a trade skill, such as a Blacksmithing or Alchemy specialization. Everything Quests cannot read your skill levels on this version of the game, so these are offered even when you have not trained the profession they need."] = "Убирает 141 задание, требующее профессии, например специализации в кузнечном деле или алхимии. Everything Quests не может прочитать ваши уровни навыков в этой версии игры, поэтому такие задания предлагаются, даже если вы не обучались нужной профессии."
L["Leaves out the quests you can hand in over and over, usually a turn-in for reputation or a common trade good. There are 609 of them and they never stop being offered, so they stay on the map forever once you can see them."] = "Убирает задания, которые можно сдавать снова и снова, обычно ради репутации или за обычное ремесленное сырьё. Их 609, и их предлагают бесконечно, поэтому они навсегда остаются на карте, как только становятся видны."
L["Look up any quest in the game"] = "Найти любое задание в игре"
L["Look up any quest in the game, including ones you have never picked up. Shows the level and race and class requirements, where it starts and turns in, what has to be finished first, and why you cannot take it yet. Also on /eqs quests, or right-click a gold quest marker on the map."] = "Найдите любое задание в игре, включая те, которые вы никогда не брали. Показывает уровень, требования к расе и классу, где оно начинается и где сдаётся, что нужно выполнить сначала и почему вы пока не можете его взять. Также доступно через /eqs quests или по правому щелчку на золотой метке задания на карте."
L["Lv %d  •  ID %d"] = "Ур. %d  •  ID %d"
L["Marks every quest giver who has something for you but is not in your quest log yet, with a gold ring around the exclamation mark so it reads apart from the quests you are already carrying. One marker covers a whole quest giver, and hovering it lists everything that giver offers. Quests are filtered by your level, race, class and the quests you have already finished. Holiday quests are left out, because nothing in the data says whether the holiday is running."] = "Отмечает каждого, у кого есть задание для вас, которого ещё нет в вашем журнале, золотым кольцом вокруг восклицательного знака, чтобы отличать их от уже взятых заданий. Один маркер охватывает всего дающего задания целиком, а наведение на него покажет всё, что он предлагает. Задания отбираются по вашему уровню, расе, классу и уже выполненным заданиям. Праздничные задания исключены, так как в данных нет сведений о том, идёт ли праздник."
L["Maximum Height (% of tracker)"] = "Максимальная высота (в процентах от трекера)"
L["nothing is hidden."] = "Ничего не скрыто"
L["Off: Everything Quests stops putting World Quests on the map — no world-map pins, no reward summary box, no zone quest list. The boxes below do nothing while this is off. This switch is ONLY for World Quests. It does NOT remove the red \"!\" / \"?\" quest rings — those are your normal quests, and you turn them off on the General tab. It also does NOT change the World Quests list in your tracker (that's on the Tracker tab)."] = "Выкл: Everything Quests перестанет наносить локальные задания на карту - ни меток на карте мира, ни окна сводки наград, ни списка заданий зоны. Пока эта опция выключена, настройки ниже не работают. \n\nЭтот переключатель ТОЛЬКО для локальных заданий. Он НЕ убирает значки \"!\" / \"?\" - это ваши обычные задания, они отключаются на вкладке «Основные». \n\nОн также НЕ меняет список локальных заданий в трекере (это на вкладке «Трекер»)."
L["Pick a category"] = "Выберите категорию"
L["Quest pins already grow as you zoom in and shrink as you zoom out. This scales that whole range, so raise it if the pins are hard to pick out on a large or high-resolution display."] = "Метки заданий и так увеличиваются при приближении и уменьшаются при отдалении. Этот ползунок масштабирует весь диапазон: увеличьте его, если метки трудно разглядеть на большом экране или при высоком разрешении."
L["Quest Title Color By Difficulty"] = "Цвет названия задания по сложности"
L["Quest Title Color Override"] = "Цвет заданий"
L["Restore every option to its default value."] = "Вернуть каждой опции значение по умолчанию."
L["Restores every setting on every tab to its default and reloads the interface. This also clears the Options Window Scale, which every character shares, and this character's collapsed sections and individually hidden entries."] = "Восстанавливает значения по умолчанию для всех настроек на всех вкладках и перезагружает интерфейс. Также сбрасывается «Масштаб окна настроек», общий для всех персонажей, а также свёрнутые разделы и скрытые по отдельности записи этого персонажа."
L["Sanctified Banner - find it for bonus loot"] = "Sanctified Banner - найдите его ради бонусной добычи"
L["Sanctified Banner - Grand Spoils earned!"] = "Sanctified Banner - крупная добыча получена!"
L["Sanctified Banner - kill the Voidfused Rager!"] = "Sanctified Banner - убейте Voidfused Rager!"
L["Sanctified Banner found - bonus Spoils secured"] = "Sanctified Banner найден - бонусная добыча обеспечена"
L["Season 2 also gives her a Poison slot. This popup does not cover it yet - the Nemesis tab already recommends one for Azta'rec."] = "Во 2 сезоне у нее также появилась ячейка яда. Это окно ее пока не охватывает - вкладка Немезиды уже рекомендует яд для Azta'rec."
L["Show Options icon on the tracker"] = "Показывать значок настроек на трекере"
L["Slash commands"] = "Чат-команды"
L["The most of this crest you're allowed to earn this season - the seasonal earning cap."] = "Сколько таких гербов вам разрешено заработать за сезон - сезонный предел заработка."
L["The seasonal cap on this crest - how many you can earn for the lower crests, and how many you can hold at once for the higher ones."] = "Сезонный предел для этого герба - для младших гербов это сколько можно заработать, а для старших - сколько можно иметь одновременно."
L["These are the round red markers Everything Quests puts on the big world map for quests you've already picked up (the ones in your quest log). A red \"!\" means \"go here for this quest's next step.\" A red \"?\" means \"this quest is done \226\128\148 go here to turn it in.\" Quests you haven't accepted yet keep the game's own yellow \"!\" markers; EQ does not change those. Uncheck this box and all of EQ's red markers go away."] = "Это круглые метки, которые Everything Quests ставит на карте мира для заданий, которые уже взяты (те, что в журнале заданий). \nКрасный \"!\" означает «иди сюда для следующего шага этого задания». \nКрасный \"?\" означает «это задание выполнено - иди сюда, чтобы сдать его». \nЗадания, которые вы ещё не приняли, сохраняют стандартные жёлтые метки \"!\" игры; EQ их не меняет. Снимите эту галочку - и все красные метки EQ исчезнут."
L["Three of the six unlock from the quest \"%s\"."] = "Три из шести открываются в задании \"%s\"."
L["Turns all six category filters back on and clears the current-zone filter. Nothing else on this tab is changed."] = "Снова включает все шесть фильтров категорий и снимает фильтр текущей зоны. Больше ничего на этой вкладке не меняется."
L["Use class color for titles"] = "Использовать цвет класса для названий"
L["When cleared, falls back to difficulty coloring or default yellow."] = "Если не задано, используется цвет по сложности или стандартный жёлтый."
L["While inside a delve, tracks the two bonus-chest objectives - Nemesis Strongbox packs and the Sanctified Banner - so you know you've grabbed the extra loot before pulling the boss."] = "Внутри вылазки отслеживает две цели с бонусными сундуками - группы у Сейфа Немезиды и Sanctified Banner - чтобы вы знали, что забрали дополнительную добычу до того, как пулить босса."
L["|cffEBB706EQ Chain Guide:|r found quest |cffffffff%d|r%s — jumping to its chain."] = "|cffEBB706EQ Гид по цепочкам:|r задание |cffffffff%d|r%s найдено - переход к его цепочке."
L["|cffEBB706EQ Chain Guide:|r found |cffffffff%s|r — jumping to its chain."] = "|cffEBB706Путеводитель по цепочкам:|r найдено |cffffffff%s|r - переход к цепочке."
L["|cffEBB706EQ Chain Guide:|r no chain quest matches |cffffffff%s|r."] = "|cffEBB706Путеводитель по цепочкам:|r ни одно задание цепочки не соответствует |cffffffff%s|r."

return L
