-- store/_retired/zhTW.lua
-- Traditional Chinese translations for phrases no addon in the family currently uses.
--
-- NOT dead. A phrase lands here when the last addon using it drops or rewords it,
-- and scan.py moves it straight back into store/zhTW.lua the moment any addon
-- starts using that exact English key again. Everything Quests v1.38.0 moved 224
-- phrases to EQ Objective Tracker in one release - this is what stops that costing
-- a translation.
--
-- Nothing here reaches the game. There is no reason to translate anything in this
-- file, and no reason to delete anything from it either.

local L = {}

L["%d hidden entries restored."] = "%d 條隱藏記錄已恢復。"
L["%s  \194\183  %s quests  \194\183  %s  \194\183  %s XP"] = "%s  •  %s 個任務  •  %s  •  %s 經驗"
L["%s%s|r %s(%s)|r%s  \226\128\148  %s%d|r in progress  %s%d|r banked  %s%d|r done  %s%d|r left"] = "%s%s|r %s(%s)|r%s  —  進行中 %s%d|r  已囤積 %s%d|r  已完成 %s%d|r  剩餘 %s%d|r"
L["/eqs\n/everythingquests\n\n|cff999999Both open this options window.|r\n\n/eqs whatsnew\n\n|cff999999Show what's new in the latest update.|r\n\n/eqs session\n\n|cff999999Show a recap of your current play session.|r"] = "/eqs\n/everythingquests\n\n|cff999999以上兩條命令均可打開此設置視窗。|r\n\n/eqs whatsnew\n\n|cff999999查看本次更新的新內容。|r\n\n/eqs session\n\n|cff999999查看當前遊戲會話統計。|r"
L["[Done] %s - completed"] = "[完成] %s - 已完成"
L["[Done] Fangs for the Memories complete \226\128\148 Corrosive Victory earned."] = "[完成] Fangs for the Memories 已完成 — 已獲得 Corrosive Victory。"
L["[Done] Gilded Stash earned! (%d / %d)"] = "[完成] 已獲得鎏金寶藏！（%d / %d）"
L["[Done] SA: %s"] = "[完成] 特殊任務：%s"
L["A unified replacement for the Blizzard quest experience: a custom tracker, objective markers on the map and minimap, nameplate quest icons, and a browser for the quests you have not picked up yet."] = "一套完整替代暴雪任務體驗的工具：自訂追蹤器、世界地圖與小地圖上的目標標記、姓名板任務圖示，以及尚未接取任務的瀏覽器。"
L["A unified replacement for the Blizzard quest experience: a custom tracker, world-map overlays, quest history, and a Midnight chain guide."] = "一套完整替代暴雪任務體驗的工具：自訂追蹤器、世界地圖覆蓋層、任務歷史記錄以及午夜版本任務鏈指南。"
L["Account-wide alt overview"] = "全帳號分身總覽"
L["Account-wide quest rewards. Totals count only quests turned in while reward tracking was on; older entries didn't capture XP or gold."] = "帳號級任務獎勵統計。僅統計開啟獎勵追蹤後提交的任務；更早的歷史記錄不會捕獲經驗與金幣。"
L["Adds the quest log heading each quest came from as a small line under its title."] = "在任務標題下方小字顯示該任務所屬的任務日誌分類。"
L["Also reads the progress other quest addons broadcast, so you see everyone in the group rather than only the people running EQ. When you join a group EQ asks those addons for their quest logs, the same way they ask each other. Your own progress is never sent on their channel."] = "同時讀取其他任務插件廣播的進度，這樣你能看到隊伍中的所有人，而不只是使用 EQ 的玩家。加入隊伍時，EQ 會像這些插件彼此之間那樣向它們請求任務日誌。你自己的進度絕不會透過它們的頻道發送。"
L["An on-screen panel while inside a delve showing the story variant and its grade, the recommended curios for your role, your run timer, and your death count."] = "在探究中的畫面面板，顯示劇情變體及其評級、適合你職責的建議珍奇物品、計時器和死亡次數。"
L["Better questing for WoW Forever: objective markers on the world map and minimap, every quest giver with something for you, a guide to the quest chains, a browser for almost any quest you have not picked up yet, and quest progress on tooltips and nameplates."] = "為WoW Forever提升任務體驗：世界地圖與小地圖目標標記、所有可接任務NPC、任務鏈指南、幾乎任何未接取任務的瀏覽器，以及滑鼠提示與姓名板任務進度。"
L["Biggest gold:  (none yet)"] = "單次最高金幣：（暫無）"
L["Biggest gold:  |cffffffff%s|r  \194\183  %s"] = "單次最高金幣：|cffffffff%s|r  •  %s"
L["Biggest XP:    (none yet)"] = "單次最高經驗：（暫無）"
L["Biggest XP:    |cffffffff%s|r  \194\183  %s XP"] = "單次最高經驗：|cffffffff%s|r  •  %s 經驗"
L["Bonus Spoils: Nemesis Strongbox packs + the Sanctified Banner — the bonus loot to grab before the boss."] = "額外戰利品：死敵保險箱的怪物組 + Sanctified Banner — 開首領之前該拿到手的額外戰利品。"
L["Bounty looted and used this week. [Done]"] = "本週已拾取並使用。[完成]"
L["Bring back every entry you have hidden"] = "恢復所有被隱藏的記錄"
L["Categories"] = "分類"
L["Character:"] = "角色："
L["Clear History"] = "清空歷史"
L["Collapse the category and chain list so the graph fills the whole window. Click again to bring it back."] = "收起分類與任務鏈列表，讓時間線圖表佔滿視窗，再次點擊恢復。"
L["Collectibles for defeating Azta'rec this season (item icons appear once their IDs are confirmed):"] = "本賽季擊敗 Azta'rec 可獲得的收藏品（物品 ID 確認後會顯示圖示）："
L["Colors & Dimensions"] = "顏色與尺寸"
L["Colors each quest title by how hard it is for your level, the way the quest log does. The Quest Title Color Override on the Appearance tab wins over this while it is set."] = "像原生任務日志一樣，按等級難度渲染任務標題顏色。外觀頁的任務標題強制顏色優先級更高。"
L["Colors quest, achievement, and endeavor titles with the class color of the character you are currently logged in on. Overrides the color above while it is on. Off by default."] = "使用當前登錄角色職業顏色渲染任務、成就、活動標題。開啟後覆蓋上面設置，預設關閉。"
L["Colors quest, achievement, and endeavor titles with the class color of the character you are currently logged in on. Overrides the color below while it is on. Off by default."] = "使用當前登錄角色職業顏色渲染任務、成就、活動標題。開啟後覆蓋下面設置，預設關閉。"
L["Colors the section headers (Quests, Campaign, and so on) with the class color of the character you are currently logged in on. Overrides the color above while it is on. Off by default."] = "使用當前登錄角色職業顏色渲染板塊標題。開啟後覆蓋上面設置，預設關閉。"
L["Date:"] = "日期："
L["Draws a filled bar for objectives that report a percentage or a running total, the way the default tracker does, instead of a plain line of text. Applies to quests, World Quests, achievements and scenario objectives."] = "對於會給出百分比或累計數值的目標，像預設追蹤器那樣繪製一條填滿的進度條，而不是單純的一行文字。適用於任務、世界任務、成就和場景戰目標。"
L["Erase all recorded delve runs and lifetime stats"] = "抹除所有已記錄的探究紀錄與累計統計"
L["Fangs for the Memories \226\128\148 the one-time seasonal quest that awards the Corrosive Victory toy. Live tracking starts once its quest ID is confirmed."] = "Fangs for the Memories — 授予 Corrosive Victory 玩具的一次性賽季任務。任務 ID 確認後才會開始即時追蹤。"
L["For example, 3/9. Applies to every section header."] = "例如：3/9，作用於全部板塊標題。"
L["for WoW Midnight (12.0.x)"] = "適用於魔獸世界午夜版本（12.0.x）"
L["Frosthearth Venom \226\128\148 cuts enemy attack and cast speed by 20 percent, which buys time on both Soul Extinction and the Void Toxin dispel."] = "Frosthearth Venom — 使敵人的攻擊與施法速度降低 20％，為 Soul Extinction 和 Void Toxin 的驅散都爭取到時間。"
L["Go"] = "前往"
L["Header Bar"] = "標題條帶"
L["Home"] = "主頁"
L["Instead of green."] = "替換綠色顯示。"
L["Insufficient Undercoins."] = "地底幣不足。"
L["Lv %d  •  ID %d"] = "等級 %d  • 任務ID %d"
L["Marks every quest giver who has something for you but is not in your quest log yet, with a gold ring around the exclamation mark so it reads apart from the quests you are already carrying. One marker covers a whole quest giver, and hovering it lists everything that giver offers. Quests are filtered by your level, race, class and the quests you have already finished. Holiday quests are left out, because nothing in the data says whether the holiday is running."] = "給尚未接取的任務NPC感嘆號新增金色外圈標記；一個標記對應整個NPC，滑鼠懸浮顯示全部可接任務。按等級、種族、職業、已完成任務過濾；節日任務不會標記，插件無法判斷節日是否開啟。"
L["Maximum Height (% of tracker)"] = "最大高度（佔追蹤器百分比）"
L["nothing is hidden."] = "沒有隱藏項目。"
L["Off: Everything Quests stops putting World Quests on the map — no world-map pins, no reward summary box, no zone quest list. The boxes below do nothing while this is off. This switch is ONLY for World Quests. It does NOT remove the red \"!\" / \"?\" quest rings — those are your normal quests, and you turn them off on the General tab. It also does NOT change the World Quests list in your tracker (that's on the Tracker tab)."] = "關閉：不再在地圖渲染世界任務標記、獎勵匯總框、區域任務列表。該開關僅控制世界任務；不會移除普通任務紅色!/?標記（在通用頁關閉）；也不修改追蹤器內世界任務列表（追蹤器頁設置）。"
L["Pick a category"] = "選擇分類"
L["Quest Title Color By Difficulty"] = "按難度著色任務標題"
L["Quest Title Color Override"] = "強制任務標題顏色"
L["Restore every option to its default value."] = "把每一項設定恢復為預設值。"
L["Restores every setting on every tab to its default and reloads the interface. This also clears the Options Window Scale, which every character shares, and this character's collapsed sections and individually hidden entries."] = "全部標簽頁恢復預設並重載界面。同時重置全角色共享的選項窗口縮放，以及本角色折疊板塊、單獨隱藏條目。"
L["Runs kept per delve:"] = "每個探究保留的紀錄數："
L["Sanctified Banner - find it for bonus loot"] = "Sanctified Banner - 找到它即可獲得額外戰利品"
L["Sanctified Banner - Grand Spoils earned!"] = "Sanctified Banner - 已獲得豐厚戰利品！"
L["Sanctified Banner - kill the Voidfused Rager!"] = "Sanctified Banner - 擊殺 Voidfused Rager！"
L["Sanctified Banner found - bonus Spoils secured"] = "已找到 Sanctified Banner - 額外戰利品到手"
L["Season 2 also gives her a Poison slot. This popup does not cover it yet - the Nemesis tab already recommends one for Azta'rec."] = "第 2 賽季還給了她一個毒藥欄。這個彈窗暫時還不涵蓋它 - 死敵頁面已經為 Azta'rec 建議了一種。"
L["Set!"] = "已設定！"
L["Show Options icon on the tracker"] = "追蹤框顯示設置圖標"
L["Slash commands"] = "聊天命令"
L["The header of the section you are scrolled into stays at the top of the quest list, so you can always see which section you are in. On by default."] = "當前滾動所在板塊的標題會固定在任務列表頂部，隨時可知自己位於哪個板塊。預設開啟。"
L["The most of this crest you're allowed to earn this season - the seasonal earning cap."] = "本賽季你最多能獲得的該紋章數量 - 也就是賽季取得上限。"
L["The Nemesis Delve"] = "死敵探究"
L["the one-time seasonal quest; defeat Azta'rec to earn it."] = "一次性賽季任務；擊敗 Azta'rec 即可獲得。"
L["The seasonal cap on this crest - how many you can earn for the lower crests, and how many you can hold at once for the higher ones."] = "該紋章的賽季上限 - 低階紋章指你能取得的數量，高階紋章指你能同時持有的數量。"
L["Three of the six unlock from the quest \"%s\"."] = "六種中有三種透過任務 \"%s\" 解鎖。"
L["Tip: right-click the minimap button to jump to Options. For support, the author may ask you to run a debug command."] = "提示：右鍵點擊小地圖按鈕可直接跳到設定。為了協助排查問題，作者可能會請你執行某個除錯指令。"
L["Turns all six category filters back on and clears the current-zone filter. Nothing else on this tab is changed."] = "重新開啟全部6項分類篩選，清除當前區域篩選。本標簽頁其餘選項保持不變。"
L["Type:"] = "類型："
L["Updated"] = "更新"
L["Use class color for titles"] = "任務標題使用職業顏色"
L["When cleared, falls back to difficulty coloring or default yellow."] = "清空後將使用任務難度顏色或預設黃色。"
L["While inside a delve, tracks the two bonus-chest objectives - Nemesis Strongbox packs and the Sanctified Banner - so you know you've grabbed the extra loot before pulling the boss."] = "在探究中追蹤兩個額外寶箱目標 - 死敵保險箱的怪物組和 Sanctified Banner - 讓你在開首領之前確認額外戰利品都已到手。"
L["|cffEBB706EQ Chain Guide:|r found quest |cffffffff%d|r%s — jumping to its chain."] = "|cffEBB706EQ任務鏈嚮導：|r找到任務 |cffffffff%d|r%s — 跳轉至該任務鏈。"
L["|cffEBB706EQ Chain Guide:|r found |cffffffff%s|r — jumping to its chain."] = "|cffEBB706EQ任務鏈嚮導：|r找到 |cffffffff%s|r — 跳轉至該任務鏈。"
L["|cffEBB706EQ Chain Guide:|r no chain quest matches |cffffffff%s|r."] = "|cffEBB706EQ任務鏈嚮導：|r沒有匹配 |cffffffff%s|r 的任務鏈。"
L["|cffEBB706EQ|r: the quest browser needs the Classic quest data, which this version of the game does not load."] = "|cffEBB706EQ|r：任務瀏覽器需要懷舊服任務數據，而此版本的遊戲不會加載這些數據。"

return L
